import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-echoes-'));
for(const name of ['data','engine','progression','cosmetics','summons','carmilla'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave,SAVE_KEY,findPath}=await import(pathToFileURL(join(out,'engine.js')).href),{MAPS}=await import(pathToFileURL(join(out,'data.js')).href),{ANCHORS,EVENTS}=await import(pathToFileURL(join(out,'progression.js')).href),{COSMETICS,RARITIES,chooseCosmetic}=await import(pathToFileURL(join(out,'cosmetics.js')).href);
let checks=0;const check=(ok,msg)=>{assert.ok(ok,msg);checks++;};const store=new Map();global.localStorage={setItem:(k,v)=>store.set(k,v),getItem:k=>store.get(k)||null};
const timers=[];global.setTimeout=cb=>{timers.push(cb);return 1;};const flush=()=>{let n=0;while(timers.length&&n++<100)timers.shift()();check(n<100,'animation settles');};const fresh=()=>{const g=new GameEngine();g.start();g.finishCutscene();return g;};
check(COSMETICS.length===50&&new Set(COSMETICS.map(c=>c.id)).size===50,'50 unique obtainable cosmetic items');check(RARITIES.reduce((n,r)=>n+r.weight,0)===100,'rarity odds total 100%');
const rolls=[0,.56,.82,.95,.995];
for(let family=0;family<10;family++)for(let rank=0;rank<5;rank++){let call=0;const c=chooseCosmetic(0,()=>call++? (family+.2)/10:rolls[rank]);check(c.id===COSMETICS[family*5+rank].id,'every item has a reachable draw');check(c.description&&c.craftCost===c.rank*8,'every item has a battle effect and alternate acquisition');}
for(const roll of [0,.55,.8,.94,.999]){check(chooseCosmetic(9,()=>roll).rank>=4,'tenth draw guarantees epic or legendary');}
const g=fresh();g.state.progress.tokens=20;check(g.drawCosmetic(()=>0),'first draw works');check(g.state.progress.tokens===19&&g.state.progress.cosmetics.length===1,'draw spends one token and gives actual collection item');check(!g.drawCosmetic(()=>0)&&g.state.progress.tokens===19,'rapid double tap cannot spend twice');flush();check(g.drawCosmetic(()=>0),'second draw works');flush();check(g.state.progress.dust===1&&g.state.progress.cosmetics.length===1&&g.state.progress.lastDuplicate,'duplicate becomes dust');
for(let i=2;i<10;i++){check(g.drawCosmetic(()=>0),'draw available');flush();}check(g.state.progress.lastDraw==='jade-4'&&g.state.progress.pity===0,'pity guarantees epic and resets');check(g.state.progress.cosmetics.includes('jade-4'),'guaranteed item is awarded');
g.state.progress.tokens=0;check(!g.drawCosmetic()&&g.state.progress.rolls===10,'no free draws');check(!g.craftCosmetic('azul-5'),'crafting requires enough dust');g.state.progress.dust=40;check(g.craftCosmetic('azul-5')&&g.state.progress.dust===0,'craft chosen missing legendary');check(!g.craftCosmetic('azul-5'),'cannot craft same owned item twice');
check(!g.equipCosmetic('seiji','nanquim-5'),'unowned item cannot be equipped');check(g.equipCosmetic('seiji','jade-4')&&g.state.heroes[0].maxHp===97,'cosmetic changes real maximum HP');check(g.equipCosmetic('ophelia','jade-4')&&!g.state.progress.cosmeticEquipment.seiji&&g.state.progress.cosmeticEquipment.ophelia==='jade-4','one unique piece transfers between heroes');check(g.equipCosmetic('ophelia'),'aura can be removed');
for(const item of COSMETICS.filter(c=>c.rank===5))g.state.progress.cosmetics.push(item.id);
g.equipCosmetic('seiji','nanquim-5');check(g.attackPower('seiji')===29,'ink cosmetic changes physical damage');g.equipCosmetic('ophelia','geada-5');check(g.skills('ophelia').find(s=>s.id==='shard').description.startsWith('37'),'ice cosmetic changes displayed and real spell power');check(g.healPower('ophelia',36)===36,'damage-only aura does not secretly add healing');g.equipCosmetic('ophelia','orvalho-5');check(g.healPower('ophelia',36)===46,'dew cosmetic changes healing');g.equipCosmetic('ophelia','vento-5');check(g.state.heroes[1].spd===16,'wind affects real speed');
g.equipCosmetic('seiji','vigilia-5');g.state.heroes[0].mp=1;g.equipCosmetic('ophelia');g.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));check(g.currentHero().id==='seiji','guard test hero starts');check(g.action('guard'),'guard action accepted');flush();check(g.state.heroes[0].mp===9,'vigil aura actually recovers eight MP');
g.state.mode='world';g.state.battle=null;g.equipCosmetic('seiji','estrela-5');g.state.heroes[0].hp=20;g.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));g.action('attack');flush();check(g.state.heroes[0].hp===25,'physical attack drain restores five HP');
g.state.mode='world';g.state.battle=null;g.equipCosmetic('seiji','ambar-5');g.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));const hp=g.state.heroes[0].hp;g.enemyTurn();check(hp-g.state.heroes[0].hp===11,'amber reduces incoming hit by five');g.state.heroes[0].guard=true;g.state.battle.weakened=true;g.state.battle.damage=1;const small=g.state.heroes[0].hp;g.enemyTurn();check(small-g.state.heroes[0].hp===1,'incoming damage remains at least one');
g.state.mode='world';g.state.battle=null;g.equipCosmetic('seiji','memoria-5');g.state.heroes[0].mp=1;g.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));check(g.state.heroes[0].mp===11,'memory recovers MP at battle entry');g.state.mode='world';g.state.battle=null;g.equipCosmetic('ophelia','azul-5');check(g.state.heroes[1].maxMp===65,'blue changes maximum MP');
g.save();const restored=parseSave(store.get(SAVE_KEY));check(restored&&restored.progress.rolls===10&&restored.progress.cosmetics.includes('jade-4')&&restored.progress.cosmeticEquipment.ophelia==='azul-5','collection, results and equipment survive reload');const broken=structuredClone(restored);broken.progress.tokens=-1;check(!parseSave(JSON.stringify(broken)),'negative gacha balance rejected');const old=fresh();old.save();const v2=JSON.parse(store.get(SAVE_KEY));for(const key of ['anchors','events','tokens','dust','cosmetics','cosmeticEquipment','rolls','pity','lastDraw','lastDuplicate'])delete v2.progress[key];check(parseSave(JSON.stringify(v2)).progress.tokens===3,'old saves safely receive new defaults');
const t=fresh();check(ANCHORS.length===3,'only three rare travel points');check(!t.fastTravel('cais'),'cannot travel from anywhere');t.state.position={x:20,y:14};t.interact('cristal');check(t.state.progress.anchors.includes('academia')&&t.currentAnchor()?.id==='academia','using crystal activates real anchor');check(!t.fastTravel('cais'),'cannot travel to unseen point');t.travel('porto',{x:24,y:12});t.finishCutscene();t.interact('porto-cristal');check(t.state.progress.anchors.includes('cais'),'second point discovered by actual interaction');t.state.heroes[0].hp=40;check(t.fastTravel('academia')&&t.state.map==='patio'&&t.state.position.x===20&&t.state.heroes[0].hp===40,'travel reaches anchor without free healing');t.state.position={x:14,y:12};check(t.fastTravel('cais'),'activated destinations work from safe areas');t.travel('patio',{x:20,y:14});t.state.position={x:20,y:14};t.state.progress.anchors.push('profundo');check(!t.fastTravel('profundo'),'locked chapter cannot be bypassed');t.state.stage=5;check(t.fastTravel('profundo')&&t.state.map==='galeria','discovered late anchor works after chapter');t.save();check(parseSave(store.get(SAVE_KEY)).progress.anchors.length===3,'travel discoveries persist');t.state.mode='battle';check(!t.fastTravel('academia'),'fast travel unavailable during combat');
for(const event of EVENTS){const e=MAPS[event.map].entities.find(e=>e.id===event.entityId);check(e&&e.kind==='event','event is part of logical map');const spawn=Object.values(MAPS).flatMap(m=>m.entities).find(e=>e.to===event.map).spawn;check([{x:e.x,y:e.y+1},{x:e.x-1,y:e.y}].some(p=>findPath(MAPS[event.map],spawn,p).length),'event is reachable on foot');}
const ev=fresh();ev.state.map='domo';ev.state.position={x:18,y:5};check(!ev.resolveEvent('orvalho'),'event requires learned field technique');ev.learn('ophelia-vital');ev.learn('ophelia-field');ev.state.heroes[1].mp=0;check(!ev.resolveEvent('orvalho'),'event requires actual MP');ev.state.heroes[1].mp=10;check(ev.resolveEvent('orvalho')&&ev.state.heroes[1].mp===5,'ice event consumes five MP');check(ev.state.progress.events.includes('orvalho')&&ev.state.progress.tokens===6&&ev.state.credits===120,'event awards tokens and credits once');check(!ev.resolveEvent('orvalho')&&!ev.activeEntities().some(e=>e.eventId==='orvalho'),'completed event cannot be repeated');
ev.state.map='porto';ev.state.position={x:6,y:11};ev.state.progress.points.seiji=3;ev.learn('seiji-vital');ev.learn('seiji-field');ev.state.heroes[0].mp=10;check(ev.resolveEvent('carta')&&ev.state.heroes[0].mp===11,'ink event costs MP and level growth restores only newly gained MP');check(ev.state.progress.tokens===8&&ev.state.progress.events.includes('carta'),'second event reward');
ev.state.map='galeria';ev.state.position={x:15,y:16};check(ev.resolveEvent('fenda')&&ev.state.battle.name==='Sombra da Fenda'&&ev.state.battle.maxHp===200,'fenda starts real battle');const before=ev.state.progress.tokens;ev.action('flee');check(!ev.state.progress.events.includes('fenda')&&ev.state.progress.tokens===before,'flee grants no event reward');ev.now+=13;check(ev.resolveEvent('fenda'),'event becomes available after retreat');ev.state.battle.hp=0;ev.nextActor();ev.finishBattle();check(ev.state.progress.events.includes('fenda')&&ev.state.progress.tokens===before+4,'battle event only rewards victory');check(!ev.resolveEvent('fenda'),'battle event victory is unique');ev.save();check(parseSave(store.get(SAVE_KEY)).progress.events.length===3,'all events persist');
const farm=fresh();for(let i=0;i<3;i++){farm.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));farm.state.battle.hp=0;farm.nextActor();farm.finishBattle();}check(farm.state.progress.tokens===4,'three common victories produce a repeatable token');
console.log(`${checks} verificações de minimapas lógicos, viagem, eventos e cosméticos passaram.`);
