import {compileGameModules} from './game-module-loader.mjs';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';import{readFileSync,writeFileSync,mkdtempSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import ts from'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-origins-'));compileGameModules(out,['remakeArt','remakeArtSeijiOphelia','remakeArtGabrielMarinMax','remakeArtCarmillaBeatrizAbel','expansionV30','enemyArtV30','orfeuArtV30','gachaSequence','questsV31','questRuntimeV31','questArtV31','cosmetics','data','engine','progression','summons','carmilla']);
const{GameEngine,parseSave,isWalkable,findPath}=await import(pathToFileURL(join(out,'engine.js')).href),{ORIGINS,MAPS,HERO_IDS}=await import(pathToFileURL(join(out,'data.js')).href);let saved,n=0;global.localStorage={setItem:(_,v)=>saved=v,getItem:()=>saved};const check=(v,m)=>{assert.ok(v,m);n++};
const dialogue=g=>{let steps=0;while(g.state.mode==='dialogue'&&steps++<16){check(!g.state.dialogue.choice,'NPC recruitment does not bypass a player choice');g.nextDialogue();}check(g.state.mode==='world'&&steps<16,'NPC dialogue finishes before party actions');};
check(HERO_IDS.join(',')==='seiji,ophelia,marin,gabriel,max','five canonical base heroes are covered');
for(const id of HERO_IDS){const g=new GameEngine();g.selectProtagonist();check(g.state.mode==='selection','selection precedes start');g.start(false,id);check(g.state.heroes.length===1&&g.state.heroes[0].id===id,'chosen hero is sole active member');check(g.state.progress.recruited.join()===id,'other heroes remain locked');check(g.state.map===ORIGINS[id].map&&isWalkable(g.map,g.state.position.x,g.state.position.y),`origin ${id} uses actual walkable map`);check(g.state.cutscene.id===`origin-${id}`,'unique lore scene');g.finishCutscene();check(parseSave(saved)?.progress.protagonist===id&&parseSave(saved).heroes.length===1,'solo save round trip');check(!g.activeEntities().some(e=>e.id===id),'no duplicate protagonist NPC');check(!g.assignParty(1,HERO_IDS.find(other=>other!==id)),'unrecruited hero cannot be selected');
const exit={seiji:'beatriz',ophelia:'domo-retorno',marin:'porto-retorno',gabriel:'mata-retorno'}[id];const entity=g.map.entities.find(e=>e.id===exit)||g.map.entities.find(e=>e.kind==='warp');check(findPath(g.map,g.state.position,entity).length>0,'opening can reach city objective or exit');
if(id!=='ophelia'){g.talkToCompanion('ophelia');check(g.state.dialogue.lines[0].speaker==='Ophelia','encounter shows actual NPC');dialogue(g);check(!g.state.progress.recruited.includes('ophelia'),'Ophelia story gate');g.state.stage=1;g.talkToCompanion('ophelia');dialogue(g);check(g.state.progress.party.includes('ophelia')&&g.state.heroes.length===2,'first recruit joins automatically');}
if(id!=='seiji'){g.state.stage=1;g.talkToCompanion('seiji');dialogue(g);check(!g.state.progress.recruited.includes('seiji'),'Seiji requires reading record');g.state.stage=2;g.talkToCompanion('seiji');dialogue(g);check(g.state.progress.recruited.includes('seiji'),'Seiji recruited after record');}
for(const other of HERO_IDS.filter(h=>h!==id)){if(other==='gabriel')g.state.progress.encounters.push('ashwolf-1');g.state.stage=2;g.talkToCompanion(other);dialogue(g);if(other==='max'){check(!g.state.progress.recruited.includes('max'),'patrol registration alone does not recruit Max');check(g.challengeRecruit('max')&&g.state.battle.eventId==='recruit-max','Max recruitment uses its actual duel');g.state.battle.hp=0;g.nextActor();check(g.state.battle.result==='victory','recruit duel victory is resolved');g.finishBattle();}}check(g.state.progress.recruited.length===5&&g.state.heroes.length===5&&HERO_IDS.every(hero=>g.state.progress.party.includes(hero)),'all five base allies can fill the five active slots');g.save();check(parseSave(saved)?.progress.recruited.length===5&&parseSave(saved)?.heroes.length===5,'full recruitment and party persist');
check(g.claimStarterMail()&&g.selectStarterFiveStar('beatriz'),'a sixth ally can be obtained from the welcome selector');check(g.state.progress.recruited.includes('beatriz')&&g.state.heroes.length===5&&!g.state.progress.party.includes('beatriz'),'sixth recruit stays on the bench when the party is full');check(!g.assignParty(5,'beatriz'),'sixth active slot is rejected');check(g.assignParty(0,'beatriz')&&g.state.heroes.length===5&&g.state.heroes[0].id==='beatriz','a benched recruit replaces one of the five active slots');g.save();check(parseSave(saved)?.heroes.length===5&&parseSave(saved)?.progress.recruited.includes('beatriz'),'five-slot party and bench survive save migration');
const solo=new GameEngine();solo.start(false,id);solo.finishCutscene();solo.beginBattle(MAPS.subsolo.entities.find(e=>e.kind==='mob'));check(solo.state.battle.queue.includes(id)&&solo.state.battle.queue.length===2,'solo turn order contains hero and enemy');check(solo.narrativeLine({speaker:'Ophelia',text:'A porta se abriu.',right:'ophelia'}).speaker===(id==='ophelia'?'Ophelia':solo.state.heroes[0].name),'story does not speak through missing companion');}
const back=new GameEngine();back.selectProtagonist();check(back.returnToTitle()&&back.state.mode==='start','selection can be cancelled without replacing save');check(new Set(HERO_IDS.map(id=>ORIGINS[id].map)).size===4,'four distinct origins');const legacy=new GameEngine();legacy.start();legacy.finishCutscene();legacy.save();check(parseSave(saved).heroes.length===2&&!parseSave(saved).progress.protagonist,'legacy pair remains compatible');console.log(`${n} origin checks passed: five solo routes, lore, reachable exits, gated recruitment, party capacity, combat and saved identity.`);
