import assert from 'node:assert/strict';import{readFileSync,writeFileSync,mkdtempSync}from'node:fs';import{tmpdir}from'node:os';import{join}from'node:path';import ts from'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-origins-'));for(const name of ['cosmetics','data','engine','progression'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const{GameEngine,parseSave,isWalkable,findPath}=await import(`${out}/engine.js`),{ORIGINS,MAPS,HERO_IDS}=await import(`${out}/data.js`);let saved,n=0;global.localStorage={setItem:(_,v)=>saved=v,getItem:()=>saved};const check=(v,m)=>{assert.ok(v,m);n++};
for(const id of HERO_IDS){const g=new GameEngine();g.selectProtagonist();check(g.state.mode==='selection','selection precedes start');g.start(false,id);check(g.state.heroes.length===1&&g.state.heroes[0].id===id,'chosen hero is sole active member');check(g.state.progress.recruited.join()===id,'other heroes remain locked');check(g.state.map===ORIGINS[id].map&&isWalkable(g.map,g.state.position.x,g.state.position.y),`origin ${id} uses actual walkable map`);check(g.state.cutscene.id===`origin-${id}`,'unique lore scene');g.finishCutscene();check(parseSave(saved)?.progress.protagonist===id&&parseSave(saved).heroes.length===1,'solo save round trip');check(!g.activeEntities().some(e=>e.id===id),'no duplicate protagonist NPC');check(!g.assignParty(1,HERO_IDS.find(other=>other!==id)),'unrecruited hero cannot be selected');
const exit={seiji:'beatriz',ophelia:'domo-retorno',marin:'porto-retorno',gabriel:'mata-retorno'}[id];const entity=g.map.entities.find(e=>e.id===exit)||g.map.entities.find(e=>e.kind==='warp');check(findPath(g.map,g.state.position,entity).length>0,'opening can reach city objective or exit');
if(id!=='ophelia'){g.talkToCompanion('ophelia');check(g.state.dialogue.lines[0].speaker==='Ophelia','encounter shows actual NPC');g.nextDialogue();check(!g.state.progress.recruited.includes('ophelia'),'Ophelia story gate');g.state.stage=1;g.talkToCompanion('ophelia');g.nextDialogue();check(g.state.progress.party.includes('ophelia')&&g.state.heroes.length===2,'first recruit joins automatically');}
if(id!=='seiji'){g.state.stage=1;g.talkToCompanion('seiji');g.nextDialogue();check(!g.state.progress.recruited.includes('seiji'),'Seiji requires reading record');g.state.stage=2;g.talkToCompanion('seiji');g.nextDialogue();check(g.state.progress.recruited.includes('seiji'),'Seiji recruited after record');}
for(const other of HERO_IDS.filter(h=>h!==id)){if(other==='gabriel')g.state.progress.encounters.push('ashwolf-1');g.state.stage=2;g.talkToCompanion(other);g.nextDialogue();}check(g.state.progress.recruited.length===4&&g.state.heroes.length===2,'all allies can be recruited, active capacity remains two');g.save();check(parseSave(saved)?.progress.recruited.length===4,'recruitment persists');
const solo=new GameEngine();solo.start(false,id);solo.finishCutscene();solo.beginBattle(MAPS.subsolo.entities.find(e=>e.kind==='mob'));check(solo.state.battle.queue.includes(id)&&solo.state.battle.queue.length===2,'solo turn order contains hero and enemy');check(solo.narrativeLine({speaker:'Ophelia',text:'A porta se abriu.',right:'ophelia'}).speaker===(id==='ophelia'?'Ophelia':solo.state.heroes[0].name),'story does not speak through missing companion');}
const back=new GameEngine();back.selectProtagonist();check(back.returnToTitle()&&back.state.mode==='start','selection can be cancelled without replacing save');check(new Set(HERO_IDS.map(id=>ORIGINS[id].map)).size===4,'four distinct origins');const legacy=new GameEngine();legacy.start();legacy.finishCutscene();legacy.save();check(parseSave(saved).heroes.length===2&&!parseSave(saved).progress.protagonist,'legacy pair remains compatible');console.log(`${n} origin checks passed: four solo routes, lore, reachable exits, gated recruitment, party capacity, combat and saved identity.`);
