import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-progression-'));
for(const name of ['remakeArt','remakeArtSeijiOphelia','remakeArtGabrielMarinMax','remakeArtCarmillaBeatrizAbel','cosmetics','data','engine','progression','summons','carmilla'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave,SAVE_KEY,isWalkable}=await import(pathToFileURL(join(out,'engine.js')).href);
const {MAPS,newHeroes}=await import(pathToFileURL(join(out,'data.js')).href);
const {SLOTS,setCount,level}=await import(pathToFileURL(join(out,'progression.js')).href);
const stored=new Map();global.localStorage={setItem:(k,v)=>stored.set(k,v),getItem:k=>stored.get(k)||null};
let checks=0;const check=(ok,message)=>{assert.ok(ok,message);checks++;};
const timers=[];global.setTimeout=cb=>{timers.push(cb);return 1;};
const flush=()=>{let n=0;while(timers.length&&n++<100)timers.shift()();check(n<100,'animation callbacks settle');};
const fresh=()=>{const g=new GameEngine();g.start();g.finishCutscene();return g;};
const g=fresh();
check(g.state.progress.seen.includes('arrival'),'skipped scene is recorded');
check(g.playCutscene('arrival',undefined,true),'scene can be replayed at its location');g.finishCutscene();
check(g.state.progress.seen.filter(id=>id==='arrival').length===1,'replay does not duplicate record');
g.state.map='arquivo';check(!g.playCutscene('arrival',undefined,true),'replay cannot pretend to be a different location');g.state.map='patio';
check(g.buy('potion')&&g.state.credits===55&&g.state.potions===4,'purchase exchanges credits for item');
check(g.claimAchievement('shopper')&&g.state.credits===75,'achievement pays reward');
check(!g.claimAchievement('shopper')&&g.state.credits===75,'achievement cannot pay twice');
g.state.credits=0;check(!g.buy('ether')&&g.state.ethers===2,'insufficient funds preserve inventory');g.state.credits=80;
g.state.map='subsolo';check(!g.buy('potion'),'shop restricted to courtyard');g.state.map='patio';
check(!g.learn('seiji-bleed'),'tree prerequisite enforced');
check(g.learn('seiji-vital')&&g.state.heroes[0].maxHp===100,'passive node changes max HP');
check(!g.learn('seiji-vital')&&g.state.progress.points.seiji===1,'node cannot be purchased twice');
check(g.learn('seiji-field')&&g.state.progress.points.seiji===0,'tree spends the correct hero points');
check(g.useFieldSkill('ink-glyph')&&!g.state.progress.field.includes('ink-glyph'),'casting anywhere cannot complete distant discovery');g.state.heroes[0].mp=g.state.heroes[0].maxMp;delete g.state.progress.fieldUntil['ink-glyph'];
g.state.map='arquivo';g.state.position={x:11,y:10};
check(!g.activeEntities().some(e=>e.id==='glifo-bau'),'secret is hidden before Tinta');
const mp=g.state.heroes[0].mp;check(g.useFieldSkill('ink-glyph')&&g.state.heroes[0].mp===mp-4,'field skill consumes MP');
check(g.activeEntities().some(e=>e.id==='glifo-bau'),'Tinta reveals real interactable treasure');
check(g.useFieldSkill('ink-glyph')&&g.state.heroes[0].mp===mp-8,'temporary field skill can be recast with its cost');
check(g.claimQuest('glyph')&&g.state.progress.points.seiji===1,'quest awards skill points');check(!g.claimQuest('glyph'),'quest cannot be claimed twice');
g.state.map='patio';g.state.position={x:2,y:15};
check(g.learn('ophelia-vital')&&g.learn('ophelia-field'),'second independent field branch');
check(!isWalkable(g.map,2,16),'water collision before freezing');
check(g.useFieldSkill('ice-bridge')&&isWalkable(g.map,2,16),'freezing creates walkable terrain');
g.state.position={x:2,y:16};g.save();
const loaded=parseSave(stored.get(SAVE_KEY));check(loaded?.position.y===16&&loaded.progress.field.includes('ice-bridge'),'save resumes on frozen terrain');
check(g.claimAchievement('explorer'),'field challenges unlock achievement');
g.state.heroes[0].hp=10;const beforeHeal=g.state.heroes[0].hp;
check(g.useFieldSkill('mend')&&g.state.heroes[0].hp===beforeHeal+36,'Orvalho heals outside battle');
g.state.progress.kills.lobo=4;check(!g.claimBestiary('lobo',5),'milestone requires threshold');g.state.progress.kills.lobo=5;
check(g.claimBestiary('lobo',5)&&g.state.progress.owned.length===2,'five victories award two pieces');
check(!g.claimBestiary('lobo',5)&&g.state.progress.owned.length===2,'milestone cannot duplicate pieces');
g.state.progress.kills.lobo=25;check(g.claimBestiary('lobo',25)&&g.state.progress.owned.length===4,'25 victories award next pieces');
for(const slot of SLOTS.slice(0,3))check(g.equip('seiji',`wolf-${slot}`),'equip earned piece');
check(setCount(g.state.progress,'seiji','wolf')===3&&g.state.progress.metrics.set3,'three-piece effect activates');
check(!g.equip('seiji','veil-weapon'),'unowned item cannot equip');
g.state.progress.kills.lobo=50;check(g.claimBestiary('lobo',50),'50 milestone pays final pieces');
for(const slot of SLOTS)g.equip('seiji',`wolf-${slot}`);
check(setCount(g.state.progress,'seiji','wolf')===6&&g.state.progress.metrics.set6,'full set effect activates');
const maxHp=g.state.heroes[0].maxHp;g.equip('seiji','wolf-body');check(g.state.heroes[0].maxHp===maxHp,'reequipping cannot stack stats');
check(g.equip('ophelia','wolf-weapon')&&setCount(g.state.progress,'seiji','wolf')===5,'an item can belong to only one hero');g.equip('seiji','wolf-weapon');g.save();
const gearSave=parseSave(stored.get(SAVE_KEY));check(gearSave?.progress.equipment.seiji.weapon==='wolf-weapon'&&gearSave.heroes[0].maxHp===maxHp,'gear and derived stats survive save migration');
const old={...JSON.parse(stored.get(SAVE_KEY)),version:1,heroes:newHeroes()};delete old.progress;delete old.remedies;
check(parseSave(JSON.stringify(old))===null,'legacy save cannot resume on water without legacy bridge');old.position={x:14,y:12};old.checkpoint={map:'patio',position:old.position};
const migration=parseSave(JSON.stringify(old));check(migration?.version===2&&migration.progress.points.seiji===2&&migration.remedies===2,'v1 saves migrate without losing chapter state');
g.gainXp(60);check(level(g.state.progress)===2,'XP advances level');const points=g.state.progress.points.seiji;g.gainXp(20);check(g.state.progress.points.seiji===points,'points awarded once per new level');
const slow=fresh();slow.keys.add('ArrowDown');slow.update(.2);check(Math.abs(slow.state.position.y-12.76)<.001,'low-FPS frames preserve movement speed with collision substeps');slow.update(8);check(slow.state.position.y<14,'long background stall cannot teleport the party');
// Status rules, actual animation impacts and unique set effects.
const battle=fresh();battle.state.progress.points={seiji:20,ophelia:20};
for(const id of ['seiji-ink','seiji-blind','seiji-bleed','ophelia-ice','ophelia-freeze','ophelia-cleanse'])check(battle.learn(id),'unlock combat tree path');
battle.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));
check(battle.action('blind'),'unlocked offensive skill executes');flush();check(battle.hasStatus('enemy','blind'),'blindness is applied');
check(battle.action('freeze'),'freezing spell executes');flush();
check(battle.state.battle.log.some(t=>t.includes('perde a ação')),'freeze skips actual enemy action');
check(!battle.hasStatus('enemy','freeze'),'freeze expires after skipped action');
check(!battle.addStatus('enemy','freeze',1),'freeze cannot permanently lock same enemy');
check(battle.action('bleed'),'bleed spell executes');flush();battle.action('guard');flush();
check(battle.state.battle.log.some(t=>t.includes('sangramento')),'bleed damages on enemy action');
const immune=fresh();immune.state.progress.owned=SLOTS.map(slot=>`wolf-${slot}`);for(const slot of SLOTS)immune.equip('seiji',`wolf-${slot}`);immune.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));
check(!immune.addStatus('seiji','bleed',3),'wolf full set grants bleed immunity');immune.state.heroes[0].mp=0;const enemyHP=immune.state.battle.hp;immune.action('attack');timers.shift()();
check(immune.state.heroes[0].mp===3,'wolf three-piece effect recovers MP on hit');check(immune.state.battle.hp===enemyHP-38,'wolf six-piece effect increases physical damage');flush();
const veil=fresh();veil.state.progress.owned=SLOTS.map(slot=>`veil-${slot}`);for(const slot of SLOTS)veil.equip('seiji',`veil-${slot}`);veil.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));
check(veil.skillCost('seiji',6)===4,'veil three-piece effect reduces magic cost');check(!veil.addStatus('seiji','blind',2),'veil full set grants blind immunity');veil.action('cut');timers.shift()();check(veil.state.battle.hp===130-48,'veil full set increases magic damage');flush();
const blind=fresh();blind.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));blind.addStatus('seiji','blind',1);const random=Math.random;Math.random=()=>0;blind.action('cut');timers.shift()();check(blind.state.battle.hp===130,'blindness can cause offensive spell to miss');timers.shift()();Math.random=random;check(!blind.hasStatus('seiji','blind'),'blindness expires after actor action');
const clean=fresh();clean.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));clean.addStatus('seiji','silence',1);check(!clean.action('cut'),'silence prevents magic before consuming MP');clean.action('guard');flush();clean.addStatus('ophelia','blind',2);check(clean.action('remedy','ophelia'),'remedy can be used in battle');flush();check(!clean.hasStatus('ophelia','blind')&&clean.state.remedies===1,'remedy removes state and consumes one item');
const boss=fresh();boss.beginBattle(MAPS.camara.entities.find(e=>e.id==='selo'));boss.state.battle.round=2;boss.enemyTurn();
check(boss.state.heroes[0].hp===61&&boss.state.heroes[1].hp===46,'Colapso damages both party members');
check(boss.hasStatus('seiji','silence')&&boss.hasStatus('ophelia','silence'),'Colapso applies silence to unguarded allies');
boss.state.heroes[0].hp=85;boss.state.heroes[1].hp=70;boss.addStatus('enemy','silence',1);boss.enemyTurn();
check(boss.state.heroes[0].hp===85&&boss.state.heroes[1].hp===51,'silencing the boss prevents its area magic');
boss.state.heroes[0].hp=85;boss.state.heroes[1].hp=70;boss.state.heroes[0].guard=true;boss.state.battle.statuses={enemy:[],seiji:[],ophelia:[]};boss.enemyTurn();
check(boss.state.heroes[0].hp===74&&!boss.hasStatus('seiji','silence'),'guard reduces Colapso damage and blocks its state');
old.stage=5;old.credits=999;const completedLegacy=parseSave(JSON.stringify(old));check(completedLegacy?.stage===5&&completedLegacy.credits===999,'completed v1 chapter and currency migrate intact');
console.log(`${checks} progression checks passed: migration, shop, skill tree, field navigation, quests, achievements, milestones, gear, sets, statuses and cinematics.`);
