import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-v14-'));for(const name of ['cosmetics','data','engine','progression','summons','carmilla'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave}=await import(pathToFileURL(join(out,'engine.js')).href),{MAPS}=await import(pathToFileURL(join(out,'data.js')).href);let n=0;const check=(v,m)=>{assert.ok(v,m);n++;};let saved;global.localStorage={setItem:(k,v)=>saved=v,getItem:()=>saved};const timers=[];global.setTimeout=cb=>{timers.push(cb);return 1;};const flush=()=>{let count=0;while(timers.length&&count++<200)timers.shift()();check(count<200,'actions terminate');};
const dialogue=g=>{let steps=0;while(g.state.mode==='dialogue'&&steps++<16){check(!g.state.dialogue.choice,'recruitment dialogue does not skip a player choice');g.nextDialogue();}check(g.state.mode==='world'&&steps<16,'recruitment conversation completes before party actions');};
const g=new GameEngine();g.start();g.finishCutscene();g.state.stage=5;g.state.credits=3000;g.travel('ashwood',{x:12,y:10});g.finishCutscene();
check(!g.assignParty(0,'marin'),'unrecruited hero cannot join');g.talkToCompanion('marin');dialogue(g);check(g.state.progress.recruited.includes('marin'),'Marin recruitment is dialogue gated');
g.state.heroes[0].hp=20;check(g.state.progress.party.includes('marin'),'recruit joins an available active slot');check(g.removeFromParty('marin')&&!g.state.progress.party.includes('marin'),'recruit can be benched before replacing the leader');check(g.assignParty(0,'marin')&&g.state.heroes[0].id==='marin','new party member actually playable');check(!g.assignParty(1,'marin'),'no duplicate hero');check(g.assignParty(0,'seiji')&&g.state.heroes[0].hp===20,'bench vitals survive swap');
g.talkToCompanion('gabriel');dialogue(g);check(!g.state.progress.recruited.includes('gabriel'),'Gabriel requires actual encounter');g.state.progress.encounters.push('ashwolf-1');g.talkToCompanion('gabriel');dialogue(g);check(g.state.progress.recruited.includes('gabriel'),'Gabriel can join after protecting camp');
check(g.buy('shop-1-head')&&g.buy('shop-1-head'),'repeat equipment purchases succeed');check(g.state.progress.owned.includes('shop-1-head@2'),'copy has its own inventory identity');check(g.equip('seiji','shop-1-head')&&g.equip('ophelia','shop-1-head@2'),'two copies equip simultaneously');check(!g.buy('shop-8-head'),'still enforces level');const credits=g.state.credits;g.state.credits=0;check(!g.buy('shop-1-head'),'still enforces price');g.state.credits=credits;
g.buy('shop-1-staff');check(g.autoEquip('ophelia')&&g.state.progress.equipment.ophelia.weapon==='shop-1-staff','auto equip selects compatible weapon');check(g.state.progress.equipment.seiji.head==='shop-1-head','auto equip does not steal teammate gear');
g.state.progress.cosmetics=['jade-1','jade-5'];g.equipCosmetic('seiji','jade-5');check(g.autoEquipAura('ophelia')&&g.state.progress.cosmeticEquipment.ophelia==='jade-1','aura auto equip preserves teammate');
g.save();let parsed=parseSave(saved);check(parsed&&parsed.progress.recruited.length===4&&parsed.progress.owned.includes('shop-1-head@2'),'new roster and duplicate items survive saves');const old=JSON.parse(saved);old.heroes=old.heroes.filter(h=>['seiji','ophelia'].includes(h.id));delete old.progress.recruited;delete old.progress.party;delete old.progress.reserveVitals;delete old.progress.limit;delete old.progress.points.marin;delete old.progress.points.gabriel;delete old.progress.equipment.marin;delete old.progress.equipment.gabriel;parsed=parseSave(JSON.stringify(old));check(parsed&&parsed.heroes.length===2&&parsed.progress.party.join(',')==='seiji,ophelia'&&parsed.progress.limit.marin===0,'legacy saves migrate');
for(const id of ['seiji','ophelia','marin','gabriel']){const test=new GameEngine();test.start();test.finishCutscene();test.state.progress.recruited=['seiji','ophelia','marin','gabriel'];if(id!=='seiji'&&id!=='ophelia')test.assignParty(0,id);test.state.progress.limit[id]=100;test.beginBattle({...MAPS.ashwood.entities.find(e=>e.id==='ashwolf-1'),hp:1000});let b=test.state.battle;b.queue=[id,'enemy'];b.index=0;const hero=test.state.heroes.find(h=>h.id===id),mp=hero.mp,hp=b.hp;check(test.action('ultimate'),'ultimate accepts full meter');check(test.state.progress.limit[id]===0&&!test.action('ultimate'),'charge committed once and repeated clicks locked');flush();check(hero.mp===mp,'ultimate costs no MP');check(id==='ophelia'?test.state.heroes.some(h=>h.guard):b.hp<hp,'ultimate has actual combat impact');}
const charge=new GameEngine();charge.start();charge.finishCutscene();charge.beginBattle(MAPS.ashwood.entities.find(e=>e.id==='ashwolf-1'));check(!charge.action('ultimate'),'ultimate blocked before charge');charge.action('attack');flush();check(charge.state.progress.limit.seiji>=20,'attacks build meter');check(charge.assignParty(0,'marin')===false,'party swap blocked in battle');
console.log(`${n} v1.4 checks passed: recruitment, party, repeat purchases, auto equipment, aura, save migration and all ultimates.`);
