import {imageDimensions} from './image-dimensions.mjs';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-v17-'));for(const name of ['remakeArt','remakeArtSeijiOphelia','remakeArtGabrielMarinMax','remakeArtCarmillaBeatrizAbel','expansionV30','enemyArtV30','orfeuArtV30','gachaSequence','cosmetics','data','engine','progression','sprites','summons','carmilla'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave}=await import(pathToFileURL(join(out,'engine.js')).href),{MAPS,ASSETS}=await import(pathToFileURL(join(out,'data.js')).href),{SLOTS,GEAR,TREE}=await import(pathToFileURL(join(out,'progression.js')).href);let n=0;const check=(v,m)=>{assert.ok(v,m);n++;};let saved;global.localStorage={setItem:(k,v)=>saved=v,getItem:()=>saved};const timers=[];global.setTimeout=(cb,ms)=>{timers.push({cb,ms});return 1;};const flush=()=>{let cap=0;while(timers.length&&cap++<100)timers.shift().cb();assert.ok(cap<100);};const create=(id='seiji')=>{const g=new GameEngine();g.start(false,id);g.finishCutscene();return g;};const battle=g=>{g.beginBattle({...MAPS.ashwood.entities.find(e=>e.id==='ashwolf-1'),hp:2000});g.state.battle.queue=[g.state.heroes[0].id,'enemy'];g.state.battle.index=0;return g.state.battle;};const wear=(g,set,count)=>{for(const slot of SLOTS.slice(0,count)){g.state.progress.owned.push(`${set}-${slot}`);g.equip(g.state.heroes[0].id,`${set}-${slot}`);}};
for(const [id,set] of [['ashwolf','ember'],['moth','lunar']]){const g=create();check(!g.claimBestiary(id,5),'locked before goal');g.state.progress.kills[id]=50;for(const goal of [5,25,50]){check(g.claimBestiary(id,goal),'claim new monster goal');check(!g.claimBestiary(id,goal),'no repeat rewards');}check(SLOTS.every(slot=>g.state.progress.owned.includes(`${set}-${slot}`)),'full six-part set obtainable');wear(g,set,6);check(g.state.progress.metrics.set3&&g.state.progress.metrics.set6,'new sets count for achievements');g.save();check(parseSave(saved).progress.equipment.seiji.weapon===`${set}-weapon`,'new rewards persist compatible save');}
for(const id of ['selo','eco','cinder']){const g=create();check(!g.claimBestiary(id,1),'boss reward needs win');g.state.progress.kills[id]=1;const t=g.state.progress.tokens;check(g.claimBestiary(id,1)&&g.state.progress.tokens>t,'unique boss gives relic and tokens');check(!g.claimBestiary(id,1)&&!g.claimBestiary(id,5),'boss reward once with realistic goal');check(g.state.progress.owned.some(key=>GEAR[key]?.slot==='charm'),'boss relic equipable');}
{const g=create('gabriel');wear(g,'ember',3);battle(g);g.action('guard');timers.shift().cb();check(g.state.progress.limit.gabriel===20,'ember3 guard doubles base charge');flush();}
{const plain=create(),set=create();wear(set,'ember',6);const b=battle(plain),bs=battle(set);const hp=plain.state.heroes[0].hp,hps=set.state.heroes[0].hp;plain.enemyTurn();set.enemyTurn();check(hps-set.state.heroes[0].hp<hp-plain.state.heroes[0].hp,'ember6 reduces actual incoming damage');check(!set.addStatus('seiji','silence',1),'ember6 silence immunity');flush();}
{const g=create('marin');wear(g,'lunar',3);g.state.heroes[0].hp=20;battle(g);g.action('eclipse');timers.shift().cb();check(g.state.heroes[0].hp===24,'lunar3 offensive spell heals at impact');flush();}
{const a=create('marin'),b=create('marin');wear(b,'lunar',6);check(b.magicScale('marin')===1.2&&b.healPower('marin',24)>a.healPower('marin',24),'lunar6 damage and heal scaling');battle(b);check(!b.addStatus('marin','freeze',1),'lunar6 freeze immunity');flush();}
for(const id of ['marin','gabriel']){const g=create(id);g.state.progress.points[id]=30;const field=`${id}-field`;check(!g.learn(field),'field prereq enforced');check(g.learn(`${id}-vital`)&&g.learn(field),'field branch unlock');g.state.heroes[0].hp=20;const hp=g.state.heroes[0].hp,mp=g.state.heroes[0].mp;check(g.useFieldSkill(id==='marin'?'shadowrest':'rekindle',id)&&g.state.heroes[0].hp>hp&&g.state.heroes[0].mp<mp,'new field heal has actual HP/MP exchange');for(const node of TREE.filter(node=>node.hero===id&&!node.id.endsWith('vital')&&!node.id.endsWith('field')))if(!g.state.progress.learned.includes(node.id))check(g.learn(node.id),'combat path unlockable');check(g.skills(id).length===7,'six existing skills plus the new signature');g.state.heroes[0].mp=g.state.heroes[0].maxMp;const b=battle(g),action=id==='marin'?'nightseal':'ashseal',before=b.hp;check(g.action(action),'new offensive skill accepts');check(b.hp===before,'damage waits for animation impact');timers.shift().cb();check(b.hp<before&&b.statuses.enemy.some(s=>s.id==='silence'),'silence skill actually applies damage and silence');flush();}
for(const id of ['seiji','ophelia','marin','gabriel']){const g=create(id),b=battle(g);g.state.progress.limit[id]=100;check(g.action('ultimate'),'all four ultimates usable');check(b.animation.duration===4800&&b.animation.impactAt>700,'small intro exits well before impact');check(!g.action('ultimate')&&g.state.progress.limit[id]===0,'ultimate consumes meter once');flush();}
const {SPRITE_FRAMES}=await import(pathToFileURL(join(out,'sprites.js')).href);for(const id of ['seiji','ophelia','marin','gabriel']){const {width:w,height:h}=imageDimensions(`public${ASSETS[`battle_${id}_ultimate`]}`),frames=SPRITE_FRAMES[`battle_${id}_ultimate`];check(frames.length===8&&new Set(frames.map(f=>`${f.x},${f.y}`)).size===8,'eight distinct generated ultimate frames');check(frames.every(f=>f.x>=0&&f.y>=0&&f.x+f.w<=w&&f.y+f.h<=h&&f.anchorX>=f.x&&f.anchorX<f.x+f.w&&f.anchorY>=f.y&&f.anchorY<f.y+f.h),'all source frames and feet stay within image bounds');check(readFileSync(`public/assets/characters/${id}-ultimate-v17.webp`).length>1000,'runtime ultimate art exists');}
console.log(`${n} v1.7 checks passed: new bestiary sets, boss relics, real bonuses, skills, field recovery, saves and ultimate sequencing.`);
