import {imageDimensions} from './image-dimensions.mjs';
import {pathToFileURL} from 'node:url';
import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-v18-'));for(const name of ['cosmetics','data','engine','progression','summons','carmilla'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave,isWalkable}=await import(pathToFileURL(join(out,'engine.js')).href),{MAPS}=await import(pathToFileURL(join(out,'data.js')).href),{TREE,deriveHeroes,DIFFICULTIES}=await import(pathToFileURL(join(out,'progression.js')).href);let count=0;const check=(v,m)=>{assert.ok(v,m);count++;};let saved;global.localStorage={setItem:(k,v)=>saved=v,getItem:()=>saved};const timers=[];global.setTimeout=(cb,ms)=>{timers.push({cb,ms});return 1;};const flush=()=>{let n=0;while(timers.length&&n++<200)timers.shift().cb();check(n<200,'timers terminate');};const fresh=(hero='seiji')=>{const g=new GameEngine();g.start(false,hero);g.finishCutscene();g.state.progress.learned=TREE.map(n=>n.id);return g;};
{const g=fresh();g.state.progress.recruited=['seiji','ophelia'];g.state.progress.party=['seiji','ophelia'];g.state.heroes=deriveHeroes(g.state.progress);check(g.fieldSlots()[0].id==='ink-glyph','Seiji quick slot');check(g.quickField(0)&&g.fieldActive('ink-glyph'),'Q actually spends MP and activates');check(g.swapLeader()&&g.state.heroes[0].id==='ophelia'&&g.fieldSlots()[0].id==='ice-bridge','Tab exchanges leader and techniques');check(parseSave(saved).heroes[0].id==='ophelia','leader swap survives reload');g.paused=true;check(!g.swapLeader()&&!g.quickField(0),'keyboard shortcuts do not act under menus');}
for(const [hero,skill] of [['seiji','ink-glyph'],['ophelia','ice-bridge'],['marin','shadow-step'],['gabriel','ember-light']]){const g=fresh(hero);check(g.quickField(0)&&g.fieldActive(skill),`${hero} real field technique`);const points=Object.values(MAPS).flatMap(m=>m.entities.filter(e=>e.fieldSkill===skill).map(e=>({m,e})));check(points.length>=2,`${hero} multiple field points`);g.state.map=points[0].m.id;check(g.activeEntities().some(e=>e.fieldRequired===skill),'temporary ability reveals chest');g.state.progress.fieldUntil[skill]=Date.now()-1;g.update(.01);check(!g.fieldActive(skill)&&!g.activeEntities().some(e=>e.fieldRequired===skill),'effect and interaction expire');check(g.quickField(0),'recasting remains possible');}
{const g=fresh('ophelia');g.state.map='patio';g.state.position={x:2,y:15};g.quickField(0);g.state.position={x:2,y:16};check(isWalkable(g.map,2,16),'active bridge is walkable');g.save();check(parseSave(saved),'active bridge saved');g.state.progress.fieldUntil['ice-bridge']=Date.now()-1;g.update(.01);check(isWalkable(g.map,g.state.position.x,g.state.position.y),'expiry safely moves player off water');const old=JSON.parse(saved);old.progress.fieldUntil['ice-bridge']=Date.now()-1;old.progress.field.push('ice-bridge');check(parseSave(JSON.stringify(old))?.position.y===15,'expired saved bridge returns to shore');}
for(const draws of [1,5,10]){const g=fresh();g.state.progress.tokens=draws-1;check(!g.drawCosmetics(draws)&&g.state.progress.rolls===0,'insufficient batch has no partial consumption');g.state.progress.tokens=draws;check(g.drawCosmetics(draws,()=>.01)&&g.state.progress.tokens===0&&g.state.progress.rolls===draws&&g.state.gachaResults.length===draws,'atomic batch count and tokens');check(!g.drawCosmetics(1),'busy batch cannot double draw');flush();check(!g.state.gachaBusy&&g.state.rewardNotice.tab==='gacha','batch ends with quick-access notification');if(draws===10)check(g.state.progress.cosmetics.some(id=>id.endsWith('-4')),'pity applies within multi-pull');}
{const g=fresh();g.state.progress.anchors=['academia','cais','profundo'];check(g.fastTravel('cais'),'safe-area travel fixed');g.finishCutscene();g.travel('subsolo',{x:3,y:3});check(!g.fastTravel('academia'),'dangerous travel still needs anchor');g.state.stage=5;g.travel('galeria',{x:12,y:12});check(g.fastTravel('academia'),'rare activated hostile anchor travels');}
{const g=fresh();g.state.credits=10000;check(g.buy('shop-weapon-1')||g.state.progress.owned.length===0,'invalid shop IDs safe');const {SHOP}=await import(pathToFileURL(join(out,'progression.js')).href),item=SHOP.find(i=>i.gear&&i.minLevel===1);check(g.buy(item.id)&&g.buy(item.id),'gear purchases repeat');check(g.state.progress.unseenGear.length===2&&g.state.rewardNotice.focus,'gear notification points to received copy');g.ackGear('weapon');check(g.state.progress.unseenGear.every(id=>!id.includes('weapon')),'only viewed slot acknowledged');}
for(const d of DIFFICULTIES){const g=fresh('gabriel');g.state.progress.difficulty=d.id;g.beginBattle(MAPS.ashpyre.entities.find(e=>e.id==='cinder'));const b=g.state.battle;check(b.maxHp===Math.round(520*d.hp)&&b.credits===Math.round(350*d.reward),'difficulty changes actual boss stats and rewards');b.hp=b.maxHp*.65;g.updateBossPhase();check(b.phase===2&&b.damage>b.baseDamage,'second boss phase changes combat');b.hp=b.maxHp*.3;g.updateBossPhase();check(b.phase===3&&b.bossCharge===50,'third phase advances and charges ultimate');timers.length=0;b.busy=false;b.animation=undefined;b.queue=['enemy','gabriel'];b.index=0;b.bossCharge=100;const hp=g.state.heroes[0].hp;g.nextActor();check(b.animation.action==='boss-ultimate'&&b.animation.impactAt>700&&g.state.heroes[0].hp===hp,'boss ultimate waits for animation before hit');timers.shift().cb();check(g.state.heroes[0].hp<hp,'boss ultimate has real damage');flush();}
for(const d of DIFFICULTIES){const g=fresh();g.state.progress.difficulty=d.id;g.beginBattle(MAPS.ashpyre.entities.find(e=>e.id==='cinder'));g.state.battle.result='victory';g.finishBattle();check(g.state.progress.owned.length===d.id,'boss loot quantity actually increases with difficulty');check(g.state.rewardNotice.tab==='gear'&&g.state.rewardNotice.focus,'boss loot notice opens received gear');flush();}
{const g=fresh('marin');g.travel('ashwood',{x:12,y:3});g.finishCutscene();const e=g.activeEntities().find(e=>e.kind==='mob');g.state.position={x:e.x,y:e.y};check(g.quickField(0),'Marin casts avoidance technique');g.update(.01);check(g.state.mode==='world','shadow prevents automatic contact battles');g.state.progress.fieldUntil['shadow-step']=Date.now()-1;g.update(.01);check(g.state.mode==='battle','contact battles return after expiration');flush();}
{const sounds=[];global.Audio=class {constructor(src){sounds.push(src);}play(){return Promise.resolve();}};const g=fresh();g.sound=true;g.beginBattle(MAPS.subsolo.entities.find(e=>e.id==='lobo'));g.action('cut');check(sounds.includes('/assets/audio/sfx/cast.wav'),'casting routes to generated sound');timers.shift().cb();check(sounds.includes('/assets/audio/sfx/hit.wav'),'damage impact routes to hit sound');g.sound=false;const n=sounds.length;g.soundEffect('hit');check(sounds.length===n,'mute also stops effects');flush();delete global.Audio;}
for(const name of ['hit','swing','cast','heal','gacha','phase','ultimate-seiji','ultimate-ophelia','ultimate-marin','ultimate-gabriel','ultimate-boss']){const wav=readFileSync(`public/assets/audio/sfx/${name}.wav`);check(wav.toString('ascii',0,4)==='RIFF'&&wav.length>4000,'valid playable original WAV');}
for(const [name,cells] of [['gacha-50-icons',50],['combat-vfx',24],['boss-phases',6],['gacha-crystal-animation',8]]){const source=imageDimensions(`public/assets/v18/${name}.webp`);check(source.width===1536&&source.height===1024,'whole generated runtime sheet retained');check(readFileSync(`public/assets/v18/${name}.webp`).length>1000,`${cells} generated runtime cells available`);}
console.log(`${count} v1.8 checks passed: leader, quick slots, timed exploration, safe expiry, batch gacha, contextual rewards, fast travel, boss phases and generated assets/sounds.`);
