import assert from 'node:assert/strict';import {readFileSync,writeFileSync,mkdtempSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import ts from 'typescript';
const out=mkdtempSync(join(tmpdir(),'eter-v19-'));for(const name of ['cosmetics','data','engine','progression','sprites'])writeFileSync(`${out}/${name}.js`,ts.transpileModule(readFileSync(`lib/game/${name}.ts`,'utf8').replace(/from '\.\/(\w+)'/g,"from './$1.js'"),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText);
const {GameEngine,parseSave}=await import(`${out}/engine.js`),{MAPS,SKILL_VISUALS,ENEMY_ULTIMATES,COMPANIONS,ASSETS}=await import(`${out}/data.js`),{SPRITE_FRAMES}=await import(`${out}/sprites.js`);let count=0;const check=(v,m)=>{assert.ok(v,m);count++;};let saved;global.localStorage={setItem:(k,v)=>saved=v,getItem:()=>null};const timers=[];global.setTimeout=(cb,ms)=>{timers.push({cb,ms});return 1;};const fresh=()=>{const g=new GameEngine();g.start(false);g.finishCutscene();return g;};
for(const family of Object.keys(ENEMY_ULTIMATES)){const g=fresh(),e=Object.values(MAPS).flatMap(m=>m.entities).find(e=>e.family===family||e.id===family);check(!!e,`encounter exists ${family}`);g.beginBattle(e);const b=g.state.battle;timers.length=0;b.busy=false;b.animation=undefined;b.queue=['enemy','seiji','ophelia'];b.index=0;b.bossCharge=100;b.statuses.enemy=[];g.state.heroes.forEach(h=>h.hp=h.maxHp=1000);const hp=g.state.heroes.map(h=>h.hp);g.nextActor();check(b.animation.action===`${b.boss?'boss':'enemy'}-ultimate`,`${family} uses ultimate`);check(b.animation.duration===4800&&b.animation.impactAt>3000,'cinematic finishes opening before hit');check(b.bossCharge===0&&g.state.heroes.every((h,i)=>h.hp===hp[i]),'charge consumed once and damage delayed');check(!g.action('attack'),'commands blocked during cinematic');timers.shift().cb();check(g.state.heroes[0].hp<hp[0],'real ultimate damage');check((g.state.heroes[1].hp<hp[1])===ENEMY_ULTIMATES[family].area,'correct single or party target');check(b.statuses.seiji.some(s=>s.id===ENEMY_ULTIMATES[family].status),'distinct contact status');}
{const g=fresh();check(!g.setGabrielForm('lycan'),'unrecruited form unavailable');g.state.progress.recruited.push('gabriel');check(g.setGabrielForm('lycan'),'form selected');check(parseSave(saved).progress.gabrielForm==='lycan','form persists');const old=JSON.parse(saved);delete old.progress.gabrielForm;check(parseSave(JSON.stringify(old)).progress.gabrielForm==='human','old saves migrate');g.state.mode='battle';check(!g.setGabrielForm('human'),'form locked in combat');}
check(Object.keys(SKILL_VISUALS).length===20,'every hero spell gets unique animation');check(new Set(Object.values(SKILL_VISUALS).map(v=>`${v.hero}:${v.row}`)).size===20,'all skill sequences distinct');for(const [id,v] of Object.entries(SKILL_VISUALS)){check(v.row<v.rows,'valid skill row');check(readFileSync(`public${ASSETS[`battle_fx_${v.hero}`]}`).length>1000,`generated art available ${id}`);}
for(const hero of Object.keys(COMPANIONS))check(COMPANIONS[hero].name,'named bound companion');for(const key of ['gabriel','gabriel_lycan','exits','companions','battle_gabriel_lycan_attack','battle_gabriel_lycan_cast','battle_gabriel_lycan_ultimate'])for(const c of SPRITE_FRAMES[key]){check(c.x>=0&&c.y>=0&&c.x+c.w<=1536&&c.y+c.h<=1024,'whole source frame in bounds');check(c.anchorX>=c.x&&c.anchorX<=c.x+c.w&&c.anchorY>=c.y&&c.anchorY<=c.y+c.h,'ground anchor in bounds');}
check(SPRITE_FRAMES.gabriel.length===12&&SPRITE_FRAMES.gabriel_lycan.length===12,'all directions have three poses');check(SPRITE_FRAMES.battle_gabriel_lycan_ultimate.length===8,'lycan has cinematic sequence');
console.log(`${count} v1.9 checks passed: every enemy ultimate, delayed impact, controls locked, status identity, persisted lycan, unique spell sheets and complete frame anchors.`);
