'use client';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Maximize, Minimize, Menu, Mail, BookOpen, Backpack, Volume2, VolumeX, Moon, MapPin, Shield, Sword, Sparkles, Heart, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, Move, Keyboard, CircleHelp, Save, RotateCcw, Check, Gem } from 'lucide-react';
import { DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { ASSETS, COMPANIONS, ORIGINS, heroBases, MAPS, OBJECTIVES, SKILLS, type HeroId } from '@/lib/game/data';
import { GameEngine, type Snapshot } from '@/lib/game/engine';
import { WorldRenderer } from '@/lib/game/renderer';
import {GameMenu,StatusBadges} from '@/components/game-menu';
import {BattleCommands} from '@/components/battle-commands';
import {QUESTS,ACHIEVEMENTS,BESTIARY,level} from '@/lib/game/progression';
import {Cutscene} from '@/components/cutscene';
import {UltimateCinematic} from '@/components/ultimate-cinematic';
import {BattleScene,preloadBattleArt} from '@/components/battle-scene';
import {GameDialog} from '@/components/game-dialog';
import {MiniMap} from '@/components/minimap';
import {GameIcon} from '@/components/game-icon';
import {TitleAtmosphere} from '@/components/title-atmosphere';
import {LoadingScreen} from '@/components/loading-screen';
import {Slider} from '@/components/ui/slider';
import {MusicDirector,musicFor,MUSIC,type MusicStatus} from '@/lib/game/music';
import {advanceMasterSequence,emptyMasterSequence} from '@/lib/game/master-mode';

function Face({id}:{id:string}){return <span className={`face face-${id}`}><img src={ASSETS[`dlg_${id}`]} alt="" /></span>;}
function HeroCard({h,active=false,lycan=false}:{h:Snapshot['heroes'][number];active?:boolean;lycan?:boolean}){return <div className={`hero-card element-${h.id} ${active?'hero-active':''}`}>
 <Face id={h.id==='gabriel'&&lycan?'gabriel_lycan':h.id}/><div className="hero-info"><div className="hero-name"><strong>{h.name}</strong><span>{h.element} · {COMPANIONS[h.id].name}</span></div><div className="stat-row"><span>HP</span><Progress className="hp-bar" value={h.hp/h.maxHp*100}/><b>{h.hp}<small>/{h.maxHp}</small></b></div><div className="stat-row"><span>MP</span><Progress className="mp-bar" value={h.mp/h.maxMp*100}/><b>{h.mp}<small>/{h.maxMp}</small></b></div></div>
 </div>;}
function Journal({s,engine,onGo}:{s:Snapshot;engine:GameEngine;onGo?:(id:string)=>void}){const objective=OBJECTIVES[s.stage];return <>
 <div className="eyebrow"><span className="gold">◆</span> MISSÃO ATUAL</div><h2>{objective.title}</h2><p>{objective.text}</p><div className="destination"><MapPin size={14}/>{objective.location}</div>
 <div className="chapter-progress"><span>O que o selo lembra</span><b>{Math.min(s.stage,5)}/5</b></div><Progress className="quest-bar" value={s.stage/5*100}/>
 <div className="map-title"><span>ARREDORES</span><span>{MAPS[s.map].safe?'Área segura':'Área hostil'}</span></div><MiniMap s={s} engine={engine}/><div className="map-legend"><span>● Você</span><span className="gold">◆ Objetivo</span><span className="cyan">● Cristal</span></div>
 <div className="nearby-list"><span className="eyebrow">PONTOS DE INTERESSE</span>{engine.activeEntities().filter(e=>e.kind!=='mob'&&!(e.id==='selo'&&s.stage>=4)&&!(e.id==='eco'&&s.progress.kills.eco>0)).map(e=><button key={e.id} onClick={()=>onGo?onGo(e.id):engine.approach(e.id)} disabled={s.mode!=='world'}><span className={OBJECTIVES[s.stage].target===e.id?'gold':''}>{e.kind==='save'?'◇':e.kind==='warp'?'↳':'◆'}</span>{e.label}</button>)}</div>
 </>;}

export default function Home(){const [engine]=useState(()=>new GameEngine());const s=useSyncExternalStore(engine.subscribe,engine.snapshot,engine.snapshot);const canvas=useRef<HTMLCanvasElement>(null),renderer=useRef<WorldRenderer|null>(null);const [loaded,setLoaded]=useState(false),[panel,setPanel]=useState<'journal'|'bag'|'help'|'menu'|null>(null),[sound,setSound]=useState(false),[confirmReset,setConfirmReset]=useState(false),[target,setTarget]=useState<HeroId>('seiji'),[menuTab,setMenuTab]=useState('party'),[menuFocus,setMenuFocus]=useState<string|undefined>(),[viewport,setViewport]=useState<HTMLElement|null>(null),[chosen,setChosen]=useState<HeroId>('seiji'),[titleArmed,setTitleArmed]=useState(false),[volume,setVolume]=useState(.6),[musicStatus,setMusicStatus]=useState<MusicStatus>('off'),[fullScreen,setFullScreen]=useState(false);
 const shell=useRef<HTMLElement>(null),channel0=useRef<HTMLAudioElement>(null),channel1=useRef<HTMLAudioElement>(null),music=useRef<MusicDirector|null>(null),panelRef=useRef(panel),armedRef=useRef(titleArmed),loadedRef=useRef(loaded);panelRef.current=panel;armedRef.current=titleArmed;loadedRef.current=loaded;
 const openMenu=(tab='party',focus?:string)=>{if(engine.state.mode!=='world')return;engine.clearMovement();engine.paused=true;setMenuTab(tab);setMenuFocus(focus);setPanel('menu');};
 const toggleFullscreen=async()=>{const game=shell.current;if(!game)return;engine.clearMovement();engine.toast('');type WebkitElement=HTMLElement&{webkitRequestFullscreen?:()=>Promise<void>|void};type WebkitDocument=Document&{webkitFullscreenElement?:Element;webkitExitFullscreen?:()=>Promise<void>|void};const doc=document as WebkitDocument;try{if(document.fullscreenElement||doc.webkitFullscreenElement){if(document.exitFullscreen)await document.exitFullscreen();else await doc.webkitExitFullscreen?.();return;}if(game.requestFullscreen)await game.requestFullscreen();else if((game as WebkitElement).webkitRequestFullscreen)await (game as WebkitElement).webkitRequestFullscreen!();else throw new Error('unsupported');const orientation=screen.orientation as ScreenOrientation&{lock?:(mode:string)=>Promise<void>};if(window.matchMedia('(pointer:coarse)').matches)try{await orientation?.lock?.('landscape');}catch{/* Rotation remains a device choice when unsupported. */}}catch{engine.toast('Tela cheia indisponível aqui. Abra o jogo no Chrome ou Safari e vire o celular na horizontal.');}};
 useEffect(()=>{const sync=()=>setFullScreen(!!(document.fullscreenElement||(document as Document&{webkitFullscreenElement?:Element}).webkitFullscreenElement));document.addEventListener('fullscreenchange',sync);document.addEventListener('webkitfullscreenchange',sync);return()=>{document.removeEventListener('fullscreenchange',sync);document.removeEventListener('webkitfullscreenchange',sync);};},[]);
 const activateTitle=()=>{setTitleArmed(true);armedRef.current=true;setSound(true);engine.sound=true;void music.current?.unlock();};
 const toggleMusic=()=>{const next=!music.current?.enabled;setSound(next);engine.sound=next;void music.current?.setEnabled(next);};
 useEffect(()=>{const director=new MusicDirector([channel0.current!,channel1.current!],setMusicStatus);music.current=director;try{const saved=Number(localStorage.getItem('eter-anima-music-volume'));if(localStorage.getItem('eter-anima-music-volume')!==null&&Number.isFinite(saved)){director.setVolume(saved);setVolume(director.volume);}}catch{}setSound(true);engine.sound=true;void director.unlock();const retry=()=>{if(director.enabled)void director.unlock();};window.addEventListener('pointerdown',retry,{once:true});window.addEventListener('keydown',retry,{once:true});return()=>{window.removeEventListener('pointerdown',retry);window.removeEventListener('keydown',retry);director.dispose();music.current=null;};},[engine]);
 useEffect(()=>{if(!s.heroes.some(h=>h.id===target))setTarget(s.heroes[0].id);},[s.heroes.map(h=>h.id).join(','),target]);
 useEffect(()=>{music.current?.request(musicFor(s));},[s.mode,s.map,s.battle?.boss,s.cutscene?.id]);
 useEffect(()=>{engine.hydrate();void preloadBattleArt();const r=new WorldRenderer(canvas.current!,engine);renderer.current=r;void r.load().then(()=>setLoaded(true));let masterSequence=emptyMasterSequence();
  const down=(e:KeyboardEvent)=>{const target=e.target; if(target instanceof Element&&target.closest('input,select,textarea,[role=slider]'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;
   if(key==='Escape'){if(engine.state.mode==='selection')engine.returnToTitle();if(panelRef.current){e.preventDefault();setPanel(null);}engine.clearMovement();return;}
   if(panelRef.current)return;
   const interactive=target instanceof Element&&!!target.closest('button,[role=tab]');if(interactive&&(key==='Enter'||key===' '))return;
   if(engine.state.mode==='world'&&!engine.paused&&!e.repeat&&!engine.state.progress.masterMode){const result=advanceMasterSequence(masterSequence,key,Date.now());masterSequence=result.state;if(result.activated){e.preventDefault();engine.clearMovement();engine.activateMasterMode();return;}if(result.consumeMovement){e.preventDefault();return;}}
   if(engine.state.mode==='selection'){if(key==='Enter'&&!e.repeat){e.preventDefault();document.querySelector<HTMLButtonElement>('[data-origin-start]')?.click();}if(key==='Escape'){engine.returnToTitle();}return;}
   if(engine.state.mode==='start'){if(key==='Enter'&&!e.repeat&&loadedRef.current){e.preventDefault();if(!armedRef.current)activateTitle();else if(engine.state.hasSave)engine.start(true);else engine.selectProtagonist();}return;}
   if(engine.state.mode==='world'&&!engine.paused&&!e.repeat&&['q','r','Tab','g','i','k','m','l','v','o','p',' '].includes(key)){e.preventDefault();if(key==='Tab')engine.swapLeader();else if(key==='q'||key==='r')engine.quickField(key==='q'?0:1);else if(key==='g')openMenu('party');else if(key==='i')openMenu('bag');else if(key==='k')openMenu('skills');else if(key==='m')openMenu('map');else if(key==='l')openMenu('quests');else if(key==='v')openMenu('achievements');else if(key==='o')openMenu('gacha');else if(key==='p')toggleMusic();else engine.blink();return;}
   if(key==='Enter'&&engine.state.mode==='world'&&!e.repeat){e.preventDefault();openMenu();return;}
   if(!engine.paused&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(key))e.preventDefault();
   if(engine.state.mode==='world'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','Shift'].includes(key))engine.keys.add(key);
   if(!e.repeat&&(key==='e'||key==='Enter'||key===' ')){if(engine.state.mode==='cutscene')engine.nextCutscene();else if(engine.state.mode==='dialogue')engine.nextDialogue();else if(key!=='Enter')engine.interact();}
  };
  const up=(e:KeyboardEvent)=>engine.keys.delete(e.key.length===1?e.key.toLowerCase():e.key);const blur=()=>engine.clearMovement();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);
  return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);r.destroy();engine.dispose();};
 },[engine]);
 useEffect(()=>{if(s.overlay){setMenuTab(s.overlay);setPanel('menu');engine.state.overlay=null;}},[s.overlay,engine]);
 useEffect(()=>{engine.paused=!!panel||confirmReset;if(panel||confirmReset)engine.clearMovement();},[panel,confirmReset,engine]);
 useEffect(()=>{const d=document as Document & {modelContext?:{registerTool:(t:unknown,o?:unknown)=>unknown}};if(!d.modelContext?.registerTool)return;const life=new AbortController();const reg=(tool:unknown)=>{try{void Promise.resolve(d.modelContext!.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  reg({name:'read_eter_game_state',description:'Read current location, mission, party and nearby interactions in Éter Anima.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({map:engine.state.map,stage:engine.state.stage,mode:engine.state.mode,position:engine.state.position,objective:OBJECTIVES[engine.state.stage].text,heroes:engine.state.heroes,nearby:engine.nearest()?.id})});
  reg({name:'walk_to_eter_interaction',description:'Start walking through the real map toward a named point of interest, then interact when nearby. Does not teleport or bypass mission conditions.',inputSchema:{type:'object',properties:{entityId:{type:'string'}},required:['entityId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{entityId:string})=>{if(!input||typeof input.entityId!=='string'||!engine.activeEntities().some(e=>e.id===input.entityId))throw new Error('Unknown interaction');return {walking:engine.approach(input.entityId)};}});
  return()=>life.abort();
 },[engine]);
 const rewards=QUESTS.filter(q=>q.value(s)>=q.goal&&!s.progress.questClaims.includes(q.id)&&(!q.request||s.progress.requests.includes(q.request))).length+ACHIEVEMENTS.filter(a=>a.test(s)&&!s.progress.achievementClaims.includes(a.id)).length+BESTIARY.reduce((n,m)=>n+(m.set?[5,25,50]:[1]).filter(goal=>(s.progress.kills[m.id]||0)>=goal&&!s.progress.bestiaryClaims.includes(`${m.id}-${goal}`)).length,0);
 const d=s.dialogue,line=d?.lines[d.index],left=s.progress.protagonist||'seiji',leftName=heroBases().find(h=>h.id===left)!.name,right=line?.right||s.heroes.find(h=>h.id!==left)?.id,b=s.battle,hero=engine.currentHero();const hold=(key:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);engine.keys.add(key);},onPointerUp:()=>engine.keys.delete(key),onPointerCancel:()=>engine.keys.delete(key),onLostPointerCapture:()=>engine.keys.delete(key)});
 const currentTrack=musicFor(s);
 const settings=<div className="settings-content"><h3>Trilhas e som</h3><p>{MUSIC[currentTrack].name}</p><button className="secondary-button" onClick={()=>{const on=!sound;setSound(on);engine.sound=on;void music.current?.setEnabled(on);}}>{sound?'Desativar som':'Ativar som'}</button><label>Volume · {Math.round(volume*100)}%</label><Slider aria-label="Volume das trilhas" min={0} max={100} step={5} value={[Math.round(volume*100)]} onValueChange={values=>{const value=values[0]/100;setVolume(value);music.current?.setVolume(value);try{localStorage.setItem('eter-anima-music-volume',String(value));}catch{}}}/><div className="menu-system-actions"><button className="secondary-button" onClick={()=>{engine.save();setPanel(null);}}>Salvar e voltar</button><button className="secondary-button" onClick={()=>{setPanel(null);engine.returnToTitle();}}>Salvar e ir à abertura</button><button className="text-button" onClick={()=>{engine.save();setPanel(null);engine.selectProtagonist();}}>Recomeçar aventura</button></div><div className="help-content"><p><strong>PC</strong> · WASD/setas para caminhar. E para interagir. Q/R usam os dois slots de exploração. Tab troca o líder. Enter abre o menu; em diálogos e cenas, avança. Esc fecha o menu.</p><p><strong>Mobile</strong> · Jogue na horizontal. O ícone ⛶ ativa a tela cheia quando o navegador permite. Toque no cenário, use o direcional ou os ícones no topo. Todo o menu fica dentro da tela do jogo.</p><p>O progresso é salvo neste navegador. Cristais restauram HP/MP. Guarda reduz dano e bloqueia estados inimigos.</p></div></div>;
 return <main className="game-shell" ref={shell} tabIndex={-1} data-game-mode={s.mode} data-fullscreen={fullScreen} data-music-track={currentTrack} data-music-status={musicStatus}>
  <audio ref={channel0} autoPlay loop preload="none"/><audio ref={channel1} loop preload="none"/>
  {!loaded&&<LoadingScreen/>}
  <header className="game-header"><div className="brand"><Gem size={27}/><span>ÉTER <em>ANIMA</em></span><small>STONE REACH</small></div><div className="chapter-label"><Moon size={15}/><span>O que o selo lembra</span><i>01</i></div><nav aria-label="Menu do jogo"><button className="icon-button" title="Diário de missão" aria-label="Abrir diário" onClick={()=>openMenu('quests')} disabled={s.mode!=='world'}><BookOpen size={20}/></button><button className="icon-button" title="MAIL · presente inicial" aria-label="Abrir MAIL" onClick={()=>openMenu('mail')} disabled={s.mode!=='world'}><Mail size={20}/>{(!s.progress.starterMailClaimed||s.progress.starterSelectorPending)&&<span className="menu-reward-count">1</span>}</button><button className="icon-button" title="Menu de aventura" aria-label="Abrir menu" onClick={()=>openMenu(rewards?'rewards':'party')} disabled={s.mode!=='world'}><Menu size={20}/>{rewards>0&&<span className="menu-reward-count" aria-label={`${rewards} recompensas disponíveis`}>{rewards}</span>}</button><button className="icon-button quick-menu" title="Habilidades" aria-label="Abrir habilidades" onClick={()=>openMenu('skills')} disabled={s.mode!=='world'}><Sparkles size={20}/></button><button className="icon-button quick-menu" title={s.progress.unseenGear.length?`${s.progress.unseenGear.length} equipamentos novos · abrir o slot recebido`:'Equipamentos'} aria-label={s.progress.unseenGear.length?`Ver ${s.progress.unseenGear.length} equipamentos novos`:'Abrir equipamentos'} onClick={()=>openMenu('gear',s.progress.unseenGear[0])} disabled={s.mode!=='world'}><Shield size={20}/>{s.progress.unseenGear.length>0&&<span className="menu-reward-count">{s.progress.unseenGear.length}</span>}</button><button className="icon-button quick-menu" title="Bolsa" aria-label="Abrir bolsa" onClick={()=>openMenu('bag')} disabled={s.mode!=='world'}><Backpack size={20}/></button><button className="icon-button fullscreen-button" title={fullScreen?'Sair da tela cheia':'Tela cheia'} aria-label={fullScreen?'Sair da tela cheia':'Entrar em tela cheia'} aria-pressed={fullScreen} onClick={()=>void toggleFullscreen()}>{fullScreen?<Minimize size={20}/>:<Maximize size={20}/>}</button><button className="icon-button" title="Som" aria-label={sound?'Desativar som':'Ativar som'} onClick={()=>{const on=!sound;engine.sound=on;setSound(on);void music.current?.setEnabled(on);}}>{sound?<Volume2 size={20}/>:<VolumeX size={20}/>}</button><button className="icon-button controls-button" title="Controles" aria-label="Abrir controles" onClick={()=>s.mode==='world'?openMenu('settings'):setPanel('help')} disabled={s.mode==='battle'||s.mode==='dialogue'||s.mode==='cutscene'}><CircleHelp size={20}/></button></nav></header>
  <div className="game-body"><div className="portrait-tip"><RotateCcw size={17}/><span>Para jogar, vire o celular na horizontal.</span></div><section className="play-column" aria-label="Área de jogo">
   <div className="world" ref={setViewport}><canvas ref={canvas} role="img" aria-label={`Mapa navegável de ${MAPS[s.map].name}. Use WASD ou as setas. E para interagir. Toque nos pontos de interesse para caminhar até eles.`} onPointerUp={e=>{shell.current?.focus();renderer.current?.click(e.clientX,e.clientY);}}/>
    {s.mode==='world'&&<><div className="location-title"><span className="eyebrow">{MAPS[s.map].subtitle}</span><h1>{MAPS[s.map].name}</h1><span className={`area-tag ${MAPS[s.map].safe?'safe':'hostile'}`}><Shield size={12}/>{MAPS[s.map].safe?'Área segura':'Criaturas de Éter'}</span></div><button className="hud-minimap" aria-label="Abrir minimapa e viagens" onClick={()=>openMenu('map')}><MiniMap s={s} engine={engine}/><span><span className="map-label-long">Mapa · Viagens</span><span className="map-label-short">Mapa</span></span></button><button className="mobile-objective" onClick={()=>openMenu('map')}><span className="gold">◆</span><span>{OBJECTIVES[s.stage].title}</span><BookOpen size={16}/></button><div className="world-hint"><Move size={14}/> Clique para caminhar <span>•</span> WASD / Setas <span>•</span> E interagir <span>•</span> Enter menu</div>
    <div className="field-quickbar" aria-label="Acesso rápido de exploração">{engine.fieldSlots().map((tech,i)=>{const caster=s.heroes[0],remaining=Math.max(0,Math.ceil(((s.progress.fieldUntil[tech.id]||0)-Date.now())/1000)),learned=!tech.node||s.progress.learned.includes(tech.node);return <button key={tech.id} disabled={!learned||caster.hp<=0||tech.cost>0&&caster.mp<engine.skillCost(caster.id,tech.cost)||tech.id==='ink-focus'&&(caster.hp<=10||caster.mp===caster.maxMp)} onClick={()=>engine.quickField(i)} title={`${caster.name}: ${tech.name} · ${tech.timed?'15 segundos': 'instantânea'}`}><kbd>{i?'R':'Q'}</kbd><GameIcon index={tech.icon}/><span>{tech.name}<small>{!learned?'Aprenda na árvore':remaining?`${remaining}s restantes`:`${tech.cost} MP`}</small></span></button>;})}<button className="leader-swap" disabled={s.heroes.length<2} onClick={()=>engine.swapLeader()} aria-label="Trocar líder e habilidades de exploração"><img src={ASSETS[`dlg_${s.heroes[0].id}`]} alt=""/><span>{s.heroes[0].name}<small>Tab · Trocar</small></span></button></div>
    <nav className="map-exits" aria-label="Saídas deste mapa">{engine.activeEntities().filter(e=>e.kind==='warp').map(e=><button key={e.id} disabled={!!e.minStage&&s.stage<e.minStage} onClick={()=>engine.approach(e.id)} title={e.minStage&&s.stage<e.minStage?'Avance na história para abrir esta passagem':`Caminhar até ${e.to?MAPS[e.to].name:e.label}`}><MapPin size={14}/><span>{e.to?MAPS[e.to].name:e.label}</span></button>)}</nav><div className="touch-controls"><div className="dpad"><button className="up" aria-label="Mover para cima" {...hold('ArrowUp')}><ChevronUp/></button><button className="left" aria-label="Mover para esquerda" {...hold('ArrowLeft')}><ChevronLeft/></button><span/><button className="right" aria-label="Mover para direita" {...hold('ArrowRight')}><ChevronRight/></button><button className="down" aria-label="Mover para baixo" {...hold('ArrowDown')}><ChevronDown/></button></div></div>
    {s.nearby&&<button className="interact-prompt" onClick={()=>engine.interact()}><kbd>E</kbd><span>{s.nearby.label}</span><Sparkles size={17}/></button>}
    </>}
    {s.mode==='start'&&<div className="start-screen animated-title"><picture><source media="(max-width:650px) and (orientation:portrait)" srcSet="/assets/world/title-stone-reach-mobile-v14.webp"/><img className="title-backdrop" src="/assets/world/title-stone-reach-v14.webp" alt=""/></picture><div className="title-shade"/><TitleAtmosphere/><div className="start-copy"><span className="eyebrow">STONE REACH</span><h1>Éter <em>Anima</em></h1><div className="title-rule"/><h2>O que o selo lembra</h2><div className="start-actions">{!titleArmed?<button className="primary-button press-start" onClick={activateTitle} disabled={!loaded}>{loaded?'PRESS START':'Preparando Stone Reach…'}<small>Enter ou toque</small></button>:<>{s.hasSave&&<button className="primary-button" onClick={()=>engine.start(true)} disabled={!loaded}>Continuar aventura</button>}<button className={s.hasSave?'secondary-button':'primary-button'} onClick={()=>engine.selectProtagonist()} disabled={!loaded}>Começar aventura<Sword size={18}/></button></>}</div><div className="start-meta">{titleArmed?(musicStatus==='playing'?<><Volume2 size={14}/>Press Start Screen · em loop</>:<button className="text-button" onClick={()=>void music.current?.unlock()}>Ativar trilha de abertura</button>):<><Keyboard size={16}/>Teclado, mouse ou toque</>}</div></div></div>}
    {s.mode==='cutscene'&&<Cutscene s={s} engine={engine}/>}

    {s.mode==='selection'&&<div className="origin-screen"><header><span className="eyebrow">CINCO ORIGENS · UM SELO</span><h1>Quem vai lembrar?</h1><p>Escolha o protagonista. A jornada começa a sós; os aliados serão encontrados no caminho.</p></header><div className="origin-cards" role="group" aria-label="Escolher protagonista">{heroBases().filter(h=>h.id!=='beatriz').map(h=><button className={`origin-card ${chosen===h.id?'selected':''}`} key={h.id} aria-pressed={chosen===h.id} onClick={()=>setChosen(h.id)}><img src={ASSETS[`dlg_${h.id}`]} alt=""/><span><small>{h.element} · {h.role}</small><strong>{h.name}</strong><em>{MAPS[ORIGINS[h.id].map].name}</em></span></button>)}</div><section className="origin-details" aria-live="polite"><div><span className="eyebrow">{heroBases().find(h=>h.id===chosen)!.name}</span><h2>{ORIGINS[chosen].title}</h2><p>{ORIGINS[chosen].lore}</p></div><div className="origin-actions"><button className="primary-button" data-origin-start onClick={()=>s.hasSave?setConfirmReset(true):engine.start(false,chosen)}>Começar com {heroBases().find(h=>h.id===chosen)!.name}</button><button className="secondary-button" onClick={()=>engine.returnToTitle()}>Voltar à abertura</button></div></section></div>}
    {s.mode==='dialogue'&&line&&<div className="dialogue-scene" aria-label="Diálogo"><div className="dialogue-shade"/><img className={`dialogue-art art-left ${line.speaker===leftName||line.both?'speaking':'listening'}`} src={ASSETS[`dlg_${left==='gabriel'&&s.progress.gabrielForm==='lycan'?'gabriel_lycan':left}`]} alt={leftName}/>{right&&right!==left&&<img className={`dialogue-art art-right ${line.speaker===(({seiji:'Seiji',beatriz:'Beatriz',ophelia:'Ophelia',orfeu:'Orfeu',ava:'Ava',abel:'Abel',max:'Max',marin:'Marin',gabriel:'Gabriel',carmilla:'Carmilla'}[right]))||line.both?'speaking':'listening'}`} src={ASSETS[`dlg_${right==='gabriel'&&s.progress.gabrielForm==='lycan'?'gabriel_lycan':right}`]} alt={({seiji:'Seiji',beatriz:'Beatriz',ophelia:'Ophelia',orfeu:'Orfeu',ava:'Ava',abel:'Abel',max:'Max',marin:'Marin',gabriel:'Gabriel',carmilla:'Carmilla'}[right])}/>}<div className="dialogue-box"><div className="speaker-label"><span className="gold">◆</span>{line.speaker}<small>{line.speaker==='Seiji'?'TINTA':line.speaker==='Ophelia'?'GELO':line.speaker==='Beatriz'?'STONE REACH':''}</small></div><p key={`${d!.index}-${line.text}`}>{line.text}</p><div className="dialogue-footer"><span>{d!.index+1} / {d!.lines.length}</span>{d!.choice&&d!.index===d!.lines.length-1?<div className="dialogue-choices"><button className="secondary-button" onClick={()=>engine.choose(false)}>Ainda não</button><button className="primary-button" onClick={()=>engine.choose(true)}>Vamos investigar</button></div>:<button onClick={()=>engine.nextDialogue()}>Avançar <kbd>Enter</kbd></button>}</div></div></div>}
    {s.mode==='battle'&&b&&<div className="battle-screen"><div className="battle-heading"><span className="eyebrow">{b.eventId?.startsWith('recruit-')?'DUELO DE RECRUTAMENTO':b.boss?(b.entityId==='cinder'?'CONFRONTO DA PIRA':b.entityId==='eco'?'CONFRONTO DA GALERIA':'CONFRONTO DO CAPÍTULO'):'ÉTER TRANSBORDADO'}</span><h2>{b.name}</h2><small>{b.boss?`Fase ${b.phase}/3 · `:''}Ultimate {b.bossCharge}%</small><Progress className="enemy-bar" value={b.hp/b.maxHp*100}/><span>{b.hp} / {b.maxHp} HP {b.weakened?'• Enfraquecido':''}</span><StatusBadges states={b.statuses.enemy}/></div><div className="turn-order"><span>RODADA {b.round}</span>{b.queue.map((id,i)=><i className={i===b.index?'current-turn':''} key={id}>{id==='enemy'&&['ashwolf','moth','cinder'].includes(b.asset)?<span className="turn-sprite" style={{backgroundImage:`url(${ASSETS[b.asset]})`,backgroundPosition:`0% ${{ashwolf:0,moth:50,cinder:100}[b.asset as 'ashwolf'|'moth'|'cinder']}%`}}/>:<img src={ASSETS[id==='enemy'&&b.eventId?.startsWith('recruit-')?`dlg_${b.asset}`:id==='enemy'?b.asset:`dlg_${id}`]} alt=""/>}<strong>{id==='enemy'?b.eventId?.startsWith('recruit-')?'Desafiante':b.boss?'Chefe':'Inimigo':s.heroes.find(h=>h.id===id)?.name}</strong><small>{i===b.index?'AGORA':i<b.index?'AGIU':'A SEGUIR'}</small></i>)}</div><BattleScene map={s.map} battle={b} heroes={s.heroes} progress={s.progress}/><div className="battle-console"><div className="battle-log" aria-live="polite">{b.log.slice(-2).map((text,i)=><p key={`${b.log.length}-${i}`}>{text}</p>)}</div>{b.result?<div className="battle-result"><h3>{b.result==='victory'?'Vitória':'O caminho de volta'}</h3><p>{b.result==='victory'?`+${b.credits} créditos · +${b.xp} XP.`:'O grupo retorna ao último cristal sem perder a missão.'}</p><button className="primary-button" onClick={()=>engine.finishBattle()}>{b.result==='victory'?'Continuar':'Retornar ao cristal'}</button></div>:<BattleCommands engine={engine} s={s} target={target} setTarget={setTarget}/>}</div><UltimateCinematic battle={b} heroes={s.heroes} map={s.map} progress={s.progress}/></div>}
    {s.rewardNotice&&s.mode==='world'&&<aside className="reward-quick" role="status"><Gem size={18}/><span>{s.rewardNotice.text}</span><button className="secondary-button" onClick={()=>{const notice=s.rewardNotice!;openMenu(notice.tab,notice.focus);engine.dismissNotice();}}>Ver {({gear:'equipamento',gacha:'relíquia',skills:'habilidades',bag:'bolsa',achievements:'conquista'} as Record<string,string>)[s.rewardNotice.tab]||'recompensas'}</button><button className="notice-close" onClick={()=>engine.dismissNotice()} aria-label="Dispensar recompensa">×</button></aside>}
    {s.toast&&!s.rewardNotice&&(s.mode==='world'||s.toast.startsWith('Tela cheia indisponível'))&&<div className="game-toast" role="status"><Sparkles size={16}/>{s.toast}</div>}
   </div>
   <footer className="party-footer">{s.heroes.map(h=><HeroCard key={h.id} h={h} lycan={s.progress.gabrielForm==='lycan'} active={hero?.id===h.id}/>)}<div className="save-status"><span><Gem size={14}/>{s.progress.masterMode?'∞':s.credits} créditos · Nv {level(s.progress)}{s.progress.masterMode?' · MESTRE':''}</span><small><Check size={12}/>{s.saving||'Progresso neste navegador'}</small></div></footer>
  </section></div>
  <GameDialog container={shell.current} open={!!panel} onClose={()=>setPanel(null)} className={panel==='menu'?'menu-modal':''}><DialogHeader><DialogTitle>{panel==='menu'?'Menu de aventura':panel==='help'?'Controles e regras':panel==='bag'?'Grupo e bolsa':'Diário de Stone Reach'}</DialogTitle><DialogDescription>{panel==='menu'?`Stone Reach · ${s.heroes.map(h=>h.name).join(' e ')}`:panel==='help'?'Escolha como explorar e conduzir o grupo.':panel==='bag'?'Os recursos acompanham o grupo durante o capítulo.':'O que o selo lembra'}</DialogDescription></DialogHeader>
   {panel==='menu'&&<GameMenu key={menuTab} s={s} engine={engine} initialTab={menuTab} initialFocus={menuFocus} journal={<Journal s={s} engine={engine} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/>} settings={settings} onClose={()=>{engine.paused=false;setPanel(null);}} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/>}
   {panel==='journal'&&<div className="journal-modal"><Journal s={s} engine={engine} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/><button className="primary-button" onClick={()=>setPanel(null)}>Voltar à aventura</button></div>}
   {panel==='bag'&&<Tabs defaultValue="bag"><TabsList><TabsTrigger value="bag">Bolsa</TabsTrigger><TabsTrigger value="party">Grupo</TabsTrigger></TabsList><TabsContent value="bag"><div className="bag-counts"><span><Heart/> Poções <b>{s.potions}</b><small>Restaura 45 HP</small></span><span><Gem/> Elixires <b>{s.ethers}</b><small>Restaura 24 MP</small></span></div><p className="muted">Escolha quem receberá o item.</p>{s.heroes.map(h=><div className="bag-hero" key={h.id}><HeroCard h={h}/><div><button disabled={s.mode!=='world'||!s.potions||h.hp===h.maxHp} onClick={()=>engine.useItem('potion',h.id)}>Usar Poção</button><button disabled={s.mode!=='world'||!s.ethers||h.mp===h.maxMp} onClick={()=>engine.useItem('ether',h.id)}>Usar Elixir</button></div></div>)}{s.stage>=5&&<div className="relic"><Gem size={24}/><div><strong>Selo Ressonante</strong><p>Relíquia recuperada no subterrâneo.</p></div></div>}</TabsContent><TabsContent value="party">{s.heroes.map(h=><div className="party-detail" key={h.id}><HeroCard h={h}/><p>{h.role} • {h.element} • Velocidade {h.spd}</p>{SKILLS[h.id].map(sk=><p key={sk.id}><strong>{sk.name}</strong> • {sk.cost} MP<br/>{sk.description}</p>)}</div>)}</TabsContent></Tabs>}
   {panel==='help'&&<div className="help-content"><div><Keyboard/><p><strong>Teclado</strong><br/>WASD ou setas para caminhar. E interage; Enter abre o menu ou avança diálogos. Esc fecha os painéis.</p></div><div><Move/><p><strong>Mouse e celular</strong><br/>Toque no cenário para caminhar. Toque em um objeto ou personagem para chegar perto e interagir. No celular, use também o direcional.</p></div><div><Shield/><p><strong>Combate por turnos</strong><br/>Observe a ordem de ação. Guarde-se contra golpes em área. Ophelia cura o alvo selecionado. Poções também recuperam aliados caídos.</p></div><div><Sparkles/><p><strong>Estados e progressão</strong><br/>Congelamento perde uma ação. Cegueira pode fazer golpes errarem. Sangramento causa 6 de dano por ação. Silêncio bloqueia magias. Guarda evita os estados dos ataques inimigos; Aurora e Antídoto removem estados. Os números ao lado dos ícones indicam ações restantes. No menu de aventura, aprenda habilidades, receba metas e equipe conjuntos em um mesmo herói.</p></div><div><Save/><p><strong>Descanso e progresso</strong><br/>Cristais restauram HP e MP. O progresso fica salvo neste navegador, sem sincronização entre dispositivos.</p></div><button className="secondary-button" onClick={()=>{engine.save();setPanel(null);}}>Salvar e voltar</button>{s.mode!=='start'&&<button className="reset-link" onClick={()=>setConfirmReset(true)}><RotateCcw size={14}/>Recomeçar este capítulo</button>}</div>}
  </GameDialog>
  <GameDialog container={shell.current} open={confirmReset} onClose={()=>setConfirmReset(false)}><DialogTitle>Recomeçar o capítulo?</DialogTitle><DialogDescription>O progresso desta versão neste navegador será substituído por uma nova aventura.</DialogDescription><div className="reset-actions"><button className="secondary-button" onClick={()=>setConfirmReset(false)}>Cancelar</button><button className="primary-button" onClick={()=>{setConfirmReset(false);setPanel(null);engine.start(false,chosen);}}>Recomeçar</button></div></GameDialog>
 </main>;
}
