'use client';
import { useEffect, useRef, useState, useSyncExternalStore } from 'react';
import { Volume2, MapPin, Shield, Sword, Sparkles, Heart, ChevronUp, ChevronDown, ChevronLeft, ChevronRight, Move, Keyboard, Save, RotateCcw, Gem } from 'lucide-react';
import { DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Progress } from '@/components/ui/progress';
import { ASSETS, ORIGINS, heroBases, MAPS, OBJECTIVES, SKILLS, type HeroId } from '@/lib/game/data';
import { GameEngine, type Snapshot } from '@/lib/game/engine';
import { WorldRenderer } from '@/lib/game/renderer';
import {WorldLoadingV32} from '@/components/world-loading-v32';
import {BattleIntentV32} from '@/components/battle-intent-v32';
import {GameMenu,StatusBadges} from '@/components/game-menu';
import {BattleCommands} from '@/components/battle-commands';
import battleStyles from '@/components/battle-interface.module.css';
import {CombatParty} from '@/components/combat-party';
import {TurnOrder} from '@/components/turn-order';
import {VictoryCelebration} from '@/components/victory-celebration';
import {QUESTS,ACHIEVEMENTS,BESTIARY,level} from '@/lib/game/progression';
import {Cutscene} from '@/components/cutscene';
import {QuestCinematic} from '@/components/quest-cinematic';
import {MIKA_FRAME_TEST_V35} from '@/lib/art/frameTestV35';
import {QuestTrackerV31} from '@/components/quest-journal-v31';
import {UltimateCinematic} from '@/components/ultimate-cinematic';
import {BattleScene} from '@/components/battle-scene';
import {GameDialog} from '@/components/game-dialog';
import {MiniMap} from '@/components/minimap';
import {GameIcon} from '@/components/game-icon';
import {HudButton,HudIcon} from '@/components/hud-icon';
import {CartographyFrame,FieldArt,TravelDestinationArt} from '@/components/field-hud-art';
import {HeroCard} from '@/components/hero-card';
import {TitleAtmosphere} from '@/components/title-atmosphere';
import {OpeningGallery} from '@/components/opening-gallery';
import {OpeningCinematicV33} from '@/components/opening-cinematic-v33';
import {OriginSelection} from '@/components/origin-selection';
import {LoadingScreen} from '@/components/loading-screen';
import {Slider} from '@/components/ui/slider';
import {MusicDirector,musicFor,MUSIC,readAudioPreferences,saveSoundPreference,saveMusicVolume,type MusicStatus} from '@/lib/game/music';
import {advanceMasterSequence,emptyMasterSequence} from '@/lib/game/master-mode';

function Journal({s,engine,onGo}:{s:Snapshot;engine:GameEngine;onGo?:(id:string)=>void}){const objective=OBJECTIVES[s.stage];return <>
 <div className="eyebrow"><span className="gold">◆</span> MISSÃO ATUAL</div><h2>{objective.title}</h2><p>{objective.text}</p><div className="destination"><MapPin size={14}/>{objective.location}</div>
 <div className="chapter-progress"><span>O que o selo lembra</span><b>{Math.min(s.stage,5)}/5</b></div><Progress className="quest-bar" value={s.stage/5*100}/>
 <div className="map-title"><span>ARREDORES</span><span>{MAPS[s.map].safe?'Área segura':'Área hostil'}</span></div><MiniMap s={s} engine={engine}/><div className="map-legend"><span>● Você</span><span className="gold">◆ Objetivo</span><span className="cyan">● Cristal</span></div>
 <div className="nearby-list"><span className="eyebrow">PONTOS DE INTERESSE</span>{engine.activeEntities().filter(e=>e.kind!=='mob'&&!(e.id==='selo'&&s.stage>=4)&&!(e.id==='eco'&&s.progress.kills.eco>0)).map(e=><button key={e.id} onClick={()=>onGo?onGo(e.id):engine.approach(e.id)} disabled={s.mode!=='world'}><span className={OBJECTIVES[s.stage].target===e.id?'gold':''}>{e.kind==='save'?'◇':e.kind==='warp'?'↳':'◆'}</span>{e.label}</button>)}</div>
 </>;}

export default function Home(){const [engine]=useState(()=>new GameEngine());const s=useSyncExternalStore(engine.subscribe,engine.snapshot,engine.snapshot);const canvas=useRef<HTMLCanvasElement>(null),renderer=useRef<WorldRenderer|null>(null);const [loaded,setLoaded]=useState(false),[panel,setPanel]=useState<'journal'|'bag'|'help'|'menu'|null>(null),[sound,setSound]=useState(false),[confirmReset,setConfirmReset]=useState(false),[target,setTarget]=useState<HeroId>('seiji'),[menuTab,setMenuTab]=useState('party'),[menuFocus,setMenuFocus]=useState<string|undefined>(),[viewport,setViewport]=useState<HTMLElement|null>(null),[chosen,setChosen]=useState<HeroId>('seiji'),[titleArmed,setTitleArmed]=useState(false),[volume,setVolume]=useState(.6),[musicStatus,setMusicStatus]=useState<MusicStatus>('off'),[fullScreen,setFullScreen]=useState(false);
 const shell=useRef<HTMLElement>(null),channel0=useRef<HTMLAudioElement>(null),channel1=useRef<HTMLAudioElement>(null),music=useRef<MusicDirector|null>(null),panelRef=useRef(panel),armedRef=useRef(titleArmed),loadedRef=useRef(loaded);panelRef.current=panel;armedRef.current=titleArmed;loadedRef.current=loaded;
 const [worldLoading,setWorldLoading]=useState<ReturnType<WorldRenderer['getLoadingState']>|null>(null);
 const [activeMenuTab,setActiveMenuTab]=useState('party');
 const [opening,setOpening]=useState(false),openingRef=useRef(false);
 const [frameTest,setFrameTest]=useState(false),frameTestRef=useRef(false);
 const showOpening=()=>{if(engine.state.mode!=='start'||openingRef.current||panelRef.current||confirmReset)return;openingRef.current=true;engine.clearMovement();engine.paused=true;setOpening(true);};
 const closeOpening=()=>{openingRef.current=false;engine.clearMovement();engine.paused=!!panelRef.current||confirmReset;setOpening(false);};
 const openMenu=(tab='party',focus?:string)=>{if(engine.state.mode!=='world'||openingRef.current)return;engine.clearMovement();engine.paused=true;setMenuTab(tab);setActiveMenuTab(tab);setMenuFocus(focus);setPanel('menu');};
 const showFrameTest=()=>{if(frameTestRef.current||engine.state.mode!=='world'||engine.state.questCinematic||engine.state.gachaBusy||engine.state.summonBusy||openingRef.current||panelRef.current!=='menu')return;frameTestRef.current=true;engine.clearMovement();engine.paused=true;const world=renderer.current;if(world&&!world.disposed)cancelAnimationFrame(world.raf);setPanel(null);setFrameTest(true);};
 const closeFrameTest=()=>{if(!frameTestRef.current)return;frameTestRef.current=false;engine.clearMovement();setFrameTest(false);openMenu('scenes',MIKA_FRAME_TEST_V35.id);const world=renderer.current;if(world&&!world.disposed){world.frame=0;world.raf=requestAnimationFrame(world.draw);}};
 const replayQuestScene=(questId:string)=>{if(!engine.replayQuestCinematic(questId))return;engine.paused=true;setPanel(null);};
 const finishQuestScene=(token:number,skip=false)=>{const session=engine.state.questCinematic;if(!session||session.token!==token)return;const replay=session.replay,id=session.questId;if(!engine.finishQuestCinematic(skip,token))return;if(replay)openMenu('scenes',id);};
 const toggleFullscreen=async()=>{const game=shell.current;if(!game)return;engine.clearMovement();engine.toast('');type WebkitElement=HTMLElement&{webkitRequestFullscreen?:()=>Promise<void>|void};type WebkitDocument=Document&{webkitFullscreenElement?:Element;webkitExitFullscreen?:()=>Promise<void>|void};const doc=document as WebkitDocument;try{if(document.fullscreenElement||doc.webkitFullscreenElement){if(document.exitFullscreen)await document.exitFullscreen();else await doc.webkitExitFullscreen?.();return;}if(game.requestFullscreen)await game.requestFullscreen();else if((game as WebkitElement).webkitRequestFullscreen)await (game as WebkitElement).webkitRequestFullscreen!();else throw new Error('unsupported');const orientation=screen.orientation as ScreenOrientation&{lock?:(mode:string)=>Promise<void>};if(window.matchMedia('(pointer:coarse)').matches)try{await orientation?.lock?.('landscape');}catch{/* Rotation remains a device choice when unsupported. */}}catch{engine.toast('Tela cheia indisponível aqui. Abra o jogo no Chrome ou Safari e vire o celular na horizontal.');}};
 useEffect(()=>{const sync=()=>setFullScreen(!!(document.fullscreenElement||(document as Document&{webkitFullscreenElement?:Element}).webkitFullscreenElement));document.addEventListener('fullscreenchange',sync);document.addEventListener('webkitfullscreenchange',sync);return()=>{document.removeEventListener('fullscreenchange',sync);document.removeEventListener('webkitfullscreenchange',sync);};},[]);
 const setGameSound=(enabled:boolean)=>{setSound(enabled);engine.sound=enabled;saveSoundPreference(enabled);void music.current?.setEnabled(enabled);};
 const activateTitle=()=>{setTitleArmed(true);armedRef.current=true;void music.current?.unlock();};
 const toggleMusic=()=>setGameSound(!music.current?.enabled);
 useEffect(()=>{const director=new MusicDirector([channel0.current!,channel1.current!],setMusicStatus),preferences=readAudioPreferences();music.current=director;director.setVolume(preferences.volume);setVolume(preferences.volume);setSound(preferences.enabled);engine.sound=preferences.enabled;void director.setEnabled(preferences.enabled);const retry=()=>{if(director.enabled)void director.unlock();};window.addEventListener('pointerdown',retry,{once:true});window.addEventListener('keydown',retry,{once:true});return()=>{window.removeEventListener('pointerdown',retry);window.removeEventListener('keydown',retry);director.dispose();music.current=null;};},[engine]);
 useEffect(()=>{if(!s.heroes.some(h=>h.id===target))setTarget(s.heroes[0].id);},[s.heroes.map(h=>h.id).join(','),target]);
 useEffect(()=>{music.current?.request(musicFor(s));},[s.mode,s.map,s.battle?.boss,s.cutscene?.id]);
 useEffect(()=>{engine.setBattleArtGateV32(true);engine.hydrate();const r=new WorldRenderer(canvas.current!,engine,{onLoadingChange:setWorldLoading});renderer.current=r;void r.load().then(result=>setLoaded(result));let masterSequence=emptyMasterSequence();
  const down=(e:KeyboardEvent)=>{const target=e.target; if(target instanceof Element&&target.closest('input,select,textarea,[role=slider]'))return;const key=e.key.length===1?e.key.toLowerCase():e.key;
   if(openingRef.current){engine.clearMovement();if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^F\d+$/.test(key))e.preventDefault();return;}
   if(frameTestRef.current){engine.clearMovement();if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^F\d+$/.test(key)&&(!(target instanceof Element)||!target.closest('button')))e.preventDefault();return;}
   if(engine.state.questCinematic){if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^F\d+$/.test(key)&&(!(target instanceof Element)||!target.closest('button')))e.preventDefault();engine.clearMovement();return;}
   if(key==='Escape'){if(engine.state.mode==='selection')engine.returnToTitle();if(panelRef.current){e.preventDefault();setPanel(null);}engine.clearMovement();return;}
   if(panelRef.current)return;
   const loadingState=renderer.current?.getLoadingState();if(loadingState&&(loadingState.loading||loadingState.error)){engine.clearMovement();if(!e.ctrlKey&&!e.metaKey&&!e.altKey&&!/^F\d+$/.test(key)&&!(target instanceof Element&&target.closest('button')))e.preventDefault();return;}
   if(key==='Tab'&&target instanceof Element&&target.closest('[data-exploration-party]'))return;
   const interactive=target instanceof Element&&!!target.closest('button,[role=tab]');if(interactive&&(key==='Enter'||key===' '))return;
   if(!e.repeat&&/^[1-5]$/.test(key)){const slot=Number(key)-1,ally=engine.state.heroes[slot];if(engine.state.mode==='world'&&!engine.paused){e.preventDefault();engine.selectPartySlot(slot);return;}if(engine.state.mode==='battle'&&ally&&!engine.state.battle?.result){e.preventDefault();setTarget(ally.id);return;}}
   if(engine.state.mode==='world'&&!engine.paused&&!e.repeat&&!engine.state.progress.masterMode){const result=advanceMasterSequence(masterSequence,key,Date.now());masterSequence=result.state;if(result.activated){e.preventDefault();engine.clearMovement();engine.activateMasterMode();return;}if(result.consumeMovement){e.preventDefault();return;}}
   if(engine.state.mode==='selection'){if(key==='Enter'&&!e.repeat){e.preventDefault();document.querySelector<HTMLButtonElement>('[data-origin-start]')?.click();}if(key==='Escape'){engine.returnToTitle();}return;}
   if(engine.state.mode==='start'){if(key==='Enter'&&!e.repeat&&loadedRef.current){e.preventDefault();if(!armedRef.current)activateTitle();else if(engine.state.hasSave)engine.start(true);else engine.selectProtagonist();}return;}
   if(engine.state.mode==='world'&&!engine.paused&&!e.repeat&&['q','r','Tab','g','i','k','m','l','v','o','p',' '].includes(key)){e.preventDefault();if(key==='Tab')engine.swapLeader();else if(key==='q'||key==='r')engine.quickField(key==='q'?0:1);else if(key==='g')openMenu('party');else if(key==='i')openMenu('bag');else if(key==='k')openMenu('skills');else if(key==='m')openMenu('map');else if(key==='l')openMenu('quests');else if(key==='v')openMenu('achievements');else if(key==='o')openMenu('gacha');else if(key==='p')toggleMusic();else engine.blink();return;}
   if(key==='Enter'&&engine.state.mode==='world'&&!e.repeat){e.preventDefault();openMenu();return;}
   if(!engine.paused&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','Enter'].includes(key))e.preventDefault();
   if(engine.state.mode==='world'&&['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d','Shift'].includes(key))engine.keys.add(key);
   if(!e.repeat&&(key==='e'||key==='Enter'||key===' ')){if(engine.state.mode==='cutscene')engine.nextCutscene();else if(engine.state.mode==='dialogue')engine.nextDialogue();else if(key!=='Enter')engine.interact();}
  };
  const up=(e:KeyboardEvent)=>engine.keys.delete(e.key.length===1?e.key.toLowerCase():e.key);const blur=()=>engine.clearMovement();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);
  return()=>{window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);r.destroy();engine.dispose();};
 },[engine]);
 useEffect(()=>{if(s.overlay){setMenuTab(s.overlay);setActiveMenuTab(s.overlay);setPanel('menu');engine.state.overlay=null;}},[s.overlay,engine]);
 useEffect(()=>{engine.paused=!!panel||confirmReset||opening||frameTest||!!s.questCinematic?.replay;if(engine.paused)engine.clearMovement();},[panel,confirmReset,opening,frameTest,s.questCinematic?.replay,engine]);
 useEffect(()=>{const d=document as Document & {modelContext?:{registerTool:(t:unknown,o?:unknown)=>unknown}};if(!d.modelContext?.registerTool)return;const life=new AbortController();const reg=(tool:unknown)=>{try{void Promise.resolve(d.modelContext!.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}};
  reg({name:'read_eter_game_state',description:'Read current location, mission, party and nearby interactions in Éter Anima.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({map:engine.state.map,stage:engine.state.stage,mode:engine.state.mode,position:engine.state.position,objective:OBJECTIVES[engine.state.stage].text,heroes:engine.state.heroes,nearby:engine.nearest()?.id})});
  reg({name:'walk_to_eter_interaction',description:'Start walking through the real map toward a named point of interest, then interact when nearby. Does not teleport or bypass mission conditions.',inputSchema:{type:'object',properties:{entityId:{type:'string'}},required:['entityId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:{entityId:string})=>{if(!input||typeof input.entityId!=='string'||!engine.activeEntities().some(e=>e.id===input.entityId))throw new Error('Unknown interaction');return {walking:engine.approach(input.entityId)};}});
  return()=>life.abort();
 },[engine]);
 const rewards=engine.questJournalV31().filter(q=>q.status==='complete').length+QUESTS.filter(q=>q.value(s)>=q.goal&&!s.progress.questClaims.includes(q.id)&&(!q.request||s.progress.requests.includes(q.request))).length+ACHIEVEMENTS.filter(a=>a.test(s)&&!s.progress.achievementClaims.includes(a.id)).length+BESTIARY.reduce((n,m)=>n+(m.set?[5,25,50]:[1]).filter(goal=>(s.progress.kills[m.id]||0)>=goal&&!s.progress.bestiaryClaims.includes(`${m.id}-${goal}`)).length,0);
 const d=s.dialogue,line=d?.lines[d.index],left=s.progress.protagonist||'seiji',leftName=heroBases().find(h=>h.id===left)!.name,right=line?.right||s.heroes.find(h=>h.id!==left)?.id,b=s.battle,hero=engine.currentHero();const hold=(key:string)=>({onPointerDown:(e:React.PointerEvent<HTMLButtonElement>)=>{e.preventDefault();if(openingRef.current||frameTestRef.current)return;e.currentTarget.setPointerCapture(e.pointerId);engine.keys.add(key);},onPointerUp:()=>engine.keys.delete(key),onPointerCancel:()=>engine.keys.delete(key),onLostPointerCapture:()=>engine.keys.delete(key)});
 const currentTrack=musicFor(s);
 const settings=<div className="settings-content"><h3>Trilhas e som</h3><p>{MUSIC[currentTrack].name}</p><button className="secondary-button" onClick={toggleMusic}>{sound?'Desativar som':'Ativar som'}</button><label>Volume · {Math.round(volume*100)}%</label><Slider aria-label="Volume das trilhas" min={0} max={100} step={5} value={[Math.round(volume*100)]} onValueChange={values=>{const value=values[0]/100;setVolume(value);music.current?.setVolume(value);saveMusicVolume(value);}}/><p><strong>Movimento reduzido</strong> · O jogo acompanha a preferência de acessibilidade do seu sistema. As cenas começam pausadas quando ela está ativa; você pode reproduzir ou pular. Isso preserva recompensas e chances de invocação.</p><div className="menu-system-actions"><button className="secondary-button" onClick={()=>{engine.save();setPanel(null);}}>Salvar e voltar</button><button className="secondary-button" onClick={()=>{setPanel(null);engine.returnToTitle();}}>Salvar e ir à abertura</button><button className="text-button" onClick={()=>{engine.save();setPanel(null);engine.selectProtagonist();}}>Recomeçar aventura</button></div><div className="help-content"><p><strong>PC</strong> · WASD/setas para caminhar. E para interagir. Q/R usam os dois slots de exploração. Tab troca o líder. Enter abre o menu; em diálogos e cenas, avança. Esc fecha o menu.</p><p><strong>Mobile</strong> · Jogue na horizontal. O botão Tela cheia expande a área de jogo quando o navegador permite. Toque no cenário, use o direcional ou os ícones no topo. Todo o menu fica dentro da tela do jogo.</p><p>O progresso é salvo neste navegador. Cristais restauram HP/MP. Guarda reduz dano e bloqueia estados inimigos.</p></div></div>;
 return <main className={'game-shell '+(s.mode==='battle'?battleStyles.battleMode:'')} ref={shell} tabIndex={-1} data-game-mode={s.mode} data-fullscreen={fullScreen} data-music-track={currentTrack} data-music-status={musicStatus}>
  <audio ref={channel0} muted={!sound} loop preload="none"/><audio ref={channel1} muted={!sound} loop preload="none"/>
  {opening&&<OpeningCinematicV33 onExit={closeOpening}/>}
  {frameTest&&<QuestCinematic questId={MIKA_FRAME_TEST_V35.id} filmSpec={MIKA_FRAME_TEST_V35} replay onComplete={closeFrameTest} onSkip={closeFrameTest}/>}
  {!loaded&&!worldLoading&&<LoadingScreen/>}{worldLoading&&(worldLoading.loading||worldLoading.error)&&<WorldLoadingV32 status={worldLoading} onRetry={()=>{void renderer.current?.retryLoading().then(ready=>{if(ready)setLoaded(true);});}}/>}
  <header className="game-header">
   <div className="brand"><HudIcon name="emblem"/><span>ÉTER <em>ANIMA</em></span><small>STONE REACH</small></div>
   <div className="chapter-label"><HudIcon name="events"/><span>O que o selo lembra</span><i>01</i></div>
   <nav aria-label="Menu do jogo">
    <HudButton icon="journal" label="Abrir diário de missão" caption="Diário" shortcut="L" active={panel==='menu'&&activeMenuTab==='quests'} onClick={()=>openMenu('quests')} disabled={s.mode!=='world'}/>
    <HudButton icon="mail" label="Abrir MAIL · presente inicial" caption="MAIL" active={panel==='menu'&&activeMenuTab==='mail'} badge={!s.progress.starterMailClaimed||s.progress.starterSelectorPending?1:0} badgeLabel="Presente inicial disponível" onClick={()=>openMenu('mail')} disabled={s.mode!=='world'}/>
    <HudButton icon="menu" label="Abrir menu de aventura" caption="Aventura" shortcut="Enter" active={panel==='menu'&&!['quests','mail','skills','gear','bag','settings'].includes(activeMenuTab)} badge={rewards} badgeLabel={`${rewards} recompensas disponíveis`} onClick={()=>openMenu(rewards?'rewards':'party')} disabled={s.mode!=='world'}/>
    <HudButton icon="skills" label="Abrir habilidades" caption="Técnicas" shortcut="K" active={panel==='menu'&&activeMenuTab==='skills'} onClick={()=>openMenu('skills')} disabled={s.mode!=='world'}/>
    <HudButton icon="gear" label={s.progress.unseenGear.length?`Ver ${s.progress.unseenGear.length} equipamentos novos`:'Abrir equipamentos'} caption="Equipar" active={panel==='menu'&&activeMenuTab==='gear'} badge={s.progress.unseenGear.length} badgeLabel={`${s.progress.unseenGear.length} equipamentos novos`} onClick={()=>openMenu('gear',s.progress.unseenGear[0])} disabled={s.mode!=='world'}/>
    <HudButton icon="bag" label="Abrir bolsa" caption="Bolsa" shortcut="I" active={panel==='menu'&&activeMenuTab==='bag'} onClick={()=>openMenu('bag')} disabled={s.mode!=='world'}/>
    <HudButton icon={fullScreen?'fullscreenExit':'fullscreenEnter'} label={fullScreen?'Sair da tela cheia':'Entrar em tela cheia'} caption="Tela cheia" active={fullScreen} onClick={()=>void toggleFullscreen()}/>
    <HudButton icon={sound?'audioOn':'audioOff'} label={sound?'Desativar som':'Ativar som'} caption={sound?'Som ativo':'Sem som'} shortcut="P" active={sound} onClick={toggleMusic}/>
    <HudButton icon="help" label="Abrir controles e sistema" caption="Controles" active={panel==='help'||panel==='menu'&&activeMenuTab==='settings'} onClick={()=>s.mode==='world'?openMenu('settings'):setPanel('help')} disabled={s.mode==='battle'||s.mode==='dialogue'||s.mode==='cutscene'}/>
   </nav>
  </header>
  <div className="game-body"><div className="portrait-tip"><RotateCcw size={17}/><span>Para jogar, vire o celular na horizontal.</span></div><section className="play-column" aria-label="Área de jogo">
   <div className="world" ref={setViewport}><canvas ref={canvas} role="img" aria-label={`Mapa navegável de ${MAPS[s.map].name}. Use WASD ou as setas. E para interagir. Toque nos pontos de interesse para caminhar até eles.`} onPointerUp={e=>{if(openingRef.current||frameTestRef.current)return;shell.current?.focus();renderer.current?.click(e.clientX,e.clientY);}}/>
    {s.mode==='world'&&<><div className="location-title"><span className="eyebrow">{MAPS[s.map].subtitle}</span><h1>{MAPS[s.map].name}</h1><span className={`area-tag ${MAPS[s.map].safe?'safe':'hostile'}`}><Shield size={12}/>{MAPS[s.map].safe?'Área segura':'Criaturas de Éter'}</span></div><QuestTrackerV31 engine={engine} onJournal={()=>openMenu('quests')} onGo={id=>engine.approach(id)}/><button className="hud-minimap" aria-label="Abrir minimapa e viagens" onClick={()=>openMenu('map')}><CartographyFrame><MiniMap s={s} engine={engine}/></CartographyFrame><span className="cartography-label"><HudIcon name="map"/><span className="map-label-long">Mapa · Viagens</span><span className="map-label-short">Mapa</span></span></button><button className="mobile-objective" onClick={()=>openMenu('map')}><span className="gold">◆</span><span>{OBJECTIVES[s.stage].title}</span><HudIcon name="journal"/></button><div className="world-hint"><Move size={14}/> Clique para caminhar <span>•</span> WASD / Setas <span>•</span> E interagir <span>•</span> Enter menu</div>
    <div className="field-quickbar" aria-label="Acesso rápido de exploração">{engine.fieldSlots().map((tech,i)=>{const caster=engine.leader(),remaining=Math.max(0,Math.ceil(((s.progress.fieldUntil[tech.id]||0)-Date.now())/1000)),learned=!tech.node||s.progress.learned.includes(tech.node);return <button key={tech.id} disabled={!learned||caster.hp<=0||tech.cost>0&&caster.mp<engine.skillCost(caster.id,tech.cost)||tech.id==='ink-focus'&&(caster.hp<=10||caster.mp===caster.maxMp)} onClick={()=>engine.quickField(i)} title={`${caster.name}: ${tech.name} · ${tech.timed?'15 segundos': 'instantânea'}`}><kbd>{i?'R':'Q'}</kbd><GameIcon index={tech.icon}/><span>{tech.name}<small>{!learned?'Aprenda na árvore':remaining?`${remaining}s restantes`:`${tech.cost} MP`}</small></span></button>;})}<button className="leader-swap" disabled={s.heroes.length<2} onClick={()=>engine.swapLeader()} aria-label="Trocar líder e habilidades de exploração"><img src={ASSETS[`dlg_${engine.leader().id}`]} alt=""/><span>{engine.leader().name}<small>1–5 / Tab · Trocar</small></span></button></div>
    <nav className="map-exits" aria-label="Saídas deste mapa">{engine.activeEntities().filter(e=>e.kind==='warp').map(e=><button key={e.id} disabled={!!e.minStage&&s.stage<e.minStage} onClick={()=>engine.approach(e.id)} title={e.minStage&&s.stage<e.minStage?'Avance na história para abrir esta passagem':`Caminhar até ${e.to?MAPS[e.to].name:e.label}`}><FieldArt name="travel-plaque" className="travel-plaque"/><TravelDestinationArt destination={e.to}/><span className="travel-label">{e.to?MAPS[e.to].name:e.label}</span>{!!e.minStage&&s.stage<e.minStage&&<FieldArt name="marker-lock" className="travel-lock"/>}</button>)}</nav><div className="touch-controls"><div className="dpad"><button className="up" aria-label="Mover para cima" {...hold('ArrowUp')}><ChevronUp/></button><button className="left" aria-label="Mover para esquerda" {...hold('ArrowLeft')}><ChevronLeft/></button><span/><button className="right" aria-label="Mover para direita" {...hold('ArrowRight')}><ChevronRight/></button><button className="down" aria-label="Mover para baixo" {...hold('ArrowDown')}><ChevronDown/></button></div></div>
    {s.nearby&&s.nearby.kind!=='warp'&&<button className="interact-prompt" onClick={()=>engine.interact()}><kbd>E</kbd><span>{s.nearby.label}</span><HudIcon name="interact"/></button>}
    </>}
    {s.mode==='start'&&<div className="start-screen animated-title"><OpeningGallery/><div className="title-shade"/><TitleAtmosphere/><div className="start-copy"><span className="eyebrow">STONE REACH</span><h1>Éter <em>Anima</em></h1><div className="title-rule"/><h2>O que o selo lembra</h2><div className="start-actions">{!titleArmed?<button className="primary-button press-start" onClick={activateTitle} disabled={!loaded}>{loaded?'PRESS START':'Preparando Stone Reach…'}<small>Enter ou toque</small></button>:<>{s.hasSave&&<button className="primary-button" onClick={()=>engine.start(true)} disabled={!loaded}>Continuar aventura</button>}<button className={s.hasSave?'secondary-button':'primary-button'} onClick={()=>engine.selectProtagonist()} disabled={!loaded}>Começar aventura<Sword size={18}/></button></>}<button type="button" className="secondary-button" onClick={showOpening} disabled={!loaded} data-watch-opening="v33"><HudIcon name="scenes"/>Assistir abertura</button></div><div className="start-meta">{titleArmed?(musicStatus==='playing'?<><Volume2 size={14}/>Press Start Screen · em loop</>:<button className="text-button" onClick={()=>setGameSound(true)}>Ativar trilha de abertura</button>):<><Keyboard size={16}/>Teclado, mouse ou toque</>}</div></div></div>}
    {s.mode==='cutscene'&&(s.questCinematic?<QuestCinematic key={s.questCinematic.token} questId={s.questCinematic.questId} replay={s.questCinematic.replay} onComplete={()=>finishQuestScene(s.questCinematic!.token)} onSkip={()=>finishQuestScene(s.questCinematic!.token,true)}/>:<Cutscene s={s} engine={engine}/>)}

    {s.mode==='selection'&&<OriginSelection chosen={chosen} onChoose={setChosen} onStart={()=>s.hasSave?setConfirmReset(true):engine.start(false,chosen)} onBack={()=>engine.returnToTitle()}/> }
    {s.mode==='dialogue'&&line&&<div className="dialogue-scene" aria-label="Diálogo"><div className="dialogue-shade"/><img className={`dialogue-art art-left ${line.speaker===leftName||line.both?'speaking':'listening'}`} src={ASSETS[`dlg_${left==='gabriel'&&s.progress.gabrielForm==='lycan'?'gabriel_lycan':left}`]} alt={leftName}/>{right&&right!==left&&<img className={`dialogue-art art-right ${line.speaker===(({seiji:'Seiji',beatriz:'Beatriz',ophelia:'Ophelia',orfeu:'Orfeu',ava:'Ava',abel:'Abel',max:'Max',marin:'Marin',gabriel:'Gabriel',carmilla:'Carmilla'}[right]))||line.both?'speaking':'listening'}`} src={ASSETS[`dlg_${right==='gabriel'&&s.progress.gabrielForm==='lycan'?'gabriel_lycan':right}`]} alt={({seiji:'Seiji',beatriz:'Beatriz',ophelia:'Ophelia',orfeu:'Orfeu',ava:'Ava',abel:'Abel',max:'Max',marin:'Marin',gabriel:'Gabriel',carmilla:'Carmilla'}[right])}/>}<div className="dialogue-box"><div className="speaker-label"><span className="gold">◆</span>{line.speaker}<small>{line.speaker==='Seiji'?'TINTA':line.speaker==='Ophelia'?'GELO':line.speaker==='Beatriz'?'STONE REACH':''}</small></div><p key={`${d!.index}-${line.text}`}>{line.text}</p><div className="dialogue-footer"><span>{d!.index+1} / {d!.lines.length}</span>{d!.questChoices&&d!.index===d!.lines.length-1?<div className="dialogue-choices quest-dialogue-choices" aria-label="Sua decisão">{d!.questChoices.map(choice=><button className="secondary-button" key={choice.id} onClick={()=>engine.chooseQuestV31(choice.id)}><strong>{choice.label}</strong><small>{choice.detail}</small></button>)}</div>:d!.choice&&d!.index===d!.lines.length-1?<div className="dialogue-choices"><button className="secondary-button" onClick={()=>engine.choose(false)}>Ainda não</button><button className="primary-button" onClick={()=>engine.choose(true)}>Vamos investigar</button></div>:<button onClick={()=>engine.nextDialogue()}>Avançar <kbd>Enter</kbd></button>}</div></div></div>}
    {s.mode==='battle'&&b&&<div className={'battle-screen '+battleStyles.screen}><div className={battleStyles.statusBar}><div className="battle-heading"><span className="eyebrow">{b.eventId?.startsWith('recruit-')?'DUELO DE RECRUTAMENTO':b.boss?(b.entityId==='cinder'?'CONFRONTO DA PIRA':b.entityId==='eco'?'CONFRONTO DA GALERIA':'CONFRONTO DO CAPÍTULO'):'ÉTER TRANSBORDADO'}</span><h2>{b.name}</h2><small>{b.boss?`Fase ${b.phase}/3 · `:''}Ultimate {b.bossCharge}%</small><Progress className="enemy-bar" value={b.hp/b.maxHp*100}/><span>{b.hp} / {b.maxHp} HP {b.weakened?'• Enfraquecido':''}</span><StatusBadges states={b.statuses.enemy}/></div><TurnOrder battle={b} heroes={s.heroes} lycan={s.progress.gabrielForm==='lycan'}/>{!b.result&&<BattleIntentV32 intent={engine.enemyIntentV32()} heroes={s.heroes} lycan={s.progress.gabrielForm==='lycan'}/>}</div><BattleScene map={s.map} battle={b} heroes={s.heroes} progress={s.progress} onArtReady={readyBattle=>engine.markBattleArtReadyV32(readyBattle.artTokenV32)}/>{!b.result&&<div className={'battle-console '+battleStyles.dock}><div className="battle-log" aria-live="polite">{b.log.slice(-2).map((text,i)=><p key={`${b.log.length}-${i}`}>{text}</p>)}</div><BattleCommands engine={engine} s={s} target={target} setTarget={setTarget}/></div>}{b.result&&<VictoryCelebration battle={b} heroes={s.heroes} lycan={s.progress.gabrielForm==='lycan'} onContinue={()=>engine.finishBattle()}/>}<UltimateCinematic battle={b} heroes={s.heroes} map={s.map} progress={s.progress}/></div>}
    {s.rewardNotice&&s.mode==='world'&&<aside className="reward-quick" role="status"><Gem size={18}/><span>{s.rewardNotice.text}</span><button className="secondary-button" onClick={()=>{const notice=s.rewardNotice!;openMenu(notice.tab,notice.focus);engine.dismissNotice();}}>Ver {({gear:'equipamento',gacha:'relíquia',skills:'habilidades',bag:'bolsa',achievements:'conquista'} as Record<string,string>)[s.rewardNotice.tab]||'recompensas'}</button><button className="notice-close" onClick={()=>engine.dismissNotice()} aria-label="Dispensar recompensa">×</button></aside>}
    {s.toast&&!s.rewardNotice&&(s.mode==='world'||s.toast.startsWith('Tela cheia indisponível'))&&<div className="game-toast" role="status"><Sparkles size={16}/>{s.toast}</div>}
   </div>
   {s.mode==='battle'?<CombatParty heroes={s.heroes} activeId={hero?.id} limits={s.progress.limit} lycan={s.progress.gabrielForm==='lycan'}/>:s.mode==='world'?<CombatParty heroes={s.heroes} limits={s.progress.limit} lycan={s.progress.gabrielForm==='lycan'} exploration leaderId={engine.leader().id} selectDisabled={s.mode!=='world'||!!panel||!!worldLoading?.loading||!!worldLoading?.error} onSelectHero={s.mode==='world'?(_id,slot)=>engine.selectPartySlot(slot):undefined} credits={s.progress.masterMode?'∞':s.credits} level={level(s.progress)} saving={s.saving} masterMode={s.progress.masterMode}/>:null}
  </section></div>
  <GameDialog container={shell.current} open={!!panel} onClose={()=>setPanel(null)} className={panel==='menu'?'menu-modal':''}><DialogHeader><DialogTitle>{panel==='menu'?'Menu de aventura':panel==='help'?'Controles e regras':panel==='bag'?'Grupo e bolsa':'Diário de Stone Reach'}</DialogTitle><DialogDescription>{panel==='menu'?`Stone Reach · ${s.heroes.map(h=>h.name).join(' e ')}`:panel==='help'?'Escolha como explorar e conduzir o grupo.':panel==='bag'?'Os recursos acompanham o grupo durante o capítulo.':'O que o selo lembra'}</DialogDescription></DialogHeader>
   {panel==='menu'&&<GameMenu key={menuTab} s={s} engine={engine} initialTab={menuTab} onTabChange={setActiveMenuTab} initialFocus={menuFocus} onReplayQuestCinematic={replayQuestScene} onPreviewFrameTest={showFrameTest} journal={<Journal s={s} engine={engine} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/>} settings={settings} onClose={()=>{engine.paused=false;setPanel(null);}} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/>}
   {panel==='journal'&&<div className="journal-modal"><Journal s={s} engine={engine} onGo={id=>{engine.paused=false;setPanel(null);engine.approach(id);}}/><button className="primary-button" onClick={()=>setPanel(null)}>Voltar à aventura</button></div>}
   {panel==='bag'&&<Tabs defaultValue="bag"><TabsList><TabsTrigger value="bag">Bolsa</TabsTrigger><TabsTrigger value="party">Grupo</TabsTrigger></TabsList><TabsContent value="bag"><div className="bag-counts"><span><Heart/> Poções <b>{s.potions}</b><small>Restaura 45 HP</small></span><span><Gem/> Elixires <b>{s.ethers}</b><small>Restaura 24 MP</small></span></div><p className="muted">Escolha quem receberá o item.</p>{s.heroes.map(h=><div className="bag-hero" key={h.id}><HeroCard h={h} lycan={s.progress.gabrielForm==='lycan'}/><div><button disabled={s.mode!=='world'||!s.potions||h.hp===h.maxHp} onClick={()=>engine.useItem('potion',h.id)}>Usar Poção</button><button disabled={s.mode!=='world'||!s.ethers||h.mp===h.maxMp} onClick={()=>engine.useItem('ether',h.id)}>Usar Elixir</button></div></div>)}{s.stage>=5&&<div className="relic"><Gem size={24}/><div><strong>Selo Ressonante</strong><p>Relíquia recuperada no subterrâneo.</p></div></div>}</TabsContent><TabsContent value="party">{s.heroes.map(h=><div className="party-detail" key={h.id}><HeroCard h={h} lycan={s.progress.gabrielForm==='lycan'}/><p>{h.role} • {h.element} • Velocidade {h.spd}</p>{SKILLS[h.id].map(sk=><p key={sk.id}><strong>{sk.name}</strong> • {sk.cost} MP<br/>{sk.description}</p>)}</div>)}</TabsContent></Tabs>}
   {panel==='help'&&<div className="help-content"><div><Keyboard/><p><strong>Teclado</strong><br/>WASD ou setas para caminhar. E interage; 1–5 escolhem o líder na exploração ou o alvo aliado na batalha. Tab passa ao próximo líder. Enter abre o menu ou avança diálogos. Esc fecha os painéis.</p></div><div><Move/><p><strong>Mouse e celular</strong><br/>Toque no cenário para caminhar. Toque em um objeto ou personagem para chegar perto e interagir. No celular, use também o direcional.</p></div><div><Shield/><p><strong>Combate por turnos</strong><br/>Observe a ordem de ação. Guarde-se contra golpes em área. Ophelia cura o alvo selecionado. Poções também recuperam aliados caídos.</p></div><div><Sparkles/><p><strong>Estados e progressão</strong><br/>Congelamento perde uma ação. Cegueira pode fazer golpes errarem. Sangramento causa 6 de dano por ação. Silêncio bloqueia magias. Guarda evita os estados dos ataques inimigos; Aurora e Antídoto removem estados. Os números ao lado dos ícones indicam ações restantes. No menu de aventura, aprenda habilidades, receba metas e equipe conjuntos em um mesmo herói.</p></div><div><Save/><p><strong>Descanso e progresso</strong><br/>Cristais restauram HP e MP. O progresso fica salvo neste navegador, sem sincronização entre dispositivos.</p></div><button className="secondary-button" onClick={()=>{engine.save();setPanel(null);}}>Salvar e voltar</button>{s.mode!=='start'&&<button className="reset-link" onClick={()=>setConfirmReset(true)}><RotateCcw size={14}/>Recomeçar este capítulo</button>}</div>}
  </GameDialog>
  <GameDialog container={shell.current} open={confirmReset} onClose={()=>setConfirmReset(false)}><DialogTitle>Recomeçar o capítulo?</DialogTitle><DialogDescription>O progresso desta versão neste navegador será substituído por uma nova aventura.</DialogDescription><div className="reset-actions"><button className="secondary-button" onClick={()=>setConfirmReset(false)}>Cancelar</button><button className="primary-button" onClick={()=>{setConfirmReset(false);setPanel(null);engine.start(false,chosen);}}>Recomeçar</button></div></GameDialog>
 </main>;
}
