'use client';
import {useEffect,useRef,useState} from 'react';
import {ASSETS,COMPANIONS,SKILL_VISUALS,SKILLS,signatureTechnique,ENEMY_ULTIMATES,ULTIMATE_NAMES,EARTH_VFX_FRAMES,combatElement,combatImpact,ELEMENT_COLORS,type Hero,type HeroId,type MapId} from '@/lib/game/data';
import type {Battle} from '@/lib/game/engine';
import {battleCrop,SPRITE_FRAMES} from '@/lib/game/sprites';
import type {Progression} from '@/lib/game/progression';
import {cosmeticOf} from '@/lib/game/cosmetics';
import {drawAura} from '@/lib/game/aura';
import {battleFormation,battleActorScale,battleCropBounds,type BattleSlot} from '@/lib/game/battleFormation';
import styles from './battle-interface.module.css';
import {characterPoseFrame,isRemadeHero} from '@/lib/game/characterAnimation';
import {drawCharacterVfx} from './character-vfx';

const artCache=new Map<string,Promise<HTMLImageElement|null>>();
export function preloadBattleArt(heroIds?:readonly HeroId[],duelHero?:HeroId){
 const selected=new Set<string>([...(heroIds||[]),...(duelHero?[duelHero]:[])]);
 const entries=Object.entries(ASSETS).filter(([key])=>{
  if(!key.startsWith('battle_')&&!key.startsWith('ultimate_')&&key!=='wolf'&&key!=='shadow')return false;
  if(!heroIds||key==='battle_fx_ava')return true;
  const character=key.match(/^battle_(?:fx_)?(seiji|ophelia|marin|gabriel|gabriel_lycan|max|beatriz|orfeu|ava|carmilla|abel)(?:_|$)/)?.[1];
  return !character||selected.has(character==='gabriel_lycan'?'gabriel':character);
 });
 return Promise.all(entries.map(async([key,src])=>{
  if(!artCache.has(src))artCache.set(src,new Promise(resolve=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>{artCache.delete(src);resolve(null);};img.src=src;}));
  return [key,await artCache.get(src)] as const;
 })).then(items=>Object.fromEntries(items.filter(([,img])=>img)) as Record<string,HTMLImageElement>);
}
const labels:Record<string,string>={'boss-ultimate':'Ruptura do Éter',attack:'Ataque',cut:'Tinta Cortante',stain:'Mancha Viva',shard:'Estilhaço Glacial',mend:'Orvalho',guard:'Guarda',potion:'Poção',ether:'Elixir de Éter',collapse:'Colapso do Véu','enemy-hit':'Golpe de Éter',blind:'Noite de Tinta',bleed:'Rasura',freeze:'Prisão Glacial',cleanse:'Aurora',remedy:'Antídoto de Luz',frozen:'Congelamento',eclipse:'Eclipse',drain:'Dreno Sombrio',darkveil:'Véu Escuro',blaze:'Chama da Forja',bulwark:'Baluarte',flamewall:'Muralha de Chamas',rupture:'Ferida da Noite',nightseal:'Selo Noturno',shadowrest:'Respiro Noturno',nova:'Erupção da Forja',ashseal:'Cinzas do Véu',rekindle:'Brasa Renovada',voltcut:'Corte de Vajra',stormguard:'Guarda de Tempestade',arc:'Arco Voltaico',tidecut:'Lâmina da Maré','umbra-seal':'Selo Umbral',margem:'Margem Serena','echo-strike':'Palma de Ruptura','echo-ward':'Guarda Nula','vine-strike':'Punho de Estratos','garden-heal':'Seiva da Terra',bound:'Prisão de Pedra','in-aeternum-vive':'IN AETERNUM VIVE'};

export function BattleScene({battle,heroes,progress,map}:{map:MapId;battle:Battle;heroes:Hero[];progress:Progression}){
 const canvas=useRef<HTMLCanvasElement>(null),live=useRef({battle,heroes,progress}),[ready,setReady]=useState(false);live.current={battle,heroes,progress};
 useEffect(()=>{let stopped=false,raf=0,lastPaint=0;const cv=canvas.current!,c=cv.getContext('2d')!;
  void preloadBattleArt(heroes.map(hero=>hero.id),battle.eventId?.startsWith('recruit-')?battle.asset as HeroId:undefined).then(art=>{if(stopped)return;setReady(live.current.heroes.every(hero=>['attack','cast','ultimate'].every(action=>!!art[`battle_${hero.id}_${action}`])));
   const draw=()=>{if(stopped)return;raf=requestAnimationFrame(draw);const now=performance.now();if(now-lastPaint<1000/30)return;lastPaint=now;const rect=cv.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio||1,2);if(cv.width!==Math.round(w*dpr)||cv.height!==Math.round(h*dpr)){cv.width=Math.round(w*dpr);cv.height=Math.round(h*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);if(!w||!h)return;
    const {battle:b,heroes:party}=live.current,a=b.animation,age=a?Date.now()-a.started:0,t=a?Math.min(1,Math.max(0,age/a.duration)):0,impact=a?age-a.impactAt:-1;
    const formation=battleFormation(w,h,party.length),pos:Record<string,BattleSlot>={enemy:formation.enemy};formation.heroes.forEach((slot,i)=>{const hero=party[i];if(hero)pos[hero.id]=slot;});
    const size=formation.heroes[0]?.height||h*.7,enemySize=formation.enemy.height;
    cv.dataset.formation=JSON.stringify(party.map(hero=>({id:hero.id,x:Math.round(pos[hero.id].x),y:Math.round(pos[hero.id].y),labelY:Math.round(pos[hero.id].labelY)})));
    const floor=c.createRadialGradient(w/2,h*.86,5,w/2,h*.86,w*.47);floor.addColorStop(0,'#789cad18');floor.addColorStop(1,'transparent');c.fillStyle=floor;c.fillRect(0,0,w,h);
    const shadow=(x:number,y:number,s:number)=>{c.fillStyle='#020d2080';c.beginPath();c.ellipse(x,y,s*.25,s*.045,0,0,Math.PI*2);c.fill();};
    const fx=(row:number,frame:number,x:number,y:number,size:number,alpha=1)=>{const img=art.battle_vfx;if(!img)return;c.save();c.globalAlpha=alpha;c.drawImage(img,frame*256,row*256,256,256,x-size/2,y-size,size,size);c.restore();};
    const duelCasting=b.eventId?.startsWith('recruit-')&&a?.actor==='enemy'&&(a.action===SKILLS[b.asset as HeroId]?.[0]?.id||b.asset==='ophelia'&&!isRemadeHero(b.asset)&&a.action==='enemy-hit'),duelUltimate=b.eventId?.startsWith('recruit-')&&a?.actor==='enemy'&&a.action.includes('ultimate'),enemyKey=`battle_${['ashwolf','moth','cinder'].includes(b.asset)?b.asset:b.boss?'boss':b.asset}_${duelUltimate?'ultimate':duelCasting?'cast':'attack'}`,enemy=art[enemyKey];if(enemy){let x=pos.enemy.x;const active=a?.actor==='enemy'&&!['frozen','bound'].includes(a.action),count=SPRITE_FRAMES[enemyKey]?.length||4,frame=active?characterPoseFrame(b.asset,duelUltimate?'ultimate':duelCasting?'cast':'attack',isRemadeHero(b.asset)&&duelUltimate?Math.max(0,age-700)/Math.max(1,(a?.duration||1)-700):t,count):0,crop=battleCrop(enemyKey,frame),idle=battleCrop(enemyKey,0),scale=battleActorScale(enemyKey,pos.enemy,!!b.eventId?.startsWith('recruit-')&&(b.asset!=='ophelia'||isRemadeHero(b.asset)));if(a?.target==='enemy'&&impact>=0&&impact<250)x+=Math.sin(impact/23)*4;if(active&&b.family==='lobo')x+=Math.sin(Math.PI*t)*Math.min(w*.025,22);shadow(x,pos.enemy.y,enemySize);c.save();if(b.eventId?.startsWith('recruit-')&&(b.asset!=='ophelia'||isRemadeHero(b.asset))){c.translate(2*x,0);c.scale(-1,1);}if(b.result==='victory')c.globalAlpha=.28;if(b.statuses.enemy?.some(s=>s.id==='freeze'))c.filter='brightness(1.35) sepia(.4) hue-rotate(150deg)';if(b.boss&&b.phase>1&&art.battle_phases){const col=b.family==='cinder'?2:b.family==='eco'?1:0,phaseSize=enemySize*(1+(b.phase-1)*.12),lunge=active?Math.sin(Math.PI*t)*w*.025:0;c.drawImage(art.battle_phases,col*512,(b.phase-2)*512,512,512,x-phaseSize*.5-lunge,pos.enemy.y-phaseSize,phaseSize,phaseSize);cv.dataset.bossPhase=String(b.phase);}else c.drawImage(enemy,crop.x,crop.y,crop.w,crop.h,x-(crop.anchorX-crop.x)*scale,pos.enemy.y-(crop.anchorY-crop.y)*scale,crop.w*scale,crop.h*scale);c.restore();if(a?.actor==='enemy'){cv.dataset.frame=`enemy:${frame}`;if(cv.dataset.enemyActionAt!==String(a.started)){cv.dataset.enemyActionAt=String(a.started);cv.dataset.enemyFrames='';}const seen=new Set((cv.dataset.enemyFrames||'').split(',').filter(Boolean));seen.add(String(frame));cv.dataset.enemyFrames=[...seen].join(',');}}
    for(const hero of party){const active=a?.actor===hero.id,casting=active&&!['attack','guard','potion','ether','remedy','frozen','bound'].includes(a.action),ultimate=active&&a.action==='ultimate',key=`battle_${hero.id==='gabriel'&&live.current.progress.gabrielForm==='lycan'?'gabriel_lycan':hero.id}_${ultimate?'ultimate':casting?'cast':'attack'}`,img=art[key];if(!img)continue;
     const frameCount=SPRITE_FRAMES[key]?.length||1,professor=false,animated=active&&!['guard','potion','ether','remedy','frozen','bound'].includes(a.action),phase=ultimate?Math.max(0,age-700)/Math.max(1,a.duration-700):t,frame=animated?Math.min(frameCount-1,characterPoseFrame(hero.id,ultimate?'ultimate':casting?'cast':'attack',phase,frameCount)):0;
     if(ultimate){cv.dataset.ultimateHero=hero.id;if(cv.dataset.ultimateStarted!==String(a.started)){cv.dataset.ultimateStarted=String(a.started);cv.dataset.ultimateFrames='';}const seen=new Set((cv.dataset.ultimateFrames||'').split(',').filter(Boolean));seen.add(String(frame));cv.dataset.ultimateFrames=[...seen].join(',');}
     if(active&&cv.dataset.frame!==`${hero.id}:${frame}`)cv.dataset.frame=`${hero.id}:${frame}`;else if(!a&&cv.dataset.frame!=='idle')cv.dataset.frame='idle';
     const p=pos[hero.id],dir=1,lunge=active&&a.action==='attack'?Math.sin(Math.PI*t)*Math.min(w*.018,p.cellWidth*.055,20):0,breathe=active?0:Math.sin(Date.now()/700+(hero.id==='seiji'?0:2))*1.5;
     shadow(p.x,p.y,size);drawAura(c,cosmeticOf(live.current.progress,hero.id),p.x,p.y,now,size/120);cv.dataset.auras=party.map(h=>live.current.progress.cosmeticEquipment[h.id]||'').join(',');c.save();if(hero.hp<=0)c.globalAlpha=.35;else if(a?.actor==='enemy'&&(a.target===hero.id||a.target==='party')&&impact>=0&&impact<280)c.globalAlpha=.55+Math.abs(Math.sin(impact/30))*.45;
     const crop=battleCrop(key,frame),flip=hero.id==='ophelia'&&!isRemadeHero(hero.id)&&!ultimate,scale=battleActorScale(key,p,flip),bounds=battleCropBounds(crop,p.x+dir*lunge,p.y+breathe,scale,flip);if(flip){c.translate(2*(p.x+lunge),0);c.scale(-1,1);}c.drawImage(img,crop.x,crop.y,crop.w,crop.h,p.x-(crop.anchorX-crop.x)*scale+dir*lunge,p.y-(crop.anchorY-crop.y)*scale+breathe,crop.w*scale,crop.h*scale);c.restore();
     cv.dataset['bounds'+hero.id]=JSON.stringify({x:Math.round(bounds.x),y:Math.round(bounds.y),width:Math.round(bounds.width),height:Math.round(bounds.height)});
    }
    for(const id of [...party.map(hero=>hero.id),'enemy']){const states=b.statuses[id]||[],p=pos[id],sz=id==='enemy'?enemySize:size;if(states.some(st=>st.id==='freeze'))fx(0,3,p.x,p.y,sz*1.13,.78);if(states.some(st=>st.id==='bind')&&art.battle_fx_ava){const crop=EARTH_VFX_FRAMES[3],s=sz*.96;c.save();c.globalAlpha=.78;c.drawImage(art.battle_fx_ava,crop.x,crop.y,crop.w,crop.h,p.x-s/2,p.y-s*.93,s,s);c.restore();}if(states.some(st=>st.id==='blind'))fx(2,3,p.x,p.y-sz*.47,sz*.6,.6);if(states.some(st=>st.id==='bleed'))fx(1,4,p.x,p.y,sz*.8,.48);}
    if(a){const origin=pos[a.actor],target=a.target==='party'?pos[party[0].id]:pos[a.target],visualHero=a.actor==='enemy'&&b.eventId?.startsWith('recruit-')?b.asset as HeroId:a.actor,element=a.element||(visualHero==='enemy'?b.family==='cinder'?'fire':'dark':combatElement(visualHero,a.action)),ink=element==='ink'||element==='dark',heal=signatureTechnique(a.action)?.target==='ally'||['mend','cleanse','shadowrest','rekindle','margem','garden-heal','echo-ward','potion','ether','remedy','bulwark','stormguard','in-aeternum-vive'].includes(a.action)||a.action==='ultimate'&&['ophelia','carmilla'].includes(visualHero),ice=element==='ice',earth=element==='earth',impactArt=combatImpact(element),ownVfx=drawCharacterVfx(c,art,visualHero,a.action,origin,target,a.target==='party'?party.filter(h=>h.hp>0&&(!a.targets||a.targets.includes(h.id))).map(h=>pos[h.id]):[],t,impact,size);
     if(!ownVfx&&impact>=0&&impactArt&&(!heal||earth)&&!['guard','frozen','bound'].includes(a.action)){
      const img=art[impactArt.asset],spots=a.target==='party'?party.filter(h=>!a.targets||a.targets.includes(h.id)).map(h=>pos[h.id]):[target],sequence=earth?(heal?[0,5]:a.action==='attack'?[0,1,2,4,5]:[0,1,2,3,4,5]):Array.from({length:impactArt.columns},(_,i)=>i),frame=sequence[Math.min(sequence.length-1,Math.floor(impact/Math.max(1,a.duration-a.impactAt)*sequence.length))];
      if(img)for(const spot of spots){const fw=img.width/impactArt.columns,fh=img.height/impactArt.rows,crop=impactArt.frames?.[frame]||{x:frame*fw,y:impactArt.row*fh,w:fw,h:fh},sz=Math.min(size*(earth&&heal?.5:a.action.includes('ultimate')?1.3:.95),Math.max(1,spot.y-12));c.save();c.globalAlpha=Math.max(0,1-impact/(a.duration-a.impactAt)*.45);c.drawImage(img,crop.x,crop.y,crop.w,crop.h,spot.x-sz/2,spot.y-sz,sz,sz);c.restore();}
     }
     const visual=SKILL_VISUALS[a.action];if(visual&&!ownVfx){const img=art[`battle_fx_${visual.hero}`];if(img){const fw=img.width/6,fh=img.height/visual.rows,phase=Math.min(5,Math.floor(t*6)),travel=Math.min(1,Math.max(0,(t-.15)/.5)),moving=visual.motion==='projectile'||visual.motion==='slash',px=moving?origin.x+(target.x-origin.x)*travel:target.x,py=moving?origin.y+(target.y-origin.y)*travel:target.y,sz=Math.min(size*(visual.motion==='veil'?1.25:visual.motion==='seal'?1.05:.9),Math.max(1,(py-12)/.95));c.save();c.globalAlpha=Math.min(1,t*5,(1-t)*5);c.drawImage(img,phase*fw,visual.row*fh,fw,fh,px-sz/2,py-sz*.95,sz,sz);c.restore();}}
     // These particles accompany the generated character frames; the map and actors remain independent assets.
     if(!ownVfx&&!earth&&!['frozen','bound'].includes(a.action)){
      c.save();const hue=ELEMENT_COLORS[element];c.strokeStyle=hue;c.fillStyle=hue;c.lineWidth=2;
      if(age<a.impactAt){const travel=Math.min(1,Math.max(0,(age-(a.action==='ultimate'?700:a.duration*.23))/(a.impactAt-(a.action==='ultimate'?700:a.duration*.23))));const x=origin.x+(target.x-origin.x)*travel,y=origin.y-size*.47+(target.y-origin.y)*travel;for(let i=0;i<10;i++){const theta=i*2.399+age/250,rad=12+i*2;c.globalAlpha=a.action==='ultimate'&&age<700?0:Math.min(1,Math.max(0,t*1.8));c.beginPath();c.arc(x+Math.cos(theta)*rad,y+Math.sin(theta)*rad,ink?2+i%3:1.5+i%2,0,Math.PI*2);c.fill();}}
      else{const out=Math.min(1,impact/(a.duration-a.impactAt));const spots=a.target==='party'?party.map(hero=>pos[hero.id]):[target];for(const spot of spots){c.globalAlpha=1-out;const radius=15+out*75;c.beginPath();c.ellipse(spot.x,spot.y-size*.3,radius,radius*.42,0,0,Math.PI*2);c.stroke();for(let i=0;i<18;i++){const angle=i*2.399,rad=(20+i*2)*(out+.25),x=spot.x+Math.cos(angle)*rad,y=spot.y-size*.45+Math.sin(angle)*rad-out*22;c.beginPath();if(ice){c.moveTo(x,y-9);c.lineTo(x+4,y+5);c.lineTo(x-4,y+5);c.closePath();}else c.arc(x,y,ink?3+i%3:2,0,Math.PI*2);c.fill();}}}
      c.restore();
     }
     if(impact>=0&&a.healing){const spot=pos[a.healing.target];drawCharacterVfx(c,art,visualHero,'return-stitch',origin,spot,[],t,impact,size);c.save();c.globalAlpha=Math.max(0,1-impact/650);c.font=`bold ${w<450?20:28}px Georgia`;c.textAlign='center';c.shadowColor='#071420';c.shadowBlur=6;c.fillStyle='#acf3cf';c.fillText(`+${a.healing.value}`,spot.x,spot.y-size*.62-impact/24);c.restore();cv.dataset.healingTarget=a.healing.target;cv.dataset.healingValue=String(a.healing.value);}
     if(impact>=0&&a.value){c.save();c.globalAlpha=Math.max(0,1-impact/650);c.font=`bold ${w<450?20:28}px Georgia`;c.textAlign='center';c.shadowColor='#071420';c.shadowBlur=6;c.fillStyle=heal?'#acf3cf':'#f2dfbb';c.fillText(`${heal||a.action==='guard'?'+':'−'}${a.value}${a.action==='ether'||a.action==='guard'?' MP':''}`,target.x,target.y-size*.62-impact/24);c.restore();}
    }
    // Labels are painted last, in their own ground lanes, clear of actor/VFX bodies.
    for(const hero of party){const p=pos[hero.id];c.save();c.font='11px Arial';c.textAlign='center';const textWidth=Math.min(p.cellWidth-8,c.measureText(hero.name).width+14);c.fillStyle='#081627db';c.fillRect(p.x-textWidth/2,p.labelY-11,textWidth,15);c.fillStyle=hero.hp<=0?'#8e9ba9':'#f4e7c9';c.fillText(hero.name,p.x,p.labelY,Math.max(1,p.cellWidth-16));c.restore();}
   };draw();
  });return()=>{stopped=true;cancelAnimationFrame(raf);};
 },[]);
 const a=battle.animation,duelHero=battle.eventId?.startsWith('recruit-')?battle.asset as HeroId:null,actionName=a?.actor==='enemy'&&duelHero?a.action.includes('ultimate')?ULTIMATE_NAMES[duelHero]:a.action==='enemy-hit'?`Ataque de ${battle.name.replace('Duelo de recrutamento · ','')}`:SKILLS[duelHero]?.find(skill=>skill.id===a.action)?.name||labels[a.action]||a.action:a?.action==='collapse'&&battle.family==='cinder'?'Pulso da Pira':a?.action.includes('ultimate')?a.actor==='enemy'?ENEMY_ULTIMATES[battle.family]?.name:ULTIMATE_NAMES[a.actor]:a?signatureTechnique(a.action)?.name||labels[a.action]||a.action:'';
 const reaction=(()=>{if(!a)return null;if(a.action==='ultimate'&&a.actor!=='enemy'){const texts:Record<string,string>={seiji:'Vai, Seiji! Faz essa tinta lembrar quem manda!',ophelia:'Estou aqui. Deixe o inverno respirar com você.',marin:'Agora sim. Mostra por que a noite teme você.',gabriel:'Sua chama encontrou o caminho.',max:'Max! A descarga é nossa!'};return {hero:a.actor,text:texts[a.actor]};}if(a.actor==='enemy'){const target=a.target==='party'?heroes[0]?.id:a.target;if(target==='ophelia'&&(battle.statuses.ophelia||[]).length)return {hero:'ophelia',text:'Respira, Ophelia. O frio ainda está do seu lado.'};if(target==='marin')return {hero:'marin',text:'Podia ter desviado dessa.'};if(target==='gabriel')return {hero:'gabriel',text:'Mesmo ferido, sua chama ainda aponta o caminho.'};if(target==='max')return {hero:'max',text:'Max, levanta. O trovão não acabou.'};}return null;})();
 return <div className={"battle-stage "+styles.stage} data-art-ready={ready} data-animation={a?`${a.actor}:${a.action}`:'idle'} style={{backgroundImage:`url(${ASSETS[['ashwood','ashpyre','vigilia'].includes(map)?'battle_bg_forest':['subsolo','camara','galeria'].includes(map)?'battle_bg_below':'battle_bg_academy']})`}}><canvas ref={canvas} role="img" aria-label={`${heroes.map(h=>h.name).join(' e ')} ${heroes.length===1?'enfrenta':'enfrentam'} ${battle.name}${a?`. ${a.actor==='enemy'?battle.name:heroes.find(h=>h.id===a.actor)?.name||a.actor} usa ${actionName}`:''}`}/>{a&&!['ultimate','boss-ultimate','enemy-ultimate'].includes(a.action)&&<div className={`battle-action-name ${a.actor==='enemy'?'enemy-action':''}`} key={a.started}>{actionName}</div>}</div>;
}
