'use client';
import {useEffect,useRef,useState} from 'react';
import {ASSETS,COMPANIONS,SKILL_VISUALS,ENEMY_ULTIMATES,type Hero,type MapId} from '@/lib/game/data';
import type {Battle} from '@/lib/game/engine';
import {battleCrop} from '@/lib/game/sprites';
import type {Progression} from '@/lib/game/progression';
import {cosmeticOf} from '@/lib/game/cosmetics';
import {drawAura} from '@/lib/game/aura';

let artPromise:Promise<Record<string,HTMLImageElement>>|undefined;
export function preloadBattleArt(){return artPromise??=Promise.all(Object.entries(ASSETS).filter(([key])=>key.startsWith('battle_')||key.startsWith('ultimate_')||key==='wolf'||key==='shadow').map(([key,src])=>new Promise<[string,HTMLImageElement|null]>(resolve=>{const img=new Image();img.onload=()=>resolve([key,img]);img.onerror=()=>resolve([key,null]);img.src=src;}))).then(items=>Object.fromEntries(items.filter(([,img])=>img)) as Record<string,HTMLImageElement>);}
const labels:Record<string,string>={'boss-ultimate':'Ruptura do Éter',attack:'Ataque',cut:'Tinta Cortante',stain:'Mancha Viva',shard:'Estilhaço Glacial',mend:'Orvalho',guard:'Guarda',potion:'Poção',ether:'Elixir de Éter',collapse:'Colapso do Véu','enemy-hit':'Golpe de Éter',blind:'Noite de Tinta',bleed:'Rasura',freeze:'Prisão Glacial',cleanse:'Aurora',remedy:'Antídoto de Luz',frozen:'Congelamento',eclipse:'Eclipse',drain:'Dreno Sombrio',darkveil:'Véu Escuro',blaze:'Chama da Forja',bulwark:'Baluarte',flamewall:'Muralha de Chamas',rupture:'Ferida da Noite',nightseal:'Selo Noturno',shadowrest:'Respiro Noturno',nova:'Erupção da Forja',ashseal:'Cinzas do Véu',rekindle:'Brasa Renovada',voltcut:'Corte de Vajra',stormguard:'Guarda de Tempestade',arc:'Arco Voltaico',tidecut:'Lâmina da Maré','umbra-seal':'Selo Umbral',margem:'Margem Serena'};

export function BattleScene({battle,heroes,progress,map}:{map:MapId;battle:Battle;heroes:Hero[];progress:Progression}){
 const canvas=useRef<HTMLCanvasElement>(null),live=useRef({battle,heroes,progress}),[ready,setReady]=useState(false);live.current={battle,heroes,progress};
 useEffect(()=>{let stopped=false,raf=0,lastPaint=0;const cv=canvas.current!,c=cv.getContext('2d')!;
  void preloadBattleArt().then(art=>{if(stopped)return;setReady(['battle_seiji_attack','battle_seiji_cast','battle_ophelia_attack','battle_ophelia_cast','wolf','shadow','battle_wolf_attack','battle_shadow_attack','battle_boss_attack','battle_seiji_ultimate','battle_ophelia_ultimate','battle_marin_ultimate','battle_gabriel_ultimate'].every(key=>!!art[key]));
   const draw=()=>{if(stopped)return;raf=requestAnimationFrame(draw);const now=performance.now();if(now-lastPaint<1000/30)return;lastPaint=now;const rect=cv.getBoundingClientRect(),w=rect.width,h=rect.height,dpr=Math.min(devicePixelRatio||1,2);if(cv.width!==Math.round(w*dpr)||cv.height!==Math.round(h*dpr)){cv.width=Math.round(w*dpr);cv.height=Math.round(h*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);if(!w||!h)return;
    const {battle:b,heroes:party}=live.current,a=b.animation,age=a?Date.now()-a.started:0,t=a?Math.min(1,Math.max(0,age/a.duration)):0,impact=a?age-a.impactAt:-1;
    const pos:Record<string,{x:number;y:number}>={enemy:{x:w*.72,y:h*.73}};const formations:Record<number,{x:number;y:number}[]>={1:[{x:.24,y:.88}],2:[{x:.15,y:.82},{x:.34,y:.90}],3:[{x:.12,y:.82},{x:.30,y:.91},{x:.20,y:.55}],4:[{x:.11,y:.83},{x:.29,y:.92},{x:.11,y:.54},{x:.30,y:.62}],5:[{x:.09,y:.84},{x:.27,y:.92},{x:.09,y:.55},{x:.27,y:.63},{x:.43,y:.82}]};(formations[Math.min(5,party.length)]||formations[5]).forEach((slot,i)=>{const hero=party[i];if(hero)pos[hero.id]={x:w*slot.x,y:h*slot.y};});
    const size=Math.min(h*1.03,w*.38,300),enemySize=Math.min(h*.88,w*.29,230);
    const floor=c.createRadialGradient(w/2,h*.86,5,w/2,h*.86,w*.47);floor.addColorStop(0,'#789cad18');floor.addColorStop(1,'transparent');c.fillStyle=floor;c.fillRect(0,0,w,h);
    const shadow=(x:number,y:number,s:number)=>{c.fillStyle='#020d2080';c.beginPath();c.ellipse(x,y,s*.25,s*.045,0,0,Math.PI*2);c.fill();};
    const fx=(row:number,frame:number,x:number,y:number,size:number,alpha=1)=>{const img=art.battle_vfx;if(!img)return;c.save();c.globalAlpha=alpha;c.drawImage(img,frame*256,row*256,256,256,x-size/2,y-size,size,size);c.restore();};
    const enemyKey=`battle_${['ashwolf','moth','cinder'].includes(b.asset)?b.asset:b.boss?'boss':b.asset}_attack`,enemy=art[enemyKey];if(enemy){let x=pos.enemy.x;const active=a?.actor==='enemy'&&a.action!=='frozen',frame=active?Math.min(3,Math.floor(t*4)):0,crop=battleCrop(enemyKey,frame),idle=battleCrop(enemyKey,0),scale=enemySize/(idle.anchorY-idle.y-16);if(a?.target==='enemy'&&impact>=0&&impact<250)x+=Math.sin(impact/23)*4;if(active&&b.family==='lobo')x+=Math.sin(Math.PI*t)*w*.04;shadow(x,pos.enemy.y,enemySize);c.save();if(b.result==='victory')c.globalAlpha=.28;if(b.statuses.enemy?.some(s=>s.id==='freeze'))c.filter='brightness(1.35) sepia(.4) hue-rotate(150deg)';if(b.boss&&b.phase>1&&art.battle_phases){const col=b.family==='cinder'?2:b.family==='eco'?1:0,phaseSize=enemySize*(1+(b.phase-1)*.12),lunge=active?Math.sin(Math.PI*t)*w*.025:0;c.drawImage(art.battle_phases,col*512,(b.phase-2)*512,512,512,x-phaseSize*.5-lunge,pos.enemy.y-phaseSize,phaseSize,phaseSize);cv.dataset.bossPhase=String(b.phase);}else c.drawImage(enemy,crop.x,crop.y,crop.w,crop.h,x-(crop.anchorX-crop.x)*scale,pos.enemy.y-(crop.anchorY-crop.y)*scale,crop.w*scale,crop.h*scale);c.restore();if(a?.actor==='enemy'){cv.dataset.frame=`enemy:${frame}`;if(cv.dataset.enemyActionAt!==String(a.started)){cv.dataset.enemyActionAt=String(a.started);cv.dataset.enemyFrames='';}const seen=new Set((cv.dataset.enemyFrames||'').split(',').filter(Boolean));seen.add(String(frame));cv.dataset.enemyFrames=[...seen].join(',');}}
    for(const hero of party){const active=a?.actor===hero.id,casting=active&&(['rupture','nightseal','shadowrest','nova','ashseal','rekindle','ultimate','eclipse','drain','blaze','darkveil','flamewall','bulwark','cut','stain','shard','mend','blind','bleed','freeze','cleanse','voltcut','stormguard','arc','tidecut','umbra-seal','margem'].includes(a.action)||hero.id==='ophelia'&&a.action==='attack'),ultimate=active&&a.action==='ultimate',key=`battle_${hero.id==='gabriel'&&live.current.progress.gabrielForm==='lycan'?'gabriel_lycan':hero.id}_${ultimate?'ultimate':casting?'cast':'attack'}`,img=art[key];if(!img)continue;
     const step=Math.min(5,Math.floor(t*6));const frame=hero.id==='beatriz'?active?Math.min(2,Math.floor(t*3)):0:ultimate?Math.min(7,Math.floor(Math.max(0,age-700)/(a.duration-700)*8)):active&&['attack','rupture','nightseal','shadowrest','nova','ashseal','rekindle','ultimate','eclipse','drain','blaze','darkveil','flamewall','bulwark','cut','stain','shard','mend','blind','bleed','freeze','cleanse','voltcut','stormguard','arc'].includes(a.action)?['mend','cleanse','shadowrest','rekindle','stormguard'].includes(a.action)?[0,1,2,5,5,0][step]:step:0;
     if(ultimate){cv.dataset.ultimateHero=hero.id;if(cv.dataset.ultimateStarted!==String(a.started)){cv.dataset.ultimateStarted=String(a.started);cv.dataset.ultimateFrames='';}const seen=new Set((cv.dataset.ultimateFrames||'').split(',').filter(Boolean));seen.add(String(frame));cv.dataset.ultimateFrames=[...seen].join(',');}
     if(active&&cv.dataset.frame!==`${hero.id}:${frame}`)cv.dataset.frame=`${hero.id}:${frame}`;else if(!a&&cv.dataset.frame!=='idle')cv.dataset.frame='idle';
     const p=pos[hero.id],dir=1,lunge=active&&a.action==='attack'?Math.sin(Math.PI*t)*w*.07:0,breathe=active?0:Math.sin(Date.now()/700+(hero.id==='seiji'?0:2))*1.5;
     shadow(p.x,p.y,size);drawAura(c,cosmeticOf(live.current.progress,hero.id),p.x,p.y,now,size/120);cv.dataset.auras=party.map(h=>live.current.progress.cosmeticEquipment[h.id]||'').join(',');c.save();if(hero.hp<=0)c.globalAlpha=.35;else if(a?.actor==='enemy'&&(a.target===hero.id||a.target==='party')&&impact>=0&&impact<280)c.globalAlpha=.55+Math.abs(Math.sin(impact/30))*.45;
     const crop=battleCrop(key,frame),idle=battleCrop(`battle_${hero.id==='gabriel'&&live.current.progress.gabrielForm==='lycan'?'gabriel_lycan':hero.id}_attack`,0),reference=battleCrop(key,0),source=hero.id==='gabriel'&&live.current.progress.gabrielForm==='lycan'?'gabriel_lycan':hero.id,scale=source==='beatriz'?size*.70/(reference.anchorY-reference.y):ultimate||source==='gabriel_lycan'?size*.94/(reference.anchorY-reference.y):source==='max'?size*.76/(reference.anchorY-reference.y):size/512*(idle.anchorY-idle.y)/(reference.anchorY-reference.y);if(hero.id==='ophelia'&&!ultimate){c.translate(2*(p.x+lunge),0);c.scale(-1,1);cv.dataset.opheliaFacing='enemy';}c.drawImage(img,crop.x,crop.y,crop.w,crop.h,p.x-(crop.anchorX-crop.x)*scale+dir*lunge,p.y-(crop.anchorY-crop.y)*scale+breathe,crop.w*scale,crop.h*scale);c.restore();
     c.font='12px Arial';c.textAlign='center';c.fillStyle=hero.hp<=0?'#8e9ba9':'#d8dee1';c.fillText(hero.name,p.x,h-3);
    }
    for(const id of [...party.map(hero=>hero.id),'enemy']){const states=b.statuses[id]||[],p=pos[id],sz=id==='enemy'?enemySize:size;if(states.some(st=>st.id==='freeze'))fx(0,3,p.x,p.y,sz*1.13,.78);if(states.some(st=>st.id==='blind'))fx(2,3,p.x,p.y-sz*.47,sz*.6,.6);if(states.some(st=>st.id==='bleed'))fx(1,4,p.x,p.y,sz*.8,.48);}
    if(a){const origin=pos[a.actor],target=a.target==='party'?pos[party[0].id]:pos[a.target],ink=['cut','stain','blind','bleed','eclipse','drain','darkveil','rupture','nightseal','umbra-seal'].includes(a.action)||a.action==='ultimate'&&['seiji','marin'].includes(a.actor),heal=['mend','cleanse','shadowrest','rekindle','margem','potion','ether','remedy','bulwark'].includes(a.action)||a.action==='ultimate'&&a.actor==='ophelia',ice=['shard','freeze','frozen','tidecut'].includes(a.action)||['ophelia','beatriz'].includes(a.actor)&&a.action==='attack'||a.action==='ultimate'&&['ophelia','beatriz'].includes(a.actor),lightning=a.actor==='max'||['voltcut','stormguard'].includes(a.action),enemyAction=a.actor==='enemy';
     if(impact>=0){const spots=a.target==='party'?party.map(h=>pos[h.id]):[target],row=ice?0:enemyAction?b.family==='cinder'?3:2:a.actor==='seiji'?1:a.actor==='marin'?2:3,frame=Math.min(5,Math.floor(impact/Math.max(1,a.duration-a.impactAt)*6));for(const spot of spots)fx(row,frame,spot.x,spot.y,size*(a.action.includes('ultimate')?1.3:.95),Math.max(0,1-impact/(a.duration-a.impactAt)*.45));}
     const visual=SKILL_VISUALS[a.action];if(visual){const img=art[`battle_fx_${visual.hero}`];if(img){const fw=img.width/6,fh=img.height/visual.rows,phase=Math.min(5,Math.floor(t*6)),travel=Math.min(1,Math.max(0,(t-.15)/.5)),moving=visual.motion==='projectile'||visual.motion==='slash',px=moving?origin.x+(target.x-origin.x)*travel:target.x,py=moving?origin.y+(target.y-origin.y)*travel:target.y,sz=size*(visual.motion==='veil'?1.25:visual.motion==='seal'?1.05:.9);c.save();c.globalAlpha=Math.min(1,t*5,(1-t)*5);c.drawImage(img,phase*fw,visual.row*fh,fw,fh,px-sz/2,py-sz*.95,sz,sz);c.restore();cv.dataset.skillVisual=`${visual.hero}:${visual.row}:${visual.motion}`;}}
     if(a.actor==='beatriz'&&['attack','tidecut','umbra-seal','margem','ultimate'].includes(a.action)&&art.battle_fx_beatriz){const img=art.battle_fx_beatriz,fxFrame=Math.min(2,Math.floor(t*3)),row=['umbra-seal','ultimate'].includes(a.action)?1:0,spot=a.target==='party'?pos[party[0].id]:target,sz=size*(a.action==='ultimate'?1.05:.68);c.save();c.globalAlpha=Math.min(.85,t*5,(1-t)*5);c.drawImage(img,fxFrame*img.width/3,row*img.height/2,img.width/3,img.height/2,spot.x-sz/2,spot.y-sz*.88,sz,sz);c.restore();cv.dataset.skillVisual=`beatriz:${row}:${fxFrame}`;}
     // These particles accompany the generated character frames; the map and actors remain independent assets.
     if(a.action==='ultimate'||ink||ice||heal||lightning||['blaze','flamewall','nova','ashseal'].includes(a.action)||enemyAction||a.action==='guard'){
      c.save();const hue=lightning?'#a9e8ff':enemyAction&&b.family==='cinder'?'#ff9955':['blaze','flamewall','nova','ashseal'].includes(a.action)||a.action==='ultimate'&&a.actor==='gabriel'?'#ff9354':a.action==='ultimate'&&a.actor==='marin'?'#b673ff':ink?'#344b73':heal?'#99efd9':ice?'#b4edff':a.action==='guard'?'#e9cc93':'#b897ee';c.strokeStyle=hue;c.fillStyle=hue;c.lineWidth=2;
      if(age<a.impactAt){const travel=Math.min(1,Math.max(0,(age-(a.action==='ultimate'?700:a.duration*.23))/(a.impactAt-(a.action==='ultimate'?700:a.duration*.23))));const x=origin.x+(target.x-origin.x)*travel,y=origin.y-size*.47+(target.y-origin.y)*travel;for(let i=0;i<10;i++){const theta=i*2.399+age/250,rad=12+i*2;c.globalAlpha=a.action==='ultimate'&&age<700?0:Math.min(1,Math.max(0,t*1.8));c.beginPath();c.arc(x+Math.cos(theta)*rad,y+Math.sin(theta)*rad,ink?2+i%3:1.5+i%2,0,Math.PI*2);c.fill();}}
      else{const out=Math.min(1,impact/(a.duration-a.impactAt));const spots=a.target==='party'?party.map(hero=>pos[hero.id]):[target];for(const spot of spots){c.globalAlpha=1-out;const radius=15+out*75;c.beginPath();c.ellipse(spot.x,spot.y-size*.3,radius,radius*.42,0,0,Math.PI*2);c.stroke();for(let i=0;i<18;i++){const angle=i*2.399,rad=(20+i*2)*(out+.25),x=spot.x+Math.cos(angle)*rad,y=spot.y-size*.45+Math.sin(angle)*rad-out*22;c.beginPath();if(ice){c.moveTo(x,y-9);c.lineTo(x+4,y+5);c.lineTo(x-4,y+5);c.closePath();}else c.arc(x,y,ink?3+i%3:2,0,Math.PI*2);c.fill();}}}
      c.restore();
     }
     if(impact>=0&&a.value){c.save();c.globalAlpha=Math.max(0,1-impact/650);c.font=`bold ${w<450?20:28}px Georgia`;c.textAlign='center';c.shadowColor='#071420';c.shadowBlur=6;c.fillStyle=heal?'#acf3cf':'#f2dfbb';c.fillText(`${heal||a.action==='guard'?'+':'−'}${a.value}${a.action==='ether'||a.action==='guard'?' MP':''}`,target.x,target.y-size*.62-impact/24);c.restore();}
    }
   };draw();
  });return()=>{stopped=true;cancelAnimationFrame(raf);};
 },[]);
 const a=battle.animation;
 const reaction=(()=>{if(!a)return null;if(a.action==='ultimate'&&a.actor!=='enemy'){const texts:Record<string,string>={seiji:'Vai, Seiji! Faz essa tinta lembrar quem manda!',ophelia:'Estou aqui. Deixe o inverno respirar com você.',marin:'Agora sim. Mostra por que a noite teme você.',gabriel:'Sua chama encontrou o caminho.',max:'Max! A descarga é nossa!'};return {hero:a.actor,text:texts[a.actor]};}if(a.actor==='enemy'){const target=a.target==='party'?heroes[0]?.id:a.target;if(target==='ophelia'&&(battle.statuses.ophelia||[]).length)return {hero:'ophelia',text:'Respira, Ophelia. O frio ainda está do seu lado.'};if(target==='marin')return {hero:'marin',text:'Podia ter desviado dessa.'};if(target==='gabriel')return {hero:'gabriel',text:'Mesmo ferido, sua chama ainda aponta o caminho.'};if(target==='max')return {hero:'max',text:'Max, levanta. O trovão não acabou.'};}return null;})();
 return <div className="battle-stage" data-art-ready={ready} data-animation={a?`${a.actor}:${a.action}`:'idle'} style={{backgroundImage:`url(${ASSETS[['ashwood','ashpyre','vigilia'].includes(map)?'battle_bg_forest':['subsolo','camara','galeria'].includes(map)?'battle_bg_below':'battle_bg_academy']})`}}><canvas ref={canvas} role="img" aria-label={`${heroes.map(h=>h.name).join(' e ')} enfrentam ${battle.name}${a?`. ${a.actor==='enemy'?battle.name:heroes.find(h=>h.id===a.actor)?.name||a.actor} usa ${a.action==='collapse'&&battle.family==='cinder'?'Pulso da Pira':a.action.includes('ultimate')?ENEMY_ULTIMATES[battle.family]?.name:labels[a.action]||a.action}`:''}`}/>{a&&!['ultimate','boss-ultimate','enemy-ultimate'].includes(a.action)&&<div className={`battle-action-name ${a.actor==='enemy'?'enemy-action':''}`} key={a.started}>{a.action==='collapse'&&battle.family==='cinder'?'Pulso da Pira':a.action.includes('ultimate')?ENEMY_ULTIMATES[battle.family]?.name:labels[a.action]||a.action}</div>}</div>;
}
