'use client';
import {useState,useEffect} from 'react';
import type {Snapshot,GameEngine} from '@/lib/game/engine';
import {ASSETS,MAPS,type HeroId} from '@/lib/game/data';
import {ANCHORS,EVENTS,TREE,gearById} from '@/lib/game/progression';
import {COSMETICS,RARITIES,cosmeticById,cosmeticOf} from '@/lib/game/cosmetics';
import {RelicIcon,GachaAnimation} from './relic-art';
import {GameIcon} from './game-icon';
import {SUMMONED_HEROES,summonedById} from '@/lib/game/summons';
import {HeroCard} from './hero-card';
import {isHeroCardId} from '@/lib/game/heroCardArt';

export function SummonMenu({s,engine,initialFocus,onClose}:{s:Snapshot;engine:GameEngine;initialFocus?:string;onClose:()=>void}){
 const [detail,setDetail]=useState(initialFocus||s.progress.lastSummon||'');const [expanded,setExpanded]=useState<string|null>(null);const p=s.progress,chosen=summonedById(detail),world=s.mode==='world';
 useEffect(()=>{if(p.lastSummon)setDetail(p.lastSummon);},[p.lastSummon]);
 const pull=(count:1|10,method:'ticket'|'crystal')=>engine.drawCharacter(count,method);
 return <><div className="menu-intro"><span className="eyebrow">CONVOCAÇÃO DO ÉTER</span><h3>Arquivo dos Despertos</h3><p>O círculo chama heróis 4★ e 5★. Beatriz entra no Grupo ao ser invocada; Orfeu e Ava concluem suas aulas de vínculo. O MAIL oferece 30 tiros e um seletor 5★ jogável. Carmilla é uma recompensa de conquistas ou do Modo Mestre, fora do sorteio.</p></div>
 <div className="echo-resources"><span><GameIcon index={15}/><b>{p.masterMode?'∞':p.crystals}</b> Cristais de Éter</span><span><GameIcon index={6}/><b>{p.masterMode?'∞':p.tokens}</b> Fichas de Invocação</span><span><GameIcon index={1}/><b>{p.soulFragments}</b> Fragmentos de Alma</span></div>
 <div className="summon-circle"><div className={`summon-sigil ${s.summonBusy?'revealing':''}`}><i/><i/><i/><i/><b>ÉTER</b></div><div className="summon-copy">{chosen?<>{chosen.art&&<img className="summon-feature-art" src={chosen.art} alt={`Arte de ${chosen.name}`}/>}<small style={{color:chosen.accent}}>{chosen.rarity}★ · {chosen.element}</small><h3>{chosen.name}</h3><p>{chosen.title}</p><small>{detail===p.lastSummon?(p.lastSummonDuplicate?'Duplicata: +Fragmentos de Alma, Cristais e 1 constelação.':'Convocação registrada no Arquivo.'):(p.summoned.includes(chosen.id)?chosen.achievementOnly?'Disponível no Grupo.':'Na Lista de Espera.':chosen.achievementOnly?'Complete todas as conquistas ou ative o Modo Mestre.':'Ainda não convocado.')}</small></>:<><h3>O círculo aguarda.</h3><p>1 giro custa 160 Cristais ou 1 Ficha. O multi de 10 custa 1.600 Cristais e garante 4★ ou superior.</p></>}</div>{s.summonBusy&&<GachaAnimation/>}<div className="gacha-pulls"><button className="primary-button" disabled={!world||s.summonBusy||(!p.masterMode&&p.crystals<160&&p.tokens<1)} onClick={()=>pull(1,p.masterMode?'crystal':p.tokens?'ticket':'crystal')}>Invocar ×1</button><button className="secondary-button" disabled={!world||s.summonBusy||!p.masterMode&&p.crystals<1600} onClick={()=>pull(10,'crystal')}>Invocar ×10 · {p.masterMode?'grátis':'1.600 Cristais'}</button></div><small>4★ garantido em até {10-p.fourPity} giros · 5★ garantido em até {80-p.fivePity} · soft pity a partir do 65º.</small></div>
 {s.summonResults.length>0&&<div className="summon-results" aria-live="polite">{s.summonResults.map((result,i)=>{const hero=summonedById(result.id),gear=gearById(result.id);return <button key={`${result.id}-${i}`} onClick={()=>hero&&setDetail(result.id)} className={`rarity-${result.rarity}`}>{hero?<><b>{hero.rarity}★</b><span>{hero.name}</span></>:<><b>3★</b><span>{gear?.name||'Equipamento'}</span></>}<small>{hero?result.duplicate?'Duplicata → fragmentos':'Lista de Espera':result.duplicate?'Outra peça':'Bolsa · Equipamentos'}</small></button>;})}</div>}
 <details className="gacha-rules"><summary>Regras do banner</summary><div className="rarity-odds"><span>3★ <b>78%</b></span><span>4★ <b>20%</b></span><span>5★ <b>2%</b></span></div><p>Uma duplicata concede Fragmentos de Alma, Cristais e uma constelação (até 6). Carmilla não integra a roleta: complete todas as conquistas ou ative o Modo Mestre. Auras cosméticas permanecem no Relicário abaixo.</p></details>
 <h3 className="menu-subheading">Lista de Espera · {p.summoned.length}/{SUMMONED_HEROES.length}</h3>
 <div className="menu-grid summon-roster">{SUMMONED_HEROES.map(hero=>{
  const owned=p.summoned.includes(hero.id),bonded=p.bonded.includes(hero.id),opened=expanded===hero.id,cardId=hero.hero||hero.id;
  const destination=hero.id==='orfeu'?'arquivo':hero.id==='ava'?'domo':'patio';
  const place=destination==='arquivo'?'Arquivo Central':destination==='domo'?'Domo de Herbologia':'Pátio Central';
  return <article className={`summon-card ${owned?'owned':'unowned'} ${opened?'expanded':''}`} key={hero.id} style={{'--summon-accent':hero.accent} as React.CSSProperties}>
   <div className="summon-card-stage">
    <img className="summon-character-art" src={hero.art||ASSETS[`dlg_${cardId}`]} alt="" loading="lazy"/>
    {isHeroCardId(cardId)&&<HeroCard className="summon-character-card" h={{id:cardId,name:hero.name,element:hero.element,portrait:hero.art}} showVitals={false} detail={`${hero.rarity}★ · ${hero.role}`}/>}
    <div className="summon-card-detail" aria-hidden={!opened}><p>{hero.description}</p><strong>{hero.ultimate}</strong><small>Constelação {p.constellations[hero.id]||0}/6</small></div>
   </div>
   <div className="summon-card-actions">
    <button className="summon-inspect" aria-expanded={opened} aria-label={`${opened?'Ocultar':'Mostrar'} detalhes de ${hero.name}`} onClick={()=>{setDetail(hero.id);setExpanded(opened?null:hero.id);}}>{opened?'Voltar à arte':'Detalhes'}</button>
    {owned?<button className="secondary-button" disabled={!world||bonded||s.map!==destination} onClick={()=>{onClose();engine.bondSummoned(hero.id);}}>{bonded?hero.id==='carmilla'?'Disponível no Grupo':'Vínculo concluído':s.map===destination?'Iniciar Aula de Vínculo':`Vá ao ${place}`}</button>:<span className="summon-locked">{hero.achievementOnly?'Conquistas / Modo Mestre':'Ainda não convocado'}</span>}
   </div>
  </article>;
 })}</div><h3 className="menu-subheading">Relicário de auras</h3><CosmeticMenu s={s} engine={engine} initialFocus={initialFocus}/></>;
}

export function CosmeticMenu({s,engine,initialFocus}:{s:Snapshot;engine:GameEngine;initialFocus?:string}){
 const [detail,setDetail]=useState(initialFocus||'');useEffect(()=>{if(detail){engine.ackCosmetic(detail);document.querySelector('.relic-detail')?.scrollIntoView({block:'nearest'});}},[detail,engine]);
 const [hero,setHero]=useState<HeroId>(s.heroes[0].id),[filter,setFilter]=useState('all');const p=s.progress,last=cosmeticById(p.lastDraw),equipped=cosmeticOf(p,hero),world=s.mode==='world';
 return <><div className="menu-intro"><span className="eyebrow">ECOS DE STONE REACH</span><h3>Relicário de auras</h3><p>50 cosméticos com partículas e um pequeno efeito em combate. Equipe uma aura em cada herói; uma mesma peça só pode pertencer a um deles.</p></div>
 <div className="echo-resources"><span><GameIcon index={15}/><b>{p.masterMode?'∞':p.tokens}</b> Fichas de Eco</span><span><GameIcon index={6}/><b>{p.dust}</b> Fragmentos</span><span>{p.cosmetics.length}/50 na coleção</span></div>
 <div className="gacha-panel"><div className={`gacha-result ${s.gachaBusy?'revealing':''}`} key={`${p.rolls}-${p.lastDraw}`} aria-live="polite" style={last?{'--aura-color':last.color,'--rarity-color':last.rarity.color} as React.CSSProperties:undefined}>{last?<><div className="aura-preview"><RelicIcon id={last.id}/>{Array.from({length:last.rank+2},(_,i)=><i key={i} style={{transform:`rotate(${i*360/(last.rank+2)}deg) translateY(-43px)`}}/>)}</div><span className="eyebrow">{last.rarity.name}</span><h4>{last.name}</h4><p>{last.description}</p><small>{p.lastDuplicate?`Duplicata convertida em ${last.rank} fragmento${last.rank>1?'s':''}.`:'Aura adicionada à coleção.'}</small></>:<><div className="aura-preview"><GameIcon index={15}/></div><h4>Qual memória responderá?</h4><p>Use uma ficha para revelar uma aura.</p></>}</div>
 {s.gachaBusy&&<GachaAnimation/>}<div className="gacha-pulls">{([5,10] as const).map(count=><button className="secondary-button" key={count} disabled={!world||s.gachaBusy||!p.masterMode&&p.tokens<count} onClick={()=>engine.drawCosmetics(count)}>Invocar ×{count} · {p.masterMode?'grátis':`${count} fichas`}</button>)}</div><button className="primary-button" disabled={!world||s.gachaBusy||!p.masterMode&&p.tokens<1} onClick={()=>engine.drawCosmetic()}>{s.gachaBusy?'Revelando…':!p.masterMode&&p.tokens<1?'Ganhe mais fichas':p.masterMode?'Invocar · grátis':'Invocar · 1 Ficha de Eco'}</button><small>Épica ou lendária em até {10-p.pity} invocações.</small></div>
 {!s.gachaBusy&&s.gachaResults.length>1&&<div className="gacha-batch" aria-label="Resultados da invocação">{s.gachaResults.map((result,i)=><button key={i} onClick={()=>setDetail(result.id)}><RelicIcon id={result.id}/><small>{cosmeticById(result.id)?.name}</small><b>{result.duplicate?'Duplicata → fragmentos':'Nova aura'}</b></button>)}</div>}
 {cosmeticById(detail)&&<article className="relic-detail inventory-focus"><RelicIcon id={detail}/><div><h3>{cosmeticById(detail)!.name}</h3><p>{cosmeticById(detail)!.rarity.name} · {cosmeticById(detail)!.description}</p><small>{p.cosmetics.includes(detail)?'Obtida na coleção':'Ainda não obtida'}</small>{p.cosmetics.includes(detail)&&<button className="secondary-button" disabled={!world||equipped?.id===detail} onClick={()=>engine.equipCosmetic(hero,detail)}>{equipped?.id===detail?'Equipada':`Equipar em ${s.heroes.find(h=>h.id===hero)?.name}`}</button>}</div><button className="text-button" onClick={()=>setDetail('')}>Fechar detalhe</button></article>}
 <details className="gacha-rules"><summary>Chances e como obter fichas</summary><p>Comece com 3 fichas. Missões concedem 1, chefes 3 e cada 3 vitórias comuns concedem 1. Eventos têm recompensas próprias. Todas as fichas são obtidas jogando.</p><div className="rarity-odds">{RARITIES.map(r=><span key={r.id} style={{color:r.color}}>{r.name} <b>{r.weight}%</b></span>)}</div><p>As 10 famílias têm a mesma chance dentro de cada raridade. A décima invocação sem uma épica garante uma épica ou lendária (94% / 6%). Uma épica ou lendária reinicia a contagem. Duplicatas dão 1 a 5 fragmentos; crie qualquer aura ainda ausente com 8 a 40 fragmentos.</p></details>
 <div className="hero-switch" aria-label="Herói da aura">{s.heroes.map(h=><button className={hero===h.id?'selected':''} key={h.id} onClick={()=>setHero(h.id)}><img src={ASSETS[`dlg_${h.id}`]} alt=""/><span>{h.name}<small>{cosmeticOf(p,h.id)?.name||'Sem aura'}</small></span></button>)}</div>
 {equipped&&<div className="equipped-aura"><RelicIcon id={equipped.id}/><span><strong>{equipped.name}</strong><small>{equipped.description}</small></span><button className="text-button" onClick={()=>engine.equipCosmetic(hero)} disabled={!world}>Retirar aura</button></div>}
 <div className="cosmetic-filters" aria-label="Filtrar auras">{[['all','Todas'],['owned','Obtidas'],...RARITIES.map(r=>[r.id,r.name])].map(([id,name])=><button key={id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{name}</button>)}</div>
 <button className="primary-button auto-equip" disabled={!world||!p.cosmetics.length} onClick={()=>engine.autoEquipAura(hero)}>Autoequipar aura · maior raridade disponível</button><div className="menu-grid cosmetic-collection">{COSMETICS.filter(c=>filter==='all'||filter==='owned'&&p.cosmetics.includes(c.id)||c.rarity.id===filter).map(c=>{const owned=p.cosmetics.includes(c.id),worn=s.heroes.find(h=>p.cosmeticEquipment[h.id]===c.id);return <article key={c.id} className={`menu-card cosmetic-card ${owned?'owned':'unowned'}`} style={{'--rarity-color':c.rarity.color,'--aura-color':c.color} as React.CSSProperties}><button className="relic-inspect" onClick={()=>setDetail(c.id)} aria-label={`Ver ${c.name}`}><RelicIcon id={c.id}/>{p.unseenCosmetics.includes(c.id)&&<b>NOVA</b>}</button><small className="rarity-label">{c.rarity.name} · {Array(c.rank).fill('✦').join('')}</small><h4>{c.name}</h4><p>{c.description}</p>{owned?<button className="secondary-button" disabled={!world||worn?.id===hero} onClick={()=>engine.equipCosmetic(hero,c.id)}>{worn?.id===hero?'Equipada':worn?`Transferir de ${worn.name}`:`Equipar em ${s.heroes.find(h=>h.id===hero)?.name||hero}`}</button>:<button className="secondary-button" disabled={!world||p.dust<c.craftCost} onClick={()=>engine.craftCosmetic(c.id)}>Criar · {c.craftCost} fragmentos</button>}</article>;})}</div>
 </>;
}

export function EventMenu({s,engine,onGo,onClose}:{s:Snapshot;engine:GameEngine;onGo:(id:string)=>void;onClose:()=>void}){
 return <><div className="menu-intro"><h3>Ecos pelo caminho</h3><p>Encontre o evento no cenário para agir. Cada evento concede sua recompensa uma vez.</p></div><div className="menu-grid">{EVENTS.map(event=>{const done=s.progress.events.includes(event.id),here=s.map===event.map,entity=engine.activeEntities().find(e=>e.id===event.entityId),near=!!entity&&Math.hypot(s.position.x-entity.x,s.position.y-entity.y)<=2.4,battle=event.type==='battle',learned=battle||s.progress.learned.includes(event.node),hero=s.heroes.find(h=>h.id===event.hero)!,cost=battle?0:engine.skillCost(event.hero,event.cost);return <article className={`menu-card event-card ${done?'claimed':''}`} key={event.id}><GameIcon index={battle?6:event.type==='ice'?7:1}/><small>{MAPS[event.map].name}</small><h4>{event.name}</h4><p>{event.description}</p><small>+{event.tokens} fichas · +{event.xp} XP · +{event.credits} créditos</small>{!battle&&<small>{TREE.find(n=>n.id===event.node)?.name} · {cost} MP</small>}<p className="event-state">{done?'Evento concluído':!here?'Procure o evento neste local.':!learned?'Aprenda a técnica de exploração na árvore.':!near?'Caminhe até o evento.':'Evento ao alcance.'}</p><button className="primary-button" disabled={s.mode!=='world'||done||!near||!learned||!battle&&(hero.hp<=0||hero.mp<cost)} onClick={()=>{if(engine.resolveEvent(event.id))onClose();}}>{done?'Concluído':battle?'Enfrentar a Sombra':'Usar técnica'}</button>{here&&!done&&!near&&entity&&<button className="text-button" onClick={()=>onGo(event.entityId)}>Caminhar até o evento</button>}</article>;})}</div></>;
}

export function TravelMenu({s,engine,onGo,onClose}:{s:Snapshot;engine:GameEngine;onGo:(id:string)=>void;onClose:()=>void}){
 const current=engine.currentAnchor();return <div className="travel-menu"><h3 className="menu-subheading">Marcos de Éter · {s.progress.anchors.length}/3</h3><p className="menu-note">Você pode viajar de qualquer área segura; em áreas hostis, fique perto de um marco ativado. São três pontos raros; encontre e use o cristal de cada um para conectá-los.</p><div className="menu-grid">{ANCHORS.map(a=>{const known=s.progress.anchors.includes(a.id),here=a.map===s.map;return <article className="menu-card travel-card" key={a.id}><GameIcon index={5}/><h4>{a.name}</h4><p>{MAPS[a.map].name}</p><small>{known?here?current?.id===a.id?'Você está neste marco.':MAPS[s.map].safe?'Ativado · viagem disponível nesta área segura.':'Ativado · aproxime-se para viajar.':'Destino ativado.':a.map==='galeria'&&s.stage<5?'Após o capítulo · ainda não encontrado.':'Encontre e ative este cristal.'}</small>{here?<button className="secondary-button" disabled={s.mode!=='world'||current?.id===a.id} onClick={()=>onGo(a.entityId)}>{known?'Caminhar até o marco':'Ativar o marco'}</button>:<button className="primary-button" disabled={s.mode!=='world'||!(MAPS[s.map].safe||current)||!known||a.map==='galeria'&&s.stage<5} onClick={()=>{if(engine.fastTravel(a.id))onClose();}}>Viajar para {a.id==='academia'?'Academia':a.id==='cais'?'Cais':'Galeria'}</button>}</article>;})}</div></div>;
}
