'use client';
import {useEffect,useRef} from 'react';
import {ASSETS,COMPANIONS,ENEMY_ULTIMATES,type Hero,type MapId} from '@/lib/game/data';
import type {Battle} from '@/lib/game/engine';
import type {Progression} from '@/lib/game/progression';
import {battleCrop} from '@/lib/game/sprites';
import {preloadBattleArt} from './battle-scene';

export function UltimateCinematic({battle,heroes,map,progress}:{battle:Battle;heroes:Hero[];map:MapId;progress:Progression}){
 const cv=useRef<HTMLCanvasElement>(null),live=useRef(battle);live.current=battle;
 const a=battle.animation,enabled=!!a&&['ultimate','boss-ultimate','enemy-ultimate'].includes(a.action),actor=a?.actor,hero=heroes.find(h=>h.id===actor),name=actor==='enemy'?ENEMY_ULTIMATES[battle.family]?.name:({seiji:'Códice Sem Fundo',ophelia:'Inverno Sereno',marin:'Hora Sem Estrelas',gabriel:'Coração da Forja',max:'Trono da Tempestade',beatriz:'Maré Umbral',orfeu:'Primeiro Som',ava:'Jardim Indomável'} as Record<string,string>)[actor||''];
 useEffect(()=>{if(!enabled||!a)return;let stop=false,raf=0,last=0;const canvas=cv.current!,ctx=canvas.getContext('2d')!,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 void preloadBattleArt().then(art=>{if(stop)return;const draw=()=>{if(stop)return;raf=requestAnimationFrame(draw);const now=Date.now();if(now-last<33)return;last=now;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const age=now-a.started,t=Math.min(1,Math.max(0,age/a.duration)),beat=age<900?'focus':age<1800?'charge':age<a.impactAt?'release':'impact';canvas.dataset.cameraBeat=beat;canvas.dataset.ultimateActor=a.actor;
 const heroKey=a.actor==='gabriel'&&progress.gabrielForm==='lycan'?'gabriel_lycan':a.actor,key=a.actor==='enemy'?`ultimate_${battle.family}`:`battle_${heroKey}_ultimate`,img=art[key];ctx.clearRect(0,0,w,h);const hue=a.actor==='ava'?'#a6d990':a.actor==='orfeu'?'#94aaff':a.actor==='gabriel'||battle.family==='cinder'&&a.actor==='enemy'?'#ff8c48':a.actor==='ophelia'?'#a9e9ff':a.actor==='seiji'?'#87a3d9':a.actor==='max'?'#9fd7ff':'#bc83f4';const grad=ctx.createRadialGradient(w*.56,h*.5,8,w*.5,h*.5,w*.65);grad.addColorStop(0,hue+'70');grad.addColorStop(1,'#040914e8');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
 if(img){const professor=a.actor==='orfeu'||a.actor==='ava',frame=professor?0:a.actor==='enemy'?Math.min(3,Math.floor(t*4)):a.actor==='beatriz'?Math.min(2,Math.floor(Math.max(0,age-900)/(a.duration-900)*3)):Math.min(7,Math.floor(Math.max(0,age-900)/(a.duration-900)*8)),crop=professor?{x:0,y:0,w:img.width,h:img.height,anchorX:img.width/2,anchorY:img.height*.96}:battleCrop(key,frame),ref=professor?{x:0,y:0,w:img.width,h:img.height,anchorX:img.width/2,anchorY:img.height*.96}:battleCrop(key,0),focus=beat==='focus',size=a.actor==='enemy'?Math.min(w*.8,h*.92):focus?h*1.75:h*.82,scale=size/Math.max(1,ref.anchorY-ref.y),x=w*(focus?.55:beat==='release'&&!reduced?.42+t*.25:.5),y=focus?h*1.25:h*.92;ctx.save();if(!reduced&&age>=a.impactAt&&age<a.impactAt+180)ctx.translate(Math.sin(age/19)*6,Math.cos(age/22)*3);ctx.drawImage(img,crop.x,crop.y,crop.w,crop.h,x-(crop.anchorX-crop.x)*scale,y-(crop.anchorY-crop.y)*scale,crop.w*scale,crop.h*scale);ctx.restore();canvas.dataset.ultimateFrame=String(frame);}
 const fx=art[a.actor==='enemy'?'battle_vfx':`battle_fx_${a.actor}`];if(fx&&age>1800){const beatriz=a.actor==='beatriz',rows=beatriz?2:a.actor==='enemy'||['seiji','ophelia'].includes(a.actor)?4:6,row=beatriz?1:a.actor==='enemy'?battle.family==='cinder'?3:2:0,columns=beatriz?3:6,fw=fx.width/columns,fh=fx.height/rows,frame=Math.min(columns-1,Math.floor((age-1800)/(a.duration-1800)*columns)),sz=Math.min(w*.78,h*1.1);ctx.save();ctx.globalAlpha=.88;ctx.drawImage(fx,frame*fw,row*fh,fw,fh,w*.58-sz/2,h*.82-sz,sz,sz);ctx.restore();}
 if(!reduced&&age>=a.impactAt&&age<a.impactAt+120){ctx.fillStyle=hue+'70';ctx.fillRect(0,0,w,h);}ctx.fillStyle='#020611';ctx.fillRect(0,0,w,h*.065);ctx.fillRect(0,h*.94,w,h*.06);
 };draw();});return()=>{stop=true;cancelAnimationFrame(raf);};},[enabled,a?.started]);
 if(!enabled)return null;const companion=actor&&actor!=='enemy'&&!['beatriz','orfeu','ava'].includes(actor)?COMPANIONS[actor]:null;return <div className="ultimate-cinematic" role="status" aria-label={`Cinemática: ${name}`} style={{backgroundImage:`url(${ASSETS[['ashwood','ashpyre'].includes(map)?'battle_bg_forest':['subsolo','camara','galeria'].includes(map)?'battle_bg_below':'battle_bg_academy']})`}}><canvas ref={cv}/>{companion&&<aside className={`ultimate-companion companion-${actor}`}><span aria-hidden="true"/><p><b>{companion.name}</b>{actor==='seiji'?'Vai, Seiji!':actor==='ophelia'?'O inverno está com você.':actor==='marin'?'A noite é sua.':actor==='gabriel'?'Sua chama conduz.':'Max, a descarga é nossa!'}</p></aside>}<div className={`cinematic-caption element-${actor}`}><small>{hero?.name||battle.name} · ULTIMATE</small><strong>{name}</strong></div></div>;
}
