'use client';
import {useEffect,useRef,type CSSProperties} from 'react';
import {ASSETS,battleBackground,COMPANIONS,ENEMY_ULTIMATES,ULTIMATE_NAMES,combatElement,combatImpact,ELEMENT_COLORS,type HeroId,type Hero,type MapId} from '@/lib/game/data';
import type {Battle} from '@/lib/game/engine';
import type {Progression} from '@/lib/game/progression';
import {battleCrop,SPRITE_FRAMES} from '@/lib/game/sprites';
import {preloadBattleArt} from './battle-scene';
import {enemyPoseFrame} from '@/lib/game/enemyArtV30';
import {characterPoseFrame,characterCamera,hasCharacterBattleArt,characterEffectMotif} from '@/lib/game/characterAnimation';

export function UltimateCinematic({battle,heroes,map,progress}:{battle:Battle;heroes:Hero[];map:MapId;progress:Progression}){
 const cv=useRef<HTMLCanvasElement>(null),live=useRef(battle);live.current=battle;
 const a=battle.animation,enabled=!!a&&['ultimate','boss-ultimate','enemy-ultimate'].includes(a.action),actor=a?.actor,hero=heroes.find(h=>h.id===actor),name=actor==='enemy'?battle.eventId?.startsWith('recruit-')?ULTIMATE_NAMES[battle.asset as HeroId]:ENEMY_ULTIMATES[battle.family]?.name:actor?ULTIMATE_NAMES[actor]:'';
 useEffect(()=>{if(!enabled||!a)return;let stop=false,raf=0,last=0;const canvas=cv.current!,ctx=canvas.getContext('2d')!,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 void preloadBattleArt(heroes.map(hero=>hero.id),battle.eventId?.startsWith('recruit-')?battle.asset as HeroId:undefined).then(art=>{if(stop)return;const draw=()=>{if(stop)return;raf=requestAnimationFrame(draw);const now=Date.now();if(now-last<33)return;last=now;const r=canvas.getBoundingClientRect(),w=r.width,h=r.height,dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const age=now-a.started,t=Math.min(1,Math.max(0,age/a.duration)),beat=age<900?'focus':age<1800?'charge':age<a.impactAt?'release':'impact';canvas.dataset.cameraBeat=beat;canvas.dataset.ultimateActor=a.actor;
 const heroKey=a.actor==='gabriel'&&progress.gabrielForm==='lycan'?'gabriel_lycan':a.actor,key=a.actor==='enemy'?battle.eventId?.startsWith('recruit-')?`battle_${battle.asset}_ultimate`:`ultimate_${battle.family}`:`battle_${heroKey}_ultimate`,img=art[key];ctx.clearRect(0,0,w,h);const visualHero=a.actor==='enemy'&&battle.eventId?.startsWith('recruit-')?battle.asset as HeroId:a.actor,element=a.element||(visualHero==='enemy'?ENEMY_ULTIMATES[battle.family]?.element||'dark':combatElement(visualHero,'ultimate')),hue=ELEMENT_COLORS[element];const grad=ctx.createRadialGradient(w*.56,h*.5,8,w*.5,h*.5,w*.65);grad.addColorStop(0,hue+'70');grad.addColorStop(1,'#040914e8');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);
 if(img){const frameCount=SPRITE_FRAMES[key]?.length||1,frame=a.actor==='enemy'&&!battle.eventId?.startsWith('recruit-')?enemyPoseFrame(battle.family,'ultimate',Math.max(0,age-900)/Math.max(1,a.duration-900),frameCount):Math.min(frameCount-1,characterPoseFrame(visualHero,'ultimate',Math.max(0,age-(hasCharacterBattleArt(visualHero)?700:900))/Math.max(1,a.duration-(hasCharacterBattleArt(visualHero)?700:900)),frameCount)),crop=battleCrop(key,frame),ref=battleCrop(key,0),focus=beat==='focus',camera=characterCamera(visualHero,beat,t,reduced),size=a.actor==='enemy'?Math.min(w*.8,h*.92):focus?h*1.75:h*.82,preferred=size*camera.zoom/Math.max(1,ref.anchorY-ref.y),x=w*(focus?.55:camera.x),y=focus?h*1.25:h*.88,frames=SPRITE_FRAMES[key]||[crop],scale=focus?preferred:Math.min(preferred,(y-h*.075)/Math.max(...frames.map(f=>f.anchorY-f.y)),(h*.94-y)/Math.max(1,...frames.map(f=>f.y+f.h-f.anchorY)),(Math.min(x,w-x)-16)/Math.max(...frames.map(f=>Math.max(f.anchorX-f.x,f.x+f.w-f.anchorX))));ctx.save();ctx.globalAlpha=camera.alpha;if(!reduced&&age>=a.impactAt&&age<a.impactAt+180)ctx.translate(Math.sin(age/19)*6,Math.cos(age/22)*3);ctx.drawImage(img,crop.x,crop.y,crop.w,crop.h,x-(crop.anchorX-crop.x)*scale,y-(crop.anchorY-crop.y)*scale,crop.w*scale,crop.h*scale);ctx.restore();canvas.dataset.ultimateFrame=String(frame);}
 const ownKey=`battle_fx_${visualHero}`,ownCrop=hasCharacterBattleArt(visualHero)?SPRITE_FRAMES[ownKey]?.[characterEffectMotif('ultimate')]:undefined,impact=ownCrop?{asset:ownKey,columns:1,rows:1,row:0,frames:[ownCrop]}:a.actor==='enemy'&&!battle.eventId?.startsWith('recruit-')?undefined:combatImpact(element),fx=impact?art[impact.asset]:undefined;if(fx&&impact&&age>1800){const fw=fx.width/impact.columns,fh=fx.height/impact.rows,count=impact.frames?.length||impact.columns,frame=Math.min(count-1,Math.floor((age-1800)/(a.duration-1800)*count)),crop=impact.frames?.[frame]||{x:frame*fw,y:impact.row*fh,w:fw,h:fh},sz=Math.min(w*.64,h*.78),x=w*(ownCrop?.78:element==='earth'?.74:.58),effectScale=ownCrop?Math.min(w*.38/crop.w,h*.74/crop.h):sz/crop.h,effectWidth=crop.w*effectScale,effectHeight=crop.h*effectScale;ctx.save();ctx.globalAlpha=.88;ctx.drawImage(fx,crop.x,crop.y,crop.w,crop.h,x-effectWidth/2,h*.86-effectHeight,effectWidth,effectHeight);ctx.restore();}
 if(!reduced&&age>=a.impactAt&&age<a.impactAt+120){ctx.fillStyle=hue+'70';ctx.fillRect(0,0,w,h);}ctx.fillStyle='#020611';ctx.fillRect(0,0,w,h*.065);ctx.fillRect(0,h*.94,w,h*.06);
 };draw();});return()=>{stop=true;cancelAnimationFrame(raf);};},[enabled,a?.started]);
 if(!enabled)return null;const companion=actor&&actor!=='enemy'&&!['beatriz','orfeu','ava','carmilla'].includes(actor)?COMPANIONS[actor]:null,element=a.element||(actor==='enemy'?battle.eventId?.startsWith('recruit-')?combatElement(battle.asset as HeroId,'ultimate'):ENEMY_ULTIMATES[battle.family]?.element||'dark':actor?combatElement(actor,'ultimate'):'neutral');return <div className="ultimate-cinematic" role="status" aria-label={`Cinemática: ${name}`} style={{'--element':ELEMENT_COLORS[element],backgroundImage:`url(${ASSETS[battleBackground(map)]})`} as CSSProperties}><canvas ref={cv}/>{companion&&<aside className={`ultimate-companion companion-${actor}`}><span aria-hidden="true"/><p><b>{companion.name}</b>{actor==='seiji'?'Vai, Seiji!':actor==='ophelia'?'O inverno está com você.':actor==='marin'?'A noite é sua.':actor==='gabriel'?'Sua chama conduz.':'Max, a descarga é nossa!'}</p></aside>}<div className={`cinematic-caption element-${actor}`} style={{'--element':ELEMENT_COLORS[element]} as CSSProperties}><small>{hero?.name||battle.name} · ULTIMATE</small><strong>{name}</strong></div></div>;
}
