import { COMPANIONS, ENEMY_ULTIMATES, ULTIMATE_NAMES, signatureTechnique, combatElement, ELEMENT_LABELS, type CombatElement, ORIGINS, MAPS, newHeroes, heroBases, HERO_IDS, PLAYABLE_HERO_IDS, OBJECTIVES, SKILLS, type MapId, type MapData, type Point, type Entity, type Hero, type HeroId, type BaseHeroId } from './data';
import { freshProgression, deriveHeroes, level, setCount, spellBonus, GEAR, gearById, commonKills, SLOTS, SETS, FIELD_TECHNIQUES, DIFFICULTIES, BESTIARY, BOSS_REWARDS, TREE, EXTRA_SKILLS, QUESTS, ACHIEVEMENTS, CUTSCENES, SHOP, ANCHORS, EVENTS, type Progression, type Slot, type Status, type StatusId } from './progression';
import {chooseCosmetic,cosmeticById,cosmeticRank} from './cosmetics';
import {SUMMONED_HEROES,summonedById,type SummonRarity} from './summons';
import {planInAeternumVive} from './carmilla';
export const SAVE_KEY='eter-anima-stone-reach-v1';
export const STARTER_FIVE_STAR_IDS=['beatriz','orfeu','ava'] as const;
export type Save={version:2;progress:Progression;remedies:number;map:MapId;position:Point;stage:number;heroes:Hero[];potions:number;ethers:number;credits:number;opened:string[];checkpoint:{map:MapId;position:Point};elapsed:number};
export type Line={speaker:string;text:string;right?:HeroId|'abel';both?:boolean;present?:boolean};
export type Dialogue={lines:Line[];index:number;choice?:boolean};
export type BattleAnimation={actor:HeroId|'enemy';action:string;element?:CombatElement;target:HeroId|'enemy'|'party';started:number;duration:number;impactAt:number;value?:number;targets?:HeroId[];healing?:{target:HeroId;value:number};selfDamage?:number};
export type Battle={entityId:string;eventId?:string;family:string;name:string;boss:boolean;asset:string;hp:number;maxHp:number;spd:number;damage:number;xp:number;credits:number;round:number;queue:string[];index:number;weakened:boolean;log:string[];busy:boolean;result?:'victory'|'defeat';flash:number;animation?:BattleAnimation;statuses:Record<string,Status[]>;phase:1|2|3;bossCharge:number;difficulty:1|2|3;dropChance:number;baseDamage:number;freezeUsed:boolean};
export type Snapshot=Save & {mode:'start'|'selection'|'world'|'dialogue'|'battle'|'cutscene';cutscene:{id:string;index:number;replay:boolean}|null;overlay:'shop'|'events'|null;rewardNotice:{text:string;tab:string;focus?:string}|null;gachaResults:{id:string;duplicate:boolean}[];gachaBusy:boolean;summonResults:{id:string;rarity:SummonRarity;duplicate:boolean}[];summonBusy:boolean;fieldEffect:{kind:CombatElement|'heal'|'shadow';started:number}|null;dialogue:Dialogue|null;battle:Battle|null;nearby:Entity|null;toast:string;hasSave:boolean;saving:string;facing:number;moving:boolean};
const dist=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.y-b.y);
export function isWalkable(map:MapData,x:number,y:number):boolean{
 const tile=map.rows[Math.floor(y+.5)]?.[Math.floor(x+.5)];
 if(!tile||tile==='#'||tile==='w')return false;
 return !map.props.some(p=>p.solid&&x>=p.solid[0]-.2&&y>=p.solid[1]-.2&&x<=p.solid[0]+p.solid[2]+.2&&y<=p.solid[1]+p.solid[3]+.2);
}
export function findPath(map:MapData,from:Point,to:Point):Point[]{
 const start={x:Math.round(from.x),y:Math.round(from.y)},end={x:Math.round(to.x),y:Math.round(to.y)};
 if(!isWalkable(map,end.x,end.y))return [];
 const key=(p:Point)=>`${p.x},${p.y}`; const q=[start],seen=new Set([key(start)]),prev=new Map<string,Point>();
 for(let i=0;i<q.length;i++){
  const p=q[i];if(key(p)===key(end)){const out:Point[]=[];let v=end;while(key(v)!==key(start)){out.unshift(v);v=prev.get(key(v))!;}return out;}
  for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const n={x:p.x+dx,y:p.y+dy};if(!seen.has(key(n))&&isWalkable(map,n.x,n.y)){seen.add(key(n));prev.set(key(n),p);q.push(n);}}
 }return [];
}
const fresh=(protagonist?:HeroId):Save=>{const origin=protagonist?ORIGINS[protagonist]:ORIGINS.seiji,progress=freshProgression();if(protagonist){progress.protagonist=protagonist;progress.recruited=[protagonist];progress.party=[protagonist];progress.visited=[origin.map];progress.seen=protagonist==='marin'?['harbor']:protagonist==='ophelia'?['roots']:protagonist==='gabriel'?['ashwood-arrival']:[];}return ({version:2,progress,remedies:2,map:origin.map,position:{...origin.position},stage:0,heroes:deriveHeroes(progress,[]),potions:3,ethers:2,credits:80,opened:[],checkpoint:{map:origin.map,position:{...origin.position}},elapsed:0});};
export function parseSave(raw:string|null):Save|null{
 try{
  const s=JSON.parse(raw||'null');
  if(!s||![1,2].includes(s.version)||!MAPS[s.map as MapId]||!Number.isInteger(s.stage)||s.stage<0||s.stage>5)return null;
  const progress=freshProgression();
  if(s.version===2){
   const p=s.progress;if(!p||!Number.isFinite(p.xp)||p.xp<0||!p.points||!p.equipment||!p.kills||!p.metrics)return null;
   const lists=['learned','owned','bestiaryClaims','questClaims','achievementClaims','field','seen'] as const;
   if(lists.some(k=>!Array.isArray(p[k])||p[k].some((v:unknown)=>typeof v!=='string')))return null;
   Object.assign(progress,structuredClone(p));progress.masterMode=p.masterMode===true;progress.starterMailClaimed=p.starterMailClaimed===true;progress.starterSelected=STARTER_FIVE_STAR_IDS.find(id=>id===p.starterSelected)||null;progress.starterSelectorPending=progress.starterMailClaimed&&!progress.starterSelected&&p.starterSelectorPending===true;progress.gabrielForm=p.gabrielForm==='lycan'?'lycan':'human';progress.difficulty=[1,2,3].includes(p.difficulty)?p.difficulty:1;progress.fieldUntil={};for(const [id,end] of Object.entries(p.fieldUntil||{}))if(typeof end==='number'&&Number.isFinite(end)&&end>Date.now()&&end<=Date.now()+15000)progress.fieldUntil[id]=end;progress.unseenGear=(p.unseenGear||[]).filter((id:string)=>p.owned.includes(id));progress.unseenCosmetics=(p.unseenCosmetics||[]).filter((id:string)=>p.cosmetics?.includes(id));
   progress.points={...freshProgression().points,...p.points};progress.equipment={...freshProgression().equipment,...p.equipment};
   if(p.protagonist!==undefined&&!HERO_IDS.includes(p.protagonist))return null;progress.recruited=Array.isArray(p.recruited)?PLAYABLE_HERO_IDS.filter(id=>id==='carmilla'?p.recruited.includes(id)&&p.summoned?.includes(id)&&p.bonded?.includes(id)&&(p.masterMode||ACHIEVEMENTS.every(a=>a.test({...s,progress}))):['beatriz','orfeu','ava'].includes(id)?p.summoned?.includes(id)&&(id==='beatriz'||p.bonded?.includes(id))&&(p.recruited.includes(id)||p.bonded?.includes(id)):p.recruited.includes(id)):['seiji','ophelia'];if(!progress.recruited.length||p.protagonist&&!progress.recruited.includes(p.protagonist))return null;
   progress.party=Array.isArray(p.party)&&p.party.length>=1&&p.party.length<=5&&new Set(p.party).size===p.party.length&&p.party.every((id:HeroId)=>progress.recruited.includes(id))?p.party:progress.recruited.slice(0,5);
   progress.reserveVitals={};for(const id of PLAYABLE_HERO_IDS){const v=p.reserveVitals?.[id];if(v&&Number.isFinite(v.hp)&&v.hp>=0&&Number.isFinite(v.mp)&&v.mp>=0)progress.reserveVitals[id]={hp:v.hp,mp:v.mp};}
   progress.limit={...freshProgression().limit};for(const id of PLAYABLE_HERO_IDS)if(Number.isFinite(p.limit?.[id]))progress.limit[id]=Math.max(0,Math.min(100,Math.floor(p.limit[id])));
   for(const key of ['requests','visited','encounters','anchors','events','cosmetics'] as const)if(p[key]!==undefined&&(!Array.isArray(p[key])||p[key].some((v:unknown)=>typeof v!=='string')))return null;
   progress.requests=[...new Set<string>(p.requests||[])].filter(id=>QUESTS.some(q=>q.request===id));
   progress.visited=[...new Set<MapId>([...(p.visited||['patio']),s.map])].filter(id=>!!MAPS[id]);
   progress.encounters=[...new Set<string>(p.encounters||[])].filter(id=>Object.values(MAPS).some(m=>m.entities.some(e=>e.id===id&&['mob','boss','event'].includes(e.kind))));
   progress.anchors=[...new Set<string>(p.anchors||[])].filter(id=>ANCHORS.some(a=>a.id===id));
   progress.events=[...new Set<string>(p.events||[])].filter(id=>EVENTS.some(e=>e.id===id));
   progress.cosmetics=[...new Set<string>(p.cosmetics||[])].filter(id=>!!cosmeticById(id));
   for(const key of ['tokens','dust','rolls','pity','crystals','soulFragments','characterRolls','fourPity','fivePity'] as const){if(p[key]!==undefined&&(!Number.isSafeInteger(p[key])||p[key]<0))return null;progress[key]=p[key]??progress[key];}
   if(progress.pity>9)return null;
   progress.summoned=[...new Set<string>(p.summoned||[])].filter(id=>!!summonedById(id));progress.bonded=[...new Set<string>(p.bonded||[])].filter(id=>progress.summoned.includes(id));progress.constellations={};for(const id of progress.summoned)progress.constellations[id]=Math.max(0,Math.min(6,Math.floor(p.constellations?.[id]||0)));progress.lastSummon=summonedById(p.lastSummon)?.id&&progress.summoned.includes(p.lastSummon)?p.lastSummon:null;progress.lastSummonDuplicate=p.lastSummonDuplicate===true;progress.fourPity=Math.min(9,progress.fourPity);progress.fivePity=Math.min(79,progress.fivePity);
   progress.lastDraw=cosmeticById(p.lastDraw)&&progress.cosmetics.includes(p.lastDraw)?p.lastDraw:null;progress.lastDuplicate=p.lastDuplicate===true;
   progress.cosmeticEquipment={...freshProgression().cosmeticEquipment};const wornCosmetics=new Set<string>();
   for(const id of PLAYABLE_HERO_IDS){const item=p.cosmeticEquipment?.[id];if(progress.cosmetics.includes(item)&&!wornCosmetics.has(item)){progress.cosmeticEquipment[id]=item;wornCosmetics.add(item);}}
   progress.kills={lobo:0,sombra:0,selo:0,eco:0,...p.kills};
   progress.learned=[...new Set<string>(p.learned)].filter(id=>TREE.some(n=>n.id===id));
   progress.owned=[...new Set<string>(p.owned)].filter(id=>!!gearById(id));
   const used=new Set<string>();
   for(const h of PLAYABLE_HERO_IDS){
    if(p.points[h]===undefined&&(['beatriz','orfeu','ava','marin','gabriel','carmilla'].includes(h))){progress.points[h]=2;progress.equipment[h]={};continue;}if(!Number.isInteger(p.points[h])||p.points[h]<0||!p.equipment[h])return null;
    progress.equipment[h]={};
    for(const slot of SLOTS){const id=p.equipment[h][slot];if(id&&progress.owned.includes(id)&&gearById(id)!.slot===slot&&(!gearById(id)!.hero||gearById(id)!.hero===h)&&(gearById(id)!.minLevel||1)<=level(progress)&&!used.has(id)){progress.equipment[h][slot]=id;used.add(id);}}
   }
   for(const id of ['lobo','sombra','selo'])if(!Number.isInteger(p.kills[id])||p.kills[id]<0)return null;
   if(!Number.isInteger(progress.kills.eco)||progress.kills.eco<0)return null;
   if(!['purchases','heals','statuses'].every(k=>Number.isFinite(p.metrics[k])&&p.metrics[k]>=0))return null;
   if(!Number.isInteger(s.remedies)||s.remedies<0)return null;
  }else{progress.kills.selo=s.stage>=4?1:0;progress.seen=s.stage>=4?['arrival','awakening','silence']:['arrival'];}
  const map=fieldMap(s.map,progress);
  if(!s.position||!Number.isFinite(s.position.x)||!Number.isFinite(s.position.y))return null;if(!isWalkable(map,s.position.x,s.position.y)){if(s.map==='patio'&&progress.field.includes('ice-bridge')&&s.position.x<4.5&&s.position.y>=15&&s.position.y<=18)s.position={x:4,y:15};else return null;}
  const bases=deriveHeroes(progress);
  if(!Array.isArray(s.heroes)||s.heroes.length!==bases.length||s.heroes.some((h:Hero,i:number)=>h.id!==bases[i].id||!Number.isFinite(h.hp)||h.hp<0||h.hp>bases[i].maxHp||!Number.isFinite(h.mp)||h.mp<0||h.mp>bases[i].maxMp))return null;
  if(!['potions','ethers','credits','elapsed'].every(k=>Number.isFinite(s[k])&&s[k]>=0)||!Array.isArray(s.opened)||s.opened.some((x:unknown)=>typeof x!=='string')||!s.checkpoint||!MAPS[s.checkpoint.map as MapId]||!isWalkable(fieldMap(s.checkpoint.map,progress),s.checkpoint.position?.x,s.checkpoint.position?.y))return null;
  return {...s,version:2,progress,remedies:s.version===2?s.remedies:2,heroes:deriveHeroes(progress,s.heroes)};
 }catch{return null;}
}
function fieldMap(id:MapId,p:Progression):MapData{
 const map=MAPS[id];if(id!=='patio'||!(p.fieldUntil?.['ice-bridge']>Date.now()))return map;
 const rows=map.rows.map((r,y)=>y===16||y===17?r.slice(0,2)+'ii'+r.slice(4):r);
 return {...map,rows};
}
export class GameEngine{
 state:Snapshot={...fresh(),mode:'start',cutscene:null,overlay:null,rewardNotice:null,gachaResults:[],gachaBusy:false,summonResults:[],summonBusy:false,fieldEffect:null,dialogue:null,battle:null,nearby:null,toast:'',hasSave:false,saving:'',facing:0,moving:false};
 listeners=new Set<()=>void>(); saved:Save|null=null;keys=new Set<string>();path:Point[]=[];pending:string|null=null;paused=false;follower:Point={x:14,y:13.1};trail:Point[]=[];respawns:Record<string,number>={};now=0;patrolTime=0;lastEmit=0;lastAutosave=0;toastUntil=0;afterDialogue:(()=>void)|null=null;audio:AudioContext|null=null;
 private soundEnabled=false;private audioGeneration=0;private effects=new Set<HTMLAudioElement>();private tones=new Map<OscillatorNode,GainNode>();
 get sound(){return this.soundEnabled;}
 set sound(enabled:boolean){this.soundEnabled=enabled;if(!enabled)this.stopSounds();}
 private stopSounds(){this.audioGeneration++;for(const effect of this.effects){effect.muted=true;effect.pause();effect.src='';effect.onended=null;effect.onerror=null;}this.effects.clear();for(const [oscillator,gain] of this.tones){oscillator.onended=null;try{oscillator.stop();oscillator.disconnect();gain.disconnect();}catch{}}this.tones.clear();if(this.audio?.state==='running')void this.audio.suspend().catch(()=>{});}
 subscribe=(fn:()=>void)=>{this.listeners.add(fn);return()=>{this.listeners.delete(fn);};};
 snapshot=()=>this.state;
 emit(){this.state={...this.state,position:{...this.state.position},heroes:this.state.heroes.map(h=>({...h})),nearby:this.nearest()};this.listeners.forEach(f=>f());}
 hydrate(){try{this.saved=parseSave(localStorage.getItem(SAVE_KEY));}catch{}this.state.hasSave=!!this.saved;this.emit();}
 toast(text:string){this.state.toast=text;this.toastUntil=this.now+4;this.emit();}
 tone(f=400){if(!this.sound)return;try{if(!this.audio||this.audio.state==='closed')this.audio=new AudioContext();const context=this.audio;void context.resume().then(()=>{if((!this.sound||context!==this.audio)&&context.state!=='closed')void context.suspend().catch(()=>{});}).catch(()=>{});const o=context.createOscillator(),g=context.createGain();this.tones.set(o,g);o.onended=()=>{this.tones.delete(o);o.disconnect();g.disconnect();};o.type='sine';o.frequency.setValueAtTime(f,context.currentTime);g.gain.setValueAtTime(.045,context.currentTime);g.gain.exponentialRampToValueAtTime(.001,context.currentTime+.2);o.connect(g);g.connect(context.destination);o.start();o.stop(context.currentTime+.21);}catch{}}
 selectProtagonist(){this.clearMovement();this.state.mode='selection';this.emit();}
 start(resume=false,protagonist?:HeroId){const s=resume&&this.saved?structuredClone(this.saved):fresh(protagonist);this.state={...this.state,...s,mode:'world',cutscene:null,overlay:null,rewardNotice:null,gachaResults:[],gachaBusy:false,summonResults:[],summonBusy:false,fieldEffect:null,dialogue:null,battle:null};this.respawns={};this.clearMovement();this.follower={x:s.position.x,y:s.position.y+.9};this.unlockCarmillaIfReady();this.emit();
  if(!resume)this.playCutscene(protagonist?`origin-${protagonist}`:'arrival',()=>this.save());
 }
 clearMovement(){this.keys.clear();this.path=[];this.pending=null;this.trail=[];this.state.moving=false;}
 get map(){return fieldMap(this.state.map,this.state.progress);}
 activeEntities(){return this.map.entities.filter(e=>!(e.kind==='npc'&&this.state.progress.recruited.includes(e.id as HeroId)&&!['beatriz','orfeu','ava'].includes(e.id))&&!(e.fieldRequired&&!this.fieldActive(e.fieldRequired))&&!(e.id==='glifo-bau'&&!this.fieldActive('ink-glyph'))&&!(e.id==='jardim-bau'&&!this.fieldActive('ice-bridge'))&&!(e.id==='selo'&&this.state.stage>=4)&&!(e.id==='eco'&&this.state.progress.kills.eco>0)&&!(e.id==='cinder'&&this.state.progress.kills.cinder>0)&&!(e.eventId&&this.state.progress.events.includes(e.eventId))&&!(['mob','event'].includes(e.kind)&&(this.respawns[e.id]||0)>this.now)).map(e=>{if(e.kind!=='npc'&&e.kind!=='mob')return e;const x=e.x+Math.sin(this.patrolTime/3+e.x)*.32,y=e.y+Math.sin(this.patrolTime/4+e.y)*.16;return isWalkable(this.map,x,y)?{...e,x,y}:e;});}
 nearest(){if(this.state.mode!=='world')return null;return this.activeEntities().filter(e=>dist(e,this.state.position)<1.65).sort((a,b)=>dist(a,this.state.position)-dist(b,this.state.position))[0]||null;}
 update(dt:number){if(dt>.045){let remaining=Math.min(dt,.25);while(remaining>0){const step=Math.min(remaining,.04);this.update(step);remaining-=step;}return;}this.now+=dt;for(const [id,end] of Object.entries(this.state.progress.fieldUntil)){if(end<=Date.now()){delete this.state.progress.fieldUntil[id];if(!isWalkable(this.map,this.state.position.x,this.state.position.y)){const candidates=this.map.rows.flatMap((row,y)=>[...row].map((_,x)=>({x,y}))).filter(p=>isWalkable(this.map,p.x,p.y)).sort((a,b)=>dist(a,this.state.position)-dist(b,this.state.position));this.state.position=candidates[0];this.clearMovement();}this.emit();}}if(this.state.mode!=='start')this.state.elapsed+=dt;
  if(this.state.toast&&this.now>this.toastUntil){this.state.toast='';this.emit();}
  if(this.paused||this.state.mode!=='world')return;this.patrolTime+=dt;
  let dx=0,dy=0;const k=this.keys;if(k.has('ArrowUp')||k.has('w'))dy--;if(k.has('ArrowDown')||k.has('s'))dy++;if(k.has('ArrowLeft')||k.has('a'))dx--;if(k.has('ArrowRight')||k.has('d'))dx++;
  if(dx||dy){this.path=[];this.pending=null;}else if(this.path.length){const t=this.path[0],p=this.state.position;dx=t.x-p.x;dy=t.y-p.y;if(Math.hypot(dx,dy)<.09){this.state.position={...t};this.path.shift();dx=0;dy=0;}}
const moving=!!(dx||dy);if(moving){const n=Math.hypot(dx,dy),step=Math.min(dt,.045)*(k.has('Shift')?6.15:3.8);dx=dx/n*step;dy=dy/n*step;const p=this.state.position;
   if(Math.abs(dx)>Math.abs(dy))this.state.facing=dx<0?1:2;else this.state.facing=dy<0?3:0;
   const blocked=(x:number,y:number)=>!isWalkable(this.map,x,y)||this.activeEntities().some(e=>e.kind==='npc'&&dist(e,{x,y})<.38);
   if(!blocked(p.x+dx,p.y))p.x+=dx;if(!blocked(p.x,p.y+dy))p.y+=dy;
   const last=this.trail[this.trail.length-1];if(!last||dist(last,p)>.13)this.trail.push({...p});if(this.trail.length>11)this.follower=this.trail.shift()!;
  }
  if(!this.path.length&&this.pending){const id=this.pending;this.pending=null;const e=this.activeEntities().find(e=>e.id===id);if(e&&dist(e,this.state.position)<1.7)this.interact(e.id);}
  this.state.moving=moving;
  const mob=this.activeEntities().find(e=>e.kind==='mob'&&dist(e,this.state.position)<.72);if(mob&&!this.fieldActive('shadow-step'))this.beginBattle(mob);
  if(this.now-this.lastEmit>.13){this.lastEmit=this.now;this.emit();}
  if(this.now-this.lastAutosave>12){this.lastAutosave=this.now;this.save(true);}
 }
 blink(){if(this.state.mode!=='world'||this.paused)return false;const p=this.state.position,dir=([{x:0,y:1},{x:-1,y:0},{x:1,y:0},{x:0,y:-1}] as Point[])[this.state.facing]||{x:0,y:1},edge={x:p.x+dir.x*.72,y:p.y+dir.y*.72},land={x:Math.round(p.x)+dir.x*2,y:Math.round(p.y)+dir.y*2};if(isWalkable(this.map,edge.x,edge.y)||!isWalkable(this.map,land.x,land.y))return false;this.state.position={x:land.x,y:land.y};this.clearMovement();this.state.fieldEffect={kind:'shadow',started:Date.now()};this.tone(720);this.save();this.emit();return true;}
 moveTo(point:Point,entityId?:string){if(this.state.mode!=='world'||this.paused)return false;const e=entityId?this.activeEntities().find(v=>v.id===entityId):null;
  if(e&&dist(e,this.state.position)<1.65){this.interact(e.id);return true;}
  const targets=e?[{x:Math.round(e.x),y:Math.round(e.y)+1},{x:Math.round(e.x)-1,y:Math.round(e.y)},{x:Math.round(e.x)+1,y:Math.round(e.y)},{x:Math.round(e.x),y:Math.round(e.y)-1}]:[point];
  const paths=targets.map(t=>findPath(this.map,this.state.position,t)).filter(p=>p.length).sort((a,b)=>a.length-b.length);if(!paths.length){this.toast('Não há passagem por aqui.');return false;}
  this.path=paths[0];this.pending=e?.id||null;this.keys.clear();this.tone(320);return true;
 }
 approach(id:string){const e=this.activeEntities().find(e=>e.id===id);return e?this.moveTo(e,id):false;}
 interact(id?:string){if(this.state.mode==='dialogue'){this.nextDialogue();return;}if(this.state.mode!=='world'||this.paused)return;const e=id?this.activeEntities().find(e=>e.id===id):this.nearest();if(!e||dist(e,this.state.position)>1.7)return;
  this.clearMovement();this.tone(470);
  if(e.kind==='shop'){this.state.overlay='shop';this.emit();return;}
  if(e.kind==='event'){this.state.overlay='events';this.emit();return;}
  if(e.fieldSkill){this.toast('Use a técnica de exploração correspondente por Q, R ou pelo slot na tela.');return;}
  if(e.id==='glifo'||e.id==='agua-jardim'){this.toast(e.id==='glifo'?'Use Leitura de Tinta aqui: Q ou slot de exploração.':'Use Passo de Geada aqui: Q ou slot de exploração.');return;}
  if(e.kind==='warp'){if(e.minStage&&this.state.stage<e.minStage){this.say([{speaker:'Seiji',text:e.id==='escada'?'A escada está lacrada. O registro no centro da biblioteca deve dizer por quê.':['porta-galeria','porta-pira','porta-mata'].includes(e.id)?'Antes de descer, precisamos concluir nosso relato a Beatriz no pátio.':'A porta responde a uma inscrição. Precisamos ler o que ficou no subterrâneo.',right:'ophelia'}]);return;}this.travel(e.to!,e.spawn!);return;}
  if(e.kind==='save'){this.state.heroes.forEach(h=>{h.hp=h.maxHp;h.mp=h.maxMp;});this.state.checkpoint={map:this.state.map,position:{...this.state.position}};const anchor=ANCHORS.find(a=>a.entityId===e.id),newAnchor=!!anchor&&!this.state.progress.anchors.includes(anchor.id);if(newAnchor)this.state.progress.anchors.push(anchor!.id);this.save();this.toast(newAnchor?`${anchor!.name} ativado. Viagens entre marcos no menu Arredores.`:'HP e MP restaurados. Progresso salvo neste navegador.');return;}
  if(e.kind==='chest'){if(this.state.opened.includes(e.id)){this.toast('O baú já está vazio.');return;}this.state.opened.push(e.id);if(e.id.startsWith('semente-')){this.save();this.toast(`Semente ${e.id==='semente-porto'?'do cais':'da Galeria'} guardada na bolsa. Leve as duas amostras a Ava.`);return;}this.state.potions+=2;this.state.ethers++;if(['glifo-bau','jardim-bau'].includes(e.id))this.state.credits+=60;this.save();this.notify('Encontrou 2 Poções e 1 Elixir de Éter.'+(['glifo-bau','jardim-bau'].includes(e.id)?' +60 créditos.':''),'bag','potion');return;}
  if(e.kind==='npc'){
   if(e.id!=='beatriz'){this.talkToCompanion(e.id);return;}
   if(this.state.stage===0)this.say([{speaker:'Beatriz',text:'A Academia está fingindo que não ouviu. Eu prefiro conferir antes que esse barulho vire um problema.',right:'beatriz'},{speaker:'Seiji',text:'Você sabe por onde chegar lá embaixo?',right:'beatriz'},{speaker:'Beatriz',text:'No arquivo, há um registro aberto. Leia o que deixaram fora dos catálogos. Conversem com os viajantes da Academia e do Domo. O cristal cura feridas, mas não faz companhia.',right:'beatriz'}],()=>{this.state.stage=1;this.save();this.toast('Missão iniciada: A escada que não existe.');},true);
   else if(this.state.stage===4)this.say([{speaker:'Beatriz',text:'A vibração parou. Vocês conseguiram?',right:'beatriz'},{speaker:'Seiji',text:'O selo tinha uma voz. E, atrás dele, havia uma escada que continua descendo.',right:'beatriz'},{speaker:'Beatriz',text:'Então hoje nós fechamos uma ferida. Amanhã vamos ter que descobrir quem a abriu.',right:'beatriz'},{speaker:'Seiji',text:'Amanhã. Hoje eu queria ouvir o pátio em silêncio.',right:'beatriz'}],()=>{this.state.stage=5;this.state.credits+=600;this.save();this.toast('Capítulo concluído • Selo Ressonante + 600 créditos.');});
   else this.say([{speaker:'Beatriz',text:this.state.stage===5?'Stone Reach está segura por esta noite. Descansem. Vocês não precisam resolver tudo de uma vez.':'O registro está no centro da biblioteca. A escada fica a leste. Se precisarem, voltem aos cristais.',right:'beatriz'}]);return;
  }
  if(e.kind==='book'){if(this.state.stage===0){this.say([{speaker:'Ophelia',text:'Beatriz pediu que falássemos com ela antes de mexer nisso. Vamos ouvi-la primeiro.',right:'ophelia'}]);return;}
   this.say([{speaker:'Registro antigo',text:'“Guarde-se quando o inimigo respirar fundo. Metade do dano é metade do luto.”',right:'ophelia',both:true},{speaker:'Ophelia',text:'Há uma referência à Sala Gênesis… e uma ordem para apagar a escada dos registros.',right:'ophelia'},{speaker:'Seiji',text:'Apagaram do papel. Não da pedra. Vamos olhar a ala leste.',right:'ophelia'}],()=>{this.state.stage=Math.max(this.state.stage,2);this.save();this.toast('A escada leste está aberta.');});return;
  }
  if(e.kind==='rune'){this.say([{speaker:'Inscrição',text:'“O que foi selado aqui não dorme. Apenas espera ser lembrado.”',right:'ophelia',both:true},{speaker:'Seiji',text:'A tinta reconhece as marcas. Não como uma palavra… como uma cicatriz.',right:'ophelia'},{speaker:'Ophelia',text:'A porta ao sul se abriu. Antes de entrar, precisamos recuperar nossas forças.',right:'ophelia'}],()=>{this.state.stage=Math.max(this.state.stage,3);this.save();});return;}
  if(e.kind==='sign'){this.say([{speaker:e.text?e.label:'Mural da Academia',text:e.text||'Stone Reach • Pátio, biblioteca, porto e domo são áreas seguras. Cristais restauram HP e MP. Criaturas de Éter permanecem nos subterrâneos.',right:'ophelia',both:true}]);return;}
  if(e.id==='cinder'){this.playCutscene('cinder-awakening',()=>this.beginBattle(e));return;}
  if(e.kind==='boss')this.playCutscene(e.id==='eco'?'echo-awakening':'awakening',()=>this.beginBattle(e));
  else if(e.kind==='mob')this.beginBattle(e);
 }
 travel(map:MapId,position:Point){this.state.map=map;this.state.position={...position};if(!this.state.progress.visited.includes(map))this.state.progress.visited.push(map);this.follower=isWalkable(this.map,position.x,position.y+1.25)?{x:position.x,y:position.y+1.25}:{x:position.x+.8,y:position.y};this.clearMovement();this.save(true);this.toast(MAPS[map].name);this.emit();const scene=map==='porto'?'harbor':map==='domo'?'roots':map==='ashwood'?'ashwood-arrival':null;if(scene&&!this.state.progress.seen.includes(scene))this.playCutscene(scene);}
 returnToTitle(){if(!['world','selection'].includes(this.state.mode))return false;if(this.state.mode==='world')this.save(true);this.clearMovement();this.state.mode='start';this.emit();return true;}
 currentAnchor(){return this.state.mode==='world'?ANCHORS.find(a=>a.map===this.state.map&&this.state.progress.anchors.includes(a.id)&&dist(a.position,this.state.position)<=2.4):undefined;}
 fastTravel(id:string){const a=ANCHORS.find(v=>v.id===id);if(this.state.mode!=='world'||!a||!MAPS[this.state.map].safe&&!this.currentAnchor()||a.map===this.state.map||!this.state.progress.anchors.includes(id)||a.map==='galeria'&&this.state.stage<5)return false;this.travel(a.map,a.position);return true;}
 resolveEvent(id:string){const event=EVENTS.find(e=>e.id===id),p=this.state.progress;if(this.state.mode!=='world'||!event||event.map!==this.state.map||p.events.includes(id))return false;const entity=this.activeEntities().find(e=>e.id===event.entityId);if(!entity||dist(entity,this.state.position)>2.4)return false;this.clearMovement();
  if(event.type==='battle'){this.beginBattle({...entity,kind:'mob',label:'Sombra da Fenda',asset:'shadow',family:'sombra',hp:200,damage:19,xp:event.xp,credits:event.credits});return true;}
  const hero=this.state.heroes.find(h=>h.id===event.hero);if(!hero)return false;const cost=this.skillCost(hero.id,event.cost);if(!p.learned.includes(event.node)||hero.hp<=0||hero.mp<cost)return false;hero.mp-=cost;p.events.push(id);p.tokens+=event.tokens;this.state.credits+=event.credits;this.gainXp(event.xp);this.state.fieldEffect={kind:event.type as 'ink'|'ice',started:Date.now()};this.save();this.notify(`Evento resolvido · +${event.tokens} Fichas de Eco · +${event.xp} XP · +${event.credits} créditos.`,'gacha');return true;
 }
 drawCosmetic(random?:()=>number){return this.drawCosmetics(1,random);}
 drawCharacter(count:1|10,payWith:'ticket'|'crystal'='crystal',random:()=>number=Math.random){
  const p=this.state.progress,cost=count*160;
  if(this.state.mode!=='world'||this.state.summonBusy||![1,10].includes(count)||!p.masterMode&&(payWith==='ticket'&&p.tokens<count||payWith==='crystal'&&p.crystals<cost))return false;
  if(!p.masterMode){if(payWith==='ticket')p.tokens-=count;else p.crystals-=cost;}
  const results:{id:string;rarity:SummonRarity;duplicate:boolean}[]=[];
  for(let i=0;i<count;i++){
   const forceFive=p.fivePity>=79,forceFour=p.fourPity>=9||(count===10&&i===9&&!results.some(r=>r.rarity>=4));
   const fiveRate=Math.min(.76,.02+Math.max(0,p.fivePity-63)*.04),roll=random();
   const rarity:SummonRarity=forceFive||roll<fiveRate?5:forceFour||roll<fiveRate+.20?4:3;
   p.characterRolls++;p.fourPity=rarity>=4?0:p.fourPity+1;p.fivePity=rarity===5?0:p.fivePity+1;
   if(rarity===3){
    const pool=SHOP.filter(item=>item.gear&&item.minLevel<=level(p)),item=pool[Math.floor(random()*pool.length)]||pool[0];
    if(!item?.gear)continue;
    let copy=item.gear,n=2;while(p.owned.includes(copy))copy=`${item.gear}@${n++}`;
    p.owned.push(copy);p.unseenGear.push(copy);results.push({id:copy,rarity,duplicate:n>2});continue;
   }
   const pool=SUMMONED_HEROES.filter(hero=>hero.rarity===rarity&&!hero.achievementOnly),hero=pool[Math.floor(random()*pool.length)]||pool[0],duplicate=p.summoned.includes(hero.id);
   p.lastSummon=hero.id;p.lastSummonDuplicate=duplicate;
   if(duplicate){p.soulFragments+=rarity===5?20:8;p.crystals+=rarity===5?160:40;p.constellations[hero.id]=Math.min(6,(p.constellations[hero.id]||0)+1);}else{p.summoned.push(hero.id);if(hero.id==='beatriz'){p.recruited.push('beatriz');const base=heroBases().find(h=>h.id==='beatriz')!;p.reserveVitals.beatriz={hp:base.maxHp,mp:base.maxMp};}}
   results.push({id:hero.id,rarity,duplicate});
  }
  this.state.summonResults=results;this.state.summonBusy=true;this.soundEffect('gacha');this.save();this.emit();
  setTimeout(()=>{if(this.state.progress!==p||this.state.summonResults!==results)return;this.state.summonBusy=false;this.notify(`${count===10?'Dez invocações concluídas':'Invocação concluída'} · confira a Lista de Espera e os equipamentos na Bolsa.`,'gacha',results.find(r=>r.rarity>=4)?.id);},1500);
  return true;
 }
 claimStarterMail(){const p=this.state.progress;if(this.state.mode!=='world'||p.starterMailClaimed)return false;p.starterMailClaimed=true;p.starterSelectorPending=true;p.tokens+=30;this.save();this.notify('Correio de boas-vindas: +30 Fichas de Invocação e um seletor 5★. Escolha seu herói no MAIL.','mail');return true;}
 selectStarterFiveStar(id:string){const p=this.state.progress;if(this.state.mode!=='world'||!p.starterMailClaimed||!p.starterSelectorPending||!STARTER_FIVE_STAR_IDS.some(choice=>choice===id))return false;const duplicate=p.summoned.includes(id);p.starterSelectorPending=false;p.starterSelected=id;if(!duplicate)p.summoned.push(id);else{p.constellations[id]=Math.min(6,(p.constellations[id]||0)+1);p.soulFragments+=20;}if(!p.bonded.includes(id))p.bonded.push(id);p.constellations[id]??=0;if(!p.recruited.includes(id as HeroId))this.recruit(id as HeroId);this.save();this.notify(`${summonedById(id)!.name} escolhido no seletor 5★${duplicate?' · +1 constelação e 20 Fragmentos de Alma':' e disponível no Grupo'}.`,'party',id);return true;}
 unlockCarmillaIfReady(){const p=this.state.progress;if(p.recruited.includes('carmilla')||!p.masterMode&&!ACHIEVEMENTS.every(a=>a.test(this.state)))return false;p.recruited.push('carmilla');if(!p.summoned.includes('carmilla'))p.summoned.push('carmilla');if(!p.bonded.includes('carmilla'))p.bonded.push('carmilla');p.constellations.carmilla??=0;const base=heroBases().find(h=>h.id==='carmilla')!;p.reserveVitals.carmilla={hp:base.maxHp,mp:base.maxMp};return true;}
 bondSummoned(id:string){
  const p=this.state.progress,hero=summonedById(id);
  if(this.state.mode!=='world'||!hero||!p.summoned.includes(id)||p.bonded.includes(id))return false;
  if(id==='orfeu'||id==='ava'){if(this.state.map!==(id==='orfeu'?'arquivo':'domo'))return false;this.talkToCompanion(id);return true;}
  if(this.state.map!=='patio')return false;
  const speaker=hero.hero?heroBases().find(h=>h.id===hero.hero)?.name||hero.name:hero.name.split(' ')[0];
  const portrait=(hero.hero||id) as Line['right'];
  this.say([
   {speaker,text:`Este é o começo da nossa aula de vínculo. ${hero.bond} O Éter responde melhor quando entendemos por que lutamos.`,right:portrait,present:true},
   {speaker:this.state.heroes[0].name,text:'Então me mostre como você o escuta. Quero reconhecer sua voz quando estivermos em campo.',right:portrait,present:true},
   {speaker,text:hero.ultimate,right:portrait,present:true}
  ],()=>{p.bonded.push(id);this.save();this.notify(`${hero.name}: vínculo concluído; história e constelações abertas.`,'gacha',id);});
  return true;
 }
 drawCosmetics(count:1|5|10,random?:()=>number){const p=this.state.progress;if(this.state.mode!=='world'||this.state.gachaBusy||![1,5,10].includes(count)||!p.masterMode&&p.tokens<count)return false;if(!p.masterMode)p.tokens-=count;const results:{id:string;duplicate:boolean}[]=[];for(let i=0;i<count;i++){const item=chooseCosmetic(p.pity,random),duplicate=p.cosmetics.includes(item.id);p.rolls++;p.pity=item.rank>=4?0:p.pity+1;p.lastDraw=item.id;p.lastDuplicate=duplicate;if(duplicate)p.dust+=item.rank;else{p.cosmetics.push(item.id);p.unseenCosmetics.push(item.id);}results.push({id:item.id,duplicate});}this.state.gachaResults=results;this.state.gachaBusy=true;this.soundEffect('gacha');this.save();this.emit();setTimeout(()=>{if(this.state.progress!==p||this.state.gachaResults!==results)return;this.state.gachaBusy=false;this.notify(`${count} ${count>1?'invocações':'invocação'}: ${results.filter(v=>!v.duplicate).length} novas auras.`, 'gacha',results.find(v=>!v.duplicate)?.id);},1800);return true;}
 craftCosmetic(id:string){const p=this.state.progress,item=cosmeticById(id);if(this.state.mode!=='world'||!item||p.cosmetics.includes(id)||p.dust<item.craftCost)return false;p.dust-=item.craftCost;p.cosmetics.push(id);p.unseenCosmetics.push(id);p.lastDraw=id;p.lastDuplicate=false;this.save();this.notify(`${item.name} criada. Equipe uma aura em cada herói.`,'gacha',id);return true;}
 equipCosmetic(hero:HeroId,id?:string){const p=this.state.progress;if(this.state.mode!=='world'||id&&(!cosmeticById(id)||!p.cosmetics.includes(id)))return false;for(const h of PLAYABLE_HERO_IDS)if(id&&p.cosmeticEquipment[h]===id)p.cosmeticEquipment[h]=undefined;p.cosmeticEquipment[hero]=id;this.recalculateGear();return true;}
 notify(text:string,tab:string,focus?:string){this.state.rewardNotice={text,tab,focus};this.emit();}
 dismissNotice(){this.state.rewardNotice=null;this.emit();}
 fieldActive(id:string){return (this.state.progress.fieldUntil[id]||0)>Date.now();}
 fieldSlots(id:HeroId=this.state.heroes[0].id){return FIELD_TECHNIQUES[id];}
 quickField(slot:number){const h=this.state.heroes[0],tech=this.fieldSlots(h.id)[slot];if(this.state.mode!=='world'||this.paused||!tech)return false;return this.useFieldSkill(tech.id,h.id);}
 swapLeader(){if(this.state.mode!=='world'||this.paused||this.state.heroes.length<2)return false;this.state.progress.party.reverse();this.state.heroes.reverse();this.clearMovement();this.save();this.toast(`${this.state.heroes[0].name} lidera. Q e R acompanham suas técnicas.`);return true;}
 setDifficulty(id:1|2|3){if(this.state.mode!=='world'||![1,2,3].includes(id))return false;this.state.progress.difficulty=id;this.save();this.toast(`Dificuldade: ${DIFFICULTIES[id-1].name}. Vale para o próximo combate.`);return true;}
 ackGear(slot?:Slot){const p=this.state.progress;p.unseenGear=p.unseenGear.filter(id=>slot&&gearById(id)?.slot!==slot);this.save();}
 ackCosmetic(id:string){this.state.progress.unseenCosmetics=this.state.progress.unseenCosmetics.filter(v=>v!==id);this.save();}
 soundEffect(id:string){if(!this.sound||typeof Audio==='undefined')return;try{const audio=new Audio(`/assets/audio/sfx/${id}.wav`),token=this.audioGeneration;audio.volume=.32;audio.muted=false;this.effects.add(audio);const release=()=>{this.effects.delete(audio);audio.onended=null;audio.onerror=null;};audio.onended=release;audio.onerror=release;void audio.play().then(()=>{if(!this.sound||token!==this.audioGeneration){audio.muted=true;audio.pause();release();}}).catch(release);}catch{}}
 chargeLimit(id:HeroId,amount:number){this.state.progress.limit[id]=Math.min(100,(this.state.progress.limit[id]||0)+amount);}
 setGabrielForm(form:'human'|'lycan'){if(this.state.mode!=='world'||!this.state.progress.recruited.includes('gabriel'))return false;this.state.progress.gabrielForm=form;this.save();this.emit();return true;}
 ultimateName(id:HeroId){return ULTIMATE_NAMES[id];}
 assignParty(slot:number,id:HeroId){const p=this.state.progress;if(this.state.mode!=='world'||slot<0||slot>4||!p.recruited.includes(id)||p.party.includes(id))return false;for(const h of this.state.heroes)p.reserveVitals[h.id]={hp:h.hp,mp:h.mp};if(slot>=p.party.length)p.party.push(id);else p.party[slot]=id;p.party=[...new Set(p.party)].slice(0,5);this.state.heroes=deriveHeroes(p,[]);this.clearMovement();this.save();this.toast('Equipe atualizada. Até cinco integrantes podem entrar em combate.');return true;}
 removeFromParty(id:HeroId){const p=this.state.progress;if(this.state.mode!=='world'||p.party.length<=1||!p.party.includes(id))return false;for(const h of this.state.heroes)p.reserveVitals[h.id]={hp:h.hp,mp:h.mp};p.party=p.party.filter(v=>v!==id);this.state.heroes=deriveHeroes(p,[]);this.save();this.emit();return true;}
 unequipAll(hero:HeroId){if(this.state.mode!=='world')return false;this.state.progress.equipment[hero]={};this.recalculateGear();this.toast(`Todos os itens foram retirados de ${heroBases().find(h=>h.id===hero)?.name}.`);return true;}
 challengeRecruit(id:HeroId){const p=this.state.progress,base=heroBases().find(h=>h.id===id);if(this.state.mode!=='world'||['beatriz','orfeu','ava','carmilla'].includes(id)||!base||p.recruited.includes(id))return false;this.beginBattle({id:`duel-${id}`,eventId:`recruit-${id}`,label:`Duelo de recrutamento · ${base.name}`,kind:'mob',x:this.state.position.x,y:this.state.position.y,asset:id,family:'sombra',hp:Math.round(base.maxHp*2.2),damage:Math.max(14,base.atk),xp:80,credits:90});return true;}
 talkWithCompanion(){const id=this.state.heroes[0].id,companion=COMPANIONS[id];if(this.state.mode!=='world'||!companion)return false;this.say([{speaker:companion.name,right:id,text:companion.line,present:true}]);return true;}
 autoEquip(hero:HeroId){const p=this.state.progress;if(this.state.mode!=='world')return false;const unavailable=new Set(PLAYABLE_HERO_IDS.filter(id=>id!==hero).flatMap(id=>Object.values(p.equipment[id])));const score=(item:NonNullable<ReturnType<typeof gearById>>)=>item.hp*.25+item.mp*.3+item.atk*(hero==='ophelia'?1:2)+(item.spell||0)*(hero==='ophelia'?2:1);for(const slot of SLOTS){const candidates=p.owned.filter(id=>{const i=gearById(id);return i&&i.slot===slot&&!unavailable.has(id)&&(!i.hero||i.hero===hero)&&(i.minLevel||1)<=level(p);}).sort((a,b)=>score(gearById(b)!)-score(gearById(a)!));if(candidates[0])p.equipment[hero][slot]=candidates[0];}this.recalculateGear();this.toast('Equipamentos selecionados por atributos; peças de outros heróis são preservadas.');return true;}
 autoEquipAura(hero:HeroId){const p=this.state.progress;if(this.state.mode!=='world')return false;const options=p.cosmetics.filter(id=>!PLAYABLE_HERO_IDS.some(h=>h!==hero&&p.cosmeticEquipment[h]===id)).sort((a,b)=>cosmeticById(b)!.rank-cosmeticById(a)!.rank);if(!options[0])return false;return this.equipCosmetic(hero,options[0]);}
 finishProfessorBond(id:'orfeu'|'ava'){const p=this.state.progress;if(!p.summoned.includes(id)||p.bonded.includes(id))return; p.bonded.push(id);if(!p.recruited.includes(id)){p.recruited.push(id);const base=heroBases().find(h=>h.id===id)!;p.reserveVitals[id]={hp:base.maxHp,mp:base.maxMp};}this.notify(`${id==='orfeu'?'Orfeu':'Ava'}: vínculo concluído; disponível no Grupo.`, 'party', id);}
 talkToCompanion(id:string){if(id==='seiji'||id==='ophelia'){const p=this.state.progress,ready=this.state.stage>=(id==='seiji'?2:1);this.say([{speaker:id==='seiji'?'Seiji':'Ophelia',right:id,present:true,text:ready?(id==='seiji'?'Você encontrou o registro apagado. Minha tinta reconhece essas marcas. Quero seguir com você e ouvir o que a pedra guarda.':'Beatriz confiou essa investigação a você. O frio nas raízes vem do mesmo lugar. Vou ajudar a manter todos de pé.'):(id==='seiji'?'Este registro está reagindo à minha tinta. Leia-o depois de falar com Beatriz; então conversaremos.':'As raízes do Domo estão congelando. Leve o relato a Beatriz no Pátio; depois posso partir com você.')}],()=>{if(ready)this.recruit(id);this.save();});return;}if(id==='marin'||id==='gabriel'){const p=this.state.progress,ready=id==='marin'||p.encounters.includes('ashwolf-1');this.say([{speaker:id==='marin'?'Marin':'Gabriel',right:id,present:true,text:id==='marin'?'A Hora Sem Estrelas não precisa de mais testemunhas. Mas a mata lá fora… essa precisa de companhia. Posso seguir com vocês.':ready?'Você apagou aquele rastro de cinzas. Bom. Vou guardar o calor para ninguém se queimar. Conte comigo.':'Os lobos de cinza rondam o acampamento. Resolva o rastro a leste e eu sigo com vocês.'}],()=>{if(ready)this.recruit(id);this.save();});return;}const p=this.state.progress,add=(key:string)=>{if(!p.requests.includes(key))p.requests.push(key);},done=(key:string)=>{if(!p.field.includes(key))p.field.push(key);};
  if(id==='orfeu'){
   const mapped=['porto','domo','subsolo'].every(map=>p.visited.includes(map as MapId)),echo=p.requests.includes('echo')&&p.kills.eco>0;
   const lines:Line[]=[...(p.summoned.includes('orfeu')&&!p.bonded.includes('orfeu')?[{speaker:'Orfeu',right:'orfeu' as const,text:'Sua convocação chegou até mim. Nossa Aula de Vínculo começa com um mapa feito por você: percorra o porto, o domo e o Subterrâneo, depois volte para me contar.'}]:[]),{speaker:'Orfeu',right:'orfeu',text:mapped?'Você olhou antes de agir. É assim que um lugar deixa de ser só um nome num mapa.':'Antes de descer às cegas, conheçam os caminhos. Visitem o porto, o domo de Ava e a entrada do Subterrâneo. Depois me contem o que viram.'},{speaker:'Seiji',right:'orfeu',text:mapped?'O porto dá espaço para respirar. O jardim sente a vibração da Academia. Lá embaixo, a pedra guarda o que apagaram do papel.':'Vamos registrar tudo. Um mapa com as próprias marcas é mais útil que uma escada apagada.'}];
   if(this.state.stage>=5)lines.push({speaker:'Orfeu',right:'orfeu',text:echo?'A última memória se desfez. Obrigado por voltar e contar. Dessa vez o registro fica completo.':'Beatriz recebeu o relato. Agora a escada atrás do selo está aberta. Investiguem a Galeria Profunda e voltem quando o último eco estiver em silêncio.'});
   this.say(lines,()=>{add('orfeu-map');if(mapped){done('orfeu-report');this.finishProfessorBond('orfeu');}if(this.state.stage>=5)add('echo');if(echo)done('echo-report');this.save();this.toast(echo?'Relato entregue. Receba a missão no menu.':mapped?'Mapa relatado a Orfeu. Receba a recompensa no menu.':'Pedido de Orfeu registrado no menu de missões.');});
  }else if(id==='ava'){
   const seeds=['semente-porto','semente-galeria'].filter(key=>this.state.opened.includes(key)).length;
   this.say([...(p.summoned.includes('ava')&&!p.bonded.includes('ava')?[{speaker:'Ava',right:'ava' as const,text:'Senti sua convocação no jardim. Para firmar nosso vínculo, encontre as duas sementes de inverno no cais e na Galeria Profunda; depois traga-as para cá.'}]:[]),{speaker:'Ava',right:'ava',text:seeds===2?'As duas amostras. Uma aprendeu a esperar a maré; a outra resistiu sem luz. Vamos dar às duas um lugar aqui.':'Preciso de duas sementes de inverno. A caixa do cais guarda uma; a Galeria Profunda preserva a outra. Não se arrisquem antes de resolver o selo.'},{speaker:'Ophelia',right:'ava',text:seeds===2?'Se sobreviveram lá embaixo, podem crescer aqui. Eu gostaria de voltar para ver.':`${seeds?'Já encontramos uma das amostras. ':''}Vamos trazê-las. Com cuidado.`}],()=>{add('ava-seeds');if(seeds===2){done('ava-report');this.finishProfessorBond('ava');}this.save();this.toast(seeds===2?'Sementes entregues a Ava. Receba a recompensa no menu.':'Pedido de Ava registrado. As sementes aparecem na bolsa.');});
  }else if(id==='max'){
   const cleared=['lobo-norte','lobo-rastro','sombra-escada'].filter(key=>p.encounters.includes(key)).length;
   this.say([{speaker:'Max',right:'max',text:cleared===3?'Os três rastros se apagaram. Meu pequeno companheiro finalmente parou de olhar para as escadas. Bom trabalho.':`Dois lobos marcaram a ala oeste do Subterrâneo, e uma sombra ficou na alcova leste. O cais está seguro, mas quero saber o que segue por baixo. ${cleared}/3 rastros já resolvidos.`},{speaker:'Seiji',right:'max',text:cleared===3?'Não era só um barulho. Mas a rota está segura para a próxima patrulha.':'Vamos conferir os três pontos. E voltar com um relato, não só uma suposição.'}],()=>{add('max-patrol');if(cleared===3)done('max-report');this.save();this.toast(cleared===3?'Patrulha relatada a Max. Receba a recompensa no menu.':'Pedido de Max registrado. Os três encontros estão no Subterrâneo.');});
  }
 }
 recruit(id:HeroId){const p=this.state.progress;if(p.recruited.includes(id))return false;p.recruited.push(id);const joined=deriveHeroes({...p,party:[id]},[])[0];p.reserveVitals[id]={hp:joined.maxHp,mp:joined.maxMp};if(p.party.length<5){p.party.push(id);this.state.heroes=deriveHeroes(p,this.state.heroes);}this.toast(`${joined.name} recrutado · ${p.party.includes(id)?'entrou na equipe':'disponível no menu Grupo'}.`);return true;}
 narrativeLine(line:Line):Line{const id=this.state.progress.protagonist;if(!id)return line;const names=heroBases().filter(h=>HERO_IDS.includes(h.id as BaseHeroId)),name=heroBases().find(h=>h.id===id)!.name;const isHero=names.some(h=>h.name===line.speaker),missing=isHero&&!line.present&&!this.state.progress.party.includes(names.find(h=>h.name===line.speaker)!.id);let out={...line};if(missing){out.speaker=name;out.text=out.text.replace('A tinta reconhece as marcas. Não como uma palavra… como uma cicatriz.',({seiji:'A tinta reconhece as marcas. Não como uma palavra… como uma cicatriz.',ophelia:'É a mesma pulsação das raízes. O frio está guardando esta memória.',marin:'Eu reconheço esse silêncio. A Hora Sem Estrelas deixou uma cicatriz aqui também.',gabriel:'A brasa da forja pulsa no mesmo ritmo. Este selo é a origem do calor.',max:'A costura vibra como uma lembrança que se recusa a morrer.',beatriz:'Água e sombra reconhecem esta marca.',orfeu:'O eco da pedra responde ao primeiro som.',ava:'As raízes ainda guardam a memória.',carmilla:'O sangue reconhece a cicatriz antes que ela se abra.'}[id])).replace('Quando ele reunir o Éter, guarde-se. Eu fico com você.','Quando ele reunir o Éter, preciso me guardar. Não vou ceder agora.');}if(!line.present&&out.right&&HERO_IDS.includes(out.right as BaseHeroId)&&!this.state.progress.party.includes(out.right as HeroId))out.right=undefined;return out;}
 say(lines:Line[],onEnd?:()=>void,choice=false){this.state.mode='dialogue';this.state.dialogue={lines:lines.map(line=>this.narrativeLine(line)),index:0,choice};this.afterDialogue=onEnd||null;this.clearMovement();this.emit();}
 nextDialogue(){const d=this.state.dialogue;if(!d)return;if(d.index<d.lines.length-1)d.index++;else if(!d.choice)this.finishDialogue();this.tone(440);this.emit();}
 choose(accept:boolean){const d=this.state.dialogue;if(!d?.choice||d.index!==d.lines.length-1)return;if(!accept){this.state.dialogue=null;this.state.mode='world';this.afterDialogue=null;this.toast('Beatriz espera sua decisão no pátio.');}else this.finishDialogue();}
 finishDialogue(){this.state.dialogue=null;this.state.mode='world';const cb=this.afterDialogue;this.afterDialogue=null;cb?.();this.emit();}
 save(silent=false){if(this.state.mode==='start'||this.state.mode==='battle')return false;this.unlockCarmillaIfReady();const {version,progress,remedies,map,position,stage,heroes,potions,ethers,credits,opened,checkpoint,elapsed}=this.state;const data={version,progress,remedies,map,position,stage,heroes,potions,ethers,credits,opened,checkpoint,elapsed};try{localStorage.setItem(SAVE_KEY,JSON.stringify(data));this.saved=structuredClone(data);this.state.hasSave=true;this.state.saving='Salvo neste navegador';if(!silent)this.emit();return true;}catch{this.state.saving='Sem acesso ao armazenamento';if(!silent)this.toast('Não foi possível salvar neste navegador.');return false;}}
 beginBattle(e:Entity){this.clearMovement();const boss=e.kind==='boss',family=e.family||(boss?'selo':e.asset==='wolf'?'lobo':'sombra'),wolf=family==='lobo',settings=DIFFICULTIES[this.state.progress.difficulty-1],hp=Math.round((e.hp||(boss?330:wolf?130:155))*settings.hp);
  this.state.heroes.forEach(h=>{h.guard=false;h.mp=Math.min(h.maxMp,h.mp+cosmeticRank(this.state.progress,h.id,'echo')*2);});const duel=e.eventId?.startsWith('recruit-');this.state.battle={entityId:e.id,eventId:e.eventId,family,name:e.label,boss,asset:e.asset||'shadow',hp,maxHp:hp,spd:duel?heroBases().find(h=>h.id===e.asset)?.spd||11:boss?14:wolf?12:11,damage:Math.round((e.damage||(boss?19:16))*settings.damage),baseDamage:Math.round((e.damage||(boss?19:16))*settings.damage),phase:1,bossCharge:0,difficulty:settings.id,dropChance:settings.drop,xp:Math.round((e.xp||(boss?100:20))*settings.reward),credits:Math.round((e.credits||(boss?180:40))*settings.reward),round:1,queue:[],index:0,weakened:false,log:[duel?`${e.label} aceita o duelo.`:boss?`${e.label} toma forma.`:'O Éter transbordado avança.'],busy:false,flash:0,statuses:{seiji:[],ophelia:[],marin:[],gabriel:[],max:[],beatriz:[],orfeu:[],ava:[],carmilla:[],enemy:[]},freezeUsed:false};this.state.mode='battle';this.newRound();this.emit();}
 newRound(){const b=this.state.battle!;b.queue=[...this.state.heroes.filter(h=>h.hp>0).map(h=>({id:h.id,spd:h.spd})),{id:'enemy',spd:b.spd}].sort((a,c)=>c.spd-a.spd).map(c=>c.id);b.index=0;this.nextActor();}
 currentHero(){const b=this.state.battle;return b&&!b.result&&!b.busy?this.state.heroes.find(h=>h.id===b.queue[b.index]):undefined;}
 nextActor(){const b=this.state.battle!;if(b.result)return;
  if(b.hp<=0){b.result='victory';b.busy=false;b.log.push(b.eventId?.startsWith('recruit-')?`${b.name.replace('Duelo de recrutamento · ','')} aceita a vitória e se junta à expedição.`:`${b.name} se desfaz em Éter.`);this.emit();return;}
  if(this.state.heroes.every(h=>h.hp<=0)){b.result='defeat';b.busy=false;b.log.push('O cristal ainda guarda o caminho de volta.');this.emit();return;}
  if(b.index>=b.queue.length){b.round++;this.newRound();return;}
  const id=b.queue[b.index];
  if(id!=='enemy'&&!this.state.heroes.some(h=>h.id===id&&h.hp>0)){b.index++;this.nextActor();return;}
  this.updateBossPhase();const states=b.statuses[id]||[];
  if(states.some(s=>s.id==='bleed')){if(id==='enemy')b.hp=Math.max(0,b.hp-6);else{const h=this.state.heroes.find(h=>h.id===id)!;h.hp=Math.max(0,h.hp-6);}b.log.push(`${id==='enemy'?b.name:id==='seiji'?'Seiji':'Ophelia'} sofre 6 de sangramento.`);}
  if(b.hp<=0||this.state.heroes.every(h=>h.hp<=0)){this.nextActor();return;}
  if(id!=='enemy'&&!this.state.heroes.some(h=>h.id===id&&h.hp>0)){b.index++;this.nextActor();return;}
  if(states.some(s=>s.id==='freeze'||s.id==='bind')){const bound=states.some(s=>s.id==='bind');this.playAction(id as HeroId|'enemy',bound?'bound':'frozen',id as HeroId|'enemy',()=>{b.log.push(`${id==='enemy'?b.name:id} perde a ação: ${bound?'prisão de pedra':'congelamento'}.`);},650);return;}
  if(id==='enemy'){const alive=this.state.heroes.filter(h=>h.hp>0),duel=b.eventId?.startsWith('recruit-')&&b.asset in SKILLS;const collapse=b.boss&&b.round%2===0&&!this.hasStatus('enemy','silence');const ultimate=b.bossCharge>=100&&!this.hasStatus('enemy','silence');if(ultimate){b.bossCharge=0;this.soundEffect('ultimate-boss');}this.playAction('enemy',ultimate?b.boss?'boss-ultimate':'enemy-ultimate':collapse?'collapse':duel&&b.round%2===0?SKILLS[b.asset as HeroId][0].id:'enemy-hit',ultimate&&!duel&&ENEMY_ULTIMATES[b.family]?.area||collapse?'party':alive[(b.round-1)%alive.length].id,()=>this.enemyTurn(ultimate),ultimate?4800:1200);return;}
  const hero=this.state.heroes.find(h=>h.id===id)!;hero.guard=false;this.emit();}
 hasStatus(id:string,status:StatusId){return !!this.state.battle?.statuses[id]?.some(s=>s.id===status);}
 addStatus(target:string,id:StatusId,turns:number){const b=this.state.battle;if(!b)return false;
  if(target!=='enemy'){const heroId=target as HeroId;if(id==='bleed'&&setCount(this.state.progress,heroId,'wolf')>=6||id==='blind'&&setCount(this.state.progress,heroId,'veil')>=6||id==='silence'&&setCount(this.state.progress,heroId,'ember')>=6||(id==='freeze'||id==='bind')&&setCount(this.state.progress,heroId,'lunar')>=6){b.log.push('O conjunto protege contra o estado.');return false;}}
  if(target==='enemy'&&(id==='freeze'||id==='bind')){if(b.freezeUsed){b.log.push('O inimigo já rompeu uma imobilização nesta batalha.');return false;}b.freezeUsed=true;}
  const states=b.statuses[target]||[];b.statuses[target]=[...states.filter(s=>s.id!==id),{id,turns}];if(target==='enemy')this.state.progress.metrics.statuses++;return true;
 }
 expireStatuses(id:string){const b=this.state.battle;if(b)b.statuses[id]=(b.statuses[id]||[]).map(s=>({...s,turns:s.turns-1})).filter(s=>s.turns>0);}

 enemyTurn(ultimate=false){const b=this.state.battle!,duel=b.eventId?.startsWith('recruit-')&&b.asset in SKILLS,duelId=b.asset as HeroId,alive=this.state.heroes.filter(h=>h.hp>0),aoe=duel?false:ultimate?!!ENEMY_ULTIMATES[b.family]?.area:b.boss&&b.round%2===0&&!this.hasStatus('enemy','silence'),targets=aoe?alive:[alive[(b.round-1)%alive.length]],base=Math.round((b.damage+(aoe?5:0))*(ultimate?(ENEMY_ULTIMATES[b.family]?.multiplier||1.5):1));if(!ultimate)b.bossCharge=Math.min(100,b.bossCharge+34+(b.phase-1)*8);this.soundEffect('hit');
  if(this.hasStatus('enemy','blind')&&Math.random()<.5){b.log.push(`${duel?heroBases().find(h=>h.id===duelId)?.name:'A criatura'} erra o golpe por cegueira.`);b.weakened=false;return;}
  const move=duel?ultimate?this.ultimateName(duelId):b.round%2===0?SKILLS[duelId][0].name:`Ataque de ${heroBases().find(h=>h.id===duelId)?.name}`:ultimate?ENEMY_ULTIMATES[b.family]?.name||'Ruptura do Éter':aoe?b.family==='cinder'?'Pulso da Pira':'Colapso do Véu':'Golpe de Éter';
  for(const h of targets){const damage=Math.max(1,Math.round(base*(h.guard?.45:1)*(b.weakened?.45:1)*(setCount(this.state.progress,h.id,'ember')>=6?.8:1))-cosmeticRank(this.state.progress,h.id,'defense'));h.hp=Math.max(0,h.hp-damage);if(this.state.progress.masterMode&&h.hp===0){h.hp=h.maxHp;h.mp=h.maxMp;b.statuses[h.id]=[];b.log.push(`${h.name} retorna completo pela proteção do Modo Mestre.`);}this.chargeLimit(h.id,Math.min(25,Math.ceil(damage*.6)));b.log.push(`${move}: ${h.name} sofre ${damage} de dano${h.guard?' (guarda)':''}.`);
   if(h.hp>0&&!h.guard&&(ultimate||b.round%2===0)){const duelStatuses:Partial<Record<HeroId,StatusId>>={seiji:'blind',ophelia:'freeze',marin:'blind',gabriel:'bleed',max:'silence'};const status=duel?duelStatuses[duelId]||'blind':ultimate?ENEMY_ULTIMATES[b.family]?.status||'blind':b.boss?'silence':b.family==='lobo'?'bleed':'blind';this.addStatus(h.id,status,b.boss?1:2);b.log.push(`${h.name}: ${status==='bleed'?'sangramento':status==='blind'?'cegueira':status==='freeze'?'congelamento':'silêncio'}.`);}
  }
  b.weakened=false;b.flash=Date.now();this.tone(130);
 }

 playAction(actor:HeroId|'enemy',action:string,target:BattleAnimation['target'],impact:()=>void,duration=1200){const b=this.state.battle!;const duelHero=actor==='enemy'&&b.eventId?.startsWith('recruit-')&&PLAYABLE_HERO_IDS.includes(b.asset as HeroId)?b.asset as HeroId:undefined;const element=action==='bound'?'earth':action==='frozen'?'ice':actor!=='enemy'?combatElement(actor,action):duelHero?combatElement(duelHero,action.includes('ultimate')?'ultimate':action==='enemy-hit'?'attack':action):b.family==='cinder'?'fire':'dark';const animation:BattleAnimation={actor,action,element,target,started:Date.now(),duration,impactAt:Math.round(duration*(['ultimate','boss-ultimate','enemy-ultimate'].includes(action)?.68:.55))};b.animation=animation;b.busy=true;if(actor!=='enemy')this.soundEffect(action==='ultimate'?`ultimate-${actor}`:['attack'].includes(action)?'swing':['guard','potion','ether','remedy'].includes(action)?'heal':'cast');this.emit();
  setTimeout(()=>{if(this.state.battle!==b||this.state.mode!=='battle'||b.animation!==animation)return;impact();this.emit();},animation.impactAt);
  setTimeout(()=>{if(this.state.battle!==b||this.state.mode!=='battle'||b.animation!==animation)return;this.expireStatuses(actor);b.animation=undefined;b.index++;b.busy=false;this.nextActor();this.emit();},duration);
 }
 transferCarmilla(guard=false){const b=this.state.battle!,plan=planInAeternumVive(this.state.heroes),caster=this.state.heroes.find(h=>h.id==='carmilla')!;for(const target of plan.targets){const ally=this.state.heroes.find(h=>h.id===target.id)!;ally.hp=Math.min(ally.maxHp,ally.hp+target.heal);}caster.hp=Math.max(0,caster.hp-plan.selfDamage);if(guard)this.state.heroes.filter(h=>h.hp>0).forEach(h=>h.guard=true);if(this.state.progress.masterMode&&caster.hp===0){caster.hp=caster.maxHp;caster.mp=caster.maxMp;b.statuses.carmilla=[];}this.state.progress.metrics.heals+=plan.targets.length;if(b.animation){b.animation.targets=plan.targets.map(h=>h.id as HeroId);b.animation.selfDamage=plan.selfDamage;b.animation.value=plan.targets.reduce((n,h)=>n+h.heal,0);}b.log.push(`IN AETERNUM VIVE: ${plan.targets.map(h=>this.state.heroes.find(v=>v.id===h.id)!.name).join(' e ')||'ninguém'} recupera ${plan.targets.reduce((n,h)=>n+h.heal,0)} HP; Carmilla sofre ${plan.selfDamage} de dano.${guard?' O grupo recebe guarda.':''}`);return plan;}
 action(action:string,target?:HeroId){const b=this.state.battle,h=this.currentHero();if(!b||!h||b.result)return false;const allyId=(this.state.heroes.find(v=>v.id===target)||h).id;
  if(action==='flee'){if(b.boss)return false;this.respawns[b.entityId]=this.now+12;this.state.mode='world';this.state.battle=null;this.save();this.toast('O grupo recuou.');return true;}
  const sk=this.skills(h.id).find(s=>s.id===action),signature=signatureTechnique(action);
  if(signature?.target==='ally'&&(this.state.heroes.find(v=>v.id===allyId)?.hp||0)<=0)return false;
  if(action==='in-aeternum-vive'&&!planInAeternumVive(this.state.heroes).targets.length)return false;
  if(sk&&this.hasStatus(h.id,'silence'))return false;
  if(action==='remedy'){if(!this.state.remedies||!b.statuses[allyId]?.length)return false;this.state.remedies--;}
  else if(action==='potion'){if(!this.state.potions)return false;this.state.potions--;}
  else if(action==='ether'){if(!this.state.ethers)return false;this.state.ethers--;}
  else if(action==='ultimate'){if((this.state.progress.limit[h.id]||0)<100)return false;this.state.progress.limit[h.id]=0;}
  else if(!['attack','guard'].includes(action)){if(!sk||!this.state.progress.masterMode&&h.mp<this.skillCost(h.id,sk.cost))return false;if(!this.state.progress.masterMode)h.mp-=this.skillCost(h.id,sk.cost);}
  const actorId=h.id;const healing=['mend','cleanse','rekindle','shadowrest','margem','garden-heal'].includes(action);this.playAction(actorId,action,signature?.target==='ally'?allyId:action==='in-aeternum-vive'||action==='ultimate'&&['ophelia','carmilla'].includes(actorId)?'party':['stormguard','echo-ward'].includes(action)?'party':action==='shadowrest'?actorId:['mend','cleanse','rekindle','margem','garden-heal','potion','ether','remedy'].includes(action)?allyId:action==='guard'?actorId:'enemy',()=>{
   const hero=this.state.heroes.find(v=>v.id===actorId)!,ally=this.state.heroes.find(v=>v.id===allyId)!;let dmg=0;
   if(signature?.target!=='ally'&&!['ultimate','in-aeternum-vive','bulwark','stormguard','echo-ward','guard','mend','cleanse','rekindle','shadowrest','potion','ether','remedy'].includes(action)&&this.hasStatus(actorId,'blind')&&Math.random()<.5){b.log.push(`${hero.name} erra por cegueira.`);return;}
   if(action==='ultimate'){
    const bonus=spellBonus(this.state.progress,actorId)+(this.state.progress.learned.includes(`${actorId}-master`)?12:0),alive=this.state.heroes.filter(member=>member.hp>0);
    if(actorId==='carmilla'){
     const plan=this.transferCarmilla(true);for(const member of plan.targets)b.statuses[member.id]=[];
     b.log.push(`${this.ultimateName(actorId)}: fios rubros limpam as feridas tratadas e protegem o grupo.`);
    }else if(actorId==='ophelia'){
     const amount=Math.round((65+bonus)*this.magicScale(actorId));for(const member of alive){member.hp=Math.min(member.maxHp,member.hp+amount);member.guard=true;b.statuses[member.id]=[];}
     this.addStatus('enemy','freeze',1);this.state.progress.metrics.heals+=alive.length;
     b.log.push(`${this.ultimateName(actorId)}: cura ${amount} HP dos aliados vivos, remove estados, concede guarda e ergue gelo sobre o inimigo.`);if(b.animation)b.animation.value=amount;
    }else{
     const base=({seiji:88,marin:94,gabriel:84,max:90,beatriz:86} as Partial<Record<HeroId,number>>)[actorId]||80;
     dmg=actorId==='orfeu'?Math.round(78+bonus+hero.atk):Math.round((base+bonus)*this.magicScale(actorId));
     if(setCount(this.state.progress,actorId,'lunar')>=3)hero.hp=Math.min(hero.maxHp,hero.hp+4);
     if(actorId==='seiji'){this.addStatus('enemy','silence',1);b.weakened=true;}
     if(actorId==='marin'){hero.hp=Math.min(hero.maxHp,hero.hp+35);this.addStatus('enemy','blind',2);this.addStatus('enemy','silence',1);}
     if(actorId==='gabriel')for(const member of alive){member.guard=true;b.statuses[member.id]=(b.statuses[member.id]||[]).filter(st=>st.id!=='bleed');}
     if(actorId==='max'){b.bossCharge=Math.max(0,b.bossCharge-35);this.addStatus('enemy','blind',2);}
     if(actorId==='beatriz'){this.addStatus('enemy','blind',2);alive.forEach(member=>member.guard=true);}
     if(actorId==='orfeu'){this.addStatus('enemy','silence',2);this.state.heroes.forEach(member=>{member.guard=true;b.statuses[member.id]=(b.statuses[member.id]||[]).filter(st=>st.id!=='silence');});}
     if(actorId==='ava'){this.addStatus('enemy','bind',1);this.state.heroes.forEach(member=>member.hp=Math.min(member.maxHp,member.hp+25));}
     b.log.push(`${hero.name} libera ${this.ultimateName(actorId)}: ${dmg} de dano.`);
    }
   }
   else if(signature){
    const healAlly=(recipient:Hero,base:number)=>{const amount=Math.min(recipient.maxHp-recipient.hp,this.healPower(actorId,base));recipient.hp+=amount;if(amount>0)this.state.progress.metrics.heals++;return amount;};
    if(signature.damage){dmg=Math.round((signature.damage+spellBonus(this.state.progress,actorId))*this.magicScale(actorId));if(setCount(this.state.progress,actorId,'lunar')>=3)hero.hp=Math.min(hero.maxHp,hero.hp+4);}
    if(signature.status)this.addStatus('enemy',signature.status,signature.turns||1);
    if(signature.weaken)b.weakened=true;
    if(signature.chargeDrain)b.bossCharge=Math.max(0,b.bossCharge-signature.chargeDrain);
    if(signature.selfHeal)healAlly(hero,signature.selfHeal);
    if(signature.woundedHeal){const wounded=this.state.heroes.filter(member=>member.hp>0&&member.hp<member.maxHp).sort((a,b)=>a.hp/a.maxHp-b.hp/b.maxHp)[0];if(wounded){const amount=healAlly(wounded,signature.woundedHeal);if(b.animation&&amount>0)b.animation.healing={target:wounded.id,value:amount};}}
    if(signature.heal){const amount=healAlly(ally,signature.heal);if(b.animation)b.animation.value=amount;}
    const protectedMembers=signature.guard==='party'?this.state.heroes.filter(member=>member.hp>0):[ally];
    if(signature.guard)protectedMembers.forEach(member=>member.guard=true);
    if(signature.cleanse)for(const member of protectedMembers)b.statuses[member.id]=signature.cleanse==='all'?[]:(b.statuses[member.id]||[]).filter(st=>st.id!=='bleed');
    b.log.push(`${hero.name} usa ${signature.name}: ${dmg?`${dmg} de dano de ${ELEMENT_LABELS[combatElement(actorId,action)]}`:`${b.animation?.value||0} HP restaurados`}${signature.chargeDrain?`; carga inimiga reduzida em ${signature.chargeDrain}`:''}.`);
   }
   else if(action==='in-aeternum-vive'){this.transferCarmilla();}
   else if(action==='bulwark'){this.state.heroes.forEach(member=>member.guard=true);b.log.push('Baluarte: o grupo recebe guarda.');}
   else if(action==='stormguard'){this.state.heroes.forEach(member=>{member.guard=true;b.statuses[member.id]=(b.statuses[member.id]||[]).filter(st=>st.id!=='blind');});b.log.push('Guarda de Tempestade: o grupo recebe guarda e dissipa cegueira.');}
   else if(action==='echo-ward'){this.state.heroes.forEach(member=>{member.guard=true;b.statuses[member.id]=(b.statuses[member.id]||[]).filter(st=>st.id!=='silence');});b.log.push('Guarda Nula: o grupo recebe guarda e remove silêncio.');}
   else if(action==='attack'){dmg=this.attackPower(actorId);if(setCount(this.state.progress,actorId,'wolf')>=3)hero.mp=Math.min(hero.maxMp,hero.mp+3);const heal=cosmeticRank(this.state.progress,actorId,'drain');hero.hp=Math.min(hero.maxHp,hero.hp+heal);b.log.push(`${hero.name} ataca: ${dmg} de dano ${combatElement(actorId,'attack')==='neutral'?'físico':`de ${ELEMENT_LABELS[combatElement(actorId,'attack')]}`} .${heal?` Aura recupera ${heal} HP.`:''}`);}
   else if(action==='guard'){const mp=3+cosmeticRank(this.state.progress,actorId,'guard');hero.guard=true;hero.mp=Math.min(hero.maxMp,hero.mp+mp);b.log.push(`${hero.name} guarda e recupera ${mp} MP.`);if(b.animation)b.animation.value=mp;}
   else if(action==='potion'){ally.hp=Math.min(ally.maxHp,ally.hp+45);b.log.push(`${hero.name} usa Poção em ${ally.name}: +45 HP.`);}
   else if(action==='ether'){ally.mp=Math.min(ally.maxMp,ally.mp+24);b.log.push(`${ally.name} recupera 24 MP com Elixir de Éter.`);}
   else if(action==='remedy'){b.statuses[allyId]=[];b.log.push(`Antídoto de Luz remove os estados de ${ally.name}.`);}
   else if(healing){const recipient=action==='shadowrest'?hero:ally,heal=this.healPower(actorId,({mend:36,cleanse:25,rekindle:28,shadowrest:24,margem:32,'garden-heal':38} as Record<string,number>)[action]);recipient.hp=Math.min(recipient.maxHp,recipient.hp+heal);if(['cleanse','rekindle','margem'].includes(action))b.statuses[allyId]=[];this.state.progress.metrics.heals++;b.log.push(`${sk!.name}: ${action==='shadowrest'?hero.name:ally.name} recupera ${heal} HP.`);if(b.animation)b.animation.value=heal;}
   else{dmg=({cut:38,shard:32,stain:26,blind:22,bleed:30,freeze:24,eclipse:34,drain:26,blaze:36,voltcut:34,arc:28,darkveil:24,flamewall:28,rupture:32,nightseal:38,nova:48,ashseal:30,tidecut:36,'umbra-seal':25,'echo-strike':32,'vine-strike':32} as Record<string,number>)[action]||0;dmg+=spellBonus(this.state.progress,actorId);if(action==='cut'&&this.state.progress.learned.includes('seiji-ink')||action==='shard'&&this.state.progress.learned.includes('ophelia-ice')||['eclipse','blaze','voltcut'].includes(action)&&this.state.progress.learned.includes(`${actorId}-power`))dmg+=8;dmg=Math.round(dmg*this.magicScale(actorId));if(setCount(this.state.progress,actorId,'lunar')>=3)hero.hp=Math.min(hero.maxHp,hero.hp+4);if(action==='rupture')this.addStatus('enemy','bleed',3);if(['nightseal','ashseal'].includes(action))this.addStatus('enemy','silence',1);if(action==='arc')this.addStatus('enemy','blind',2);if(action==='echo-strike')this.addStatus('enemy','silence',1);if(action==='vine-strike')this.addStatus('enemy','bind',1);if(action==='drain')hero.hp=Math.min(hero.maxHp,hero.hp+18);if(['darkveil','umbra-seal'].includes(action))this.addStatus('enemy','blind',2);if(action==='flamewall')b.weakened=true;if(action==='stain'){b.weakened=true;if(this.state.progress.learned.includes('seiji-master'))this.addStatus('enemy','silence',1);}if(action==='blind')this.addStatus('enemy','blind',2);if(action==='bleed')this.addStatus('enemy','bleed',3);if(action==='freeze')this.addStatus('enemy','freeze',1);b.log.push(`${hero.name} usa ${sk!.name}: ${dmg} de dano${action==='stain'?', próximo golpe enfraquecido':''}.`);}
   if(action!=='ultimate')this.chargeLimit(actorId,(action==='attack'?20:sk?15:10)+(action==='guard'&&setCount(this.state.progress,actorId,'ember')>=3?10:0));b.hp=Math.max(0,b.hp-dmg);if(b.animation&&!b.animation.value)b.animation.value=dmg||({'mend':36,'potion':45,'ether':24,'guard':3}as Record<string,number>)[action];if(dmg){b.flash=Date.now();this.soundEffect('hit');this.updateBossPhase();this.tone(620);}else this.tone(370);
  },action==='ultimate'?4800:['guard','potion','ether','remedy'].includes(action)?700:action==='attack'?1200:1600);return true;
 }
 updateBossPhase(){const b=this.state.battle;if(!b?.boss||b.hp<=0)return;const phase=b.hp<=b.maxHp/3?3:b.hp<=b.maxHp*2/3?2:1;if(phase>b.phase){b.phase=phase;b.damage=b.baseDamage+(phase-1)*4;b.spd=14+(phase-1)*2;b.bossCharge=Math.min(100,b.bossCharge+25);b.log.push(`Fase ${phase}: ${b.name} desperta. A ultimate está em ${b.bossCharge}%.`);this.soundEffect('phase');}}
 finishBattle(){const b=this.state.battle;if(!b?.result)return;let lootGear:string|undefined,lootText='';const beforeLevel=level(this.state.progress);
  if(b.result==='defeat'){this.state.heroes.forEach(h=>{h.hp=Math.ceil(h.maxHp*.6);h.mp=Math.ceil(h.maxMp*.6);});this.travel(this.state.checkpoint.map,this.state.checkpoint.position);this.toast('O grupo retorna ao cristal. Você pode tentar novamente.');}
  else{const p=this.state.progress;this.state.credits+=b.credits;if(!b.eventId?.startsWith('recruit-'))p.kills[b.family]=(p.kills[b.family]||0)+1;if(!p.encounters.includes(b.entityId))p.encounters.push(b.entityId);if(b.boss)p.tokens+=Math.round(3*DIFFICULTIES[b.difficulty-1].reward);else if(!b.eventId?.startsWith('recruit-')&&commonKills(p)%3===0)p.tokens++;const event=EVENTS.find(e=>e.id===b.eventId);if(b.eventId?.startsWith("recruit-"))this.recruit(b.eventId.slice(8) as HeroId);if(event&&!p.events.includes(event.id)){p.events.push(event.id);p.tokens+=event.tokens;}if(b.boss||Math.random()<b.dropChance){const options=SHOP.filter(i=>i.gear&&i.minLevel<=level(p)),gear=options[Math.floor(Math.random()*options.length)]?.gear;if(b.boss&&gear){let id=gear,n=2;while(p.owned.includes(id))id=`${gear}@${n++}`;p.owned.push(id);p.unseenGear.push(id);lootGear=id;for(let extra=1;extra<b.difficulty;extra++){const base=options[Math.floor(Math.random()*options.length)]?.gear;if(!base)continue;let next=base,j=2;while(p.owned.includes(next))next=`${base}@${j++}`;p.owned.push(next);p.unseenGear.push(next);}lootText=b.difficulty>1?` · ${b.difficulty} equipamentos obtidos`:` · ${gearById(id)?.name||'equipamento'} obtido`;}else{this.state.potions++;lootText=' · +1 Poção';}}this.gainXp(b.xp);if(b.entityId==='selo')this.state.stage=4;else if(!b.boss&&!b.eventId?.startsWith('recruit-'))this.respawns[b.entityId]=this.now+12;this.state.heroes.forEach(h=>{if(h.hp===0)h.hp=1;});}
  this.state.battle=null;this.state.mode='world';this.save();this.emit();if(b.result==='victory')this.notify(`Vitória: +${b.credits} créditos · +${b.xp} XP${lootText}${level(this.state.progress)>beforeLevel?` · nível ${level(this.state.progress)} · +${level(this.state.progress)-beforeLevel} ponto por herói`:''}.`,lootGear?'gear':'rewards',lootGear);
  if(b.result==='victory'&&b.boss)this.playCutscene(b.entityId==='cinder'?'cinder-silence':b.entityId==='eco'?'echo-silence':'silence');
  else if(b.result==='victory')this.toast(b.eventId?.startsWith('recruit-')?`${heroBases().find(h=>h.id===b.eventId!.slice(8))?.name} aceitou o duelo e entrou para o Grupo!`:b.eventId?`Fenda selada · +${EVENTS.find(e=>e.id===b.eventId)?.tokens} Fichas de Eco · +${b.xp} XP.`:`Vitória • +${b.credits} créditos · +${b.xp} XP.${commonKills(this.state.progress)%3===0?' +1 Ficha de Eco.':''} A criatura retorna em 12 segundos.`);
 }
 useItem(type:'potion'|'ether',target:HeroId){if(this.state.mode!=='world')return false;const h=this.state.heroes.find(v=>v.id===target)!;if(type==='potion'){if(this.state.potions===0||h.hp===h.maxHp)return false;this.state.potions--;h.hp=Math.min(h.maxHp,h.hp+45);}else{if(this.state.ethers===0||h.mp===h.maxMp)return false;this.state.ethers--;h.mp=Math.min(h.maxMp,h.mp+24);}this.save();this.emit();return true;}

 skills(id:HeroId){const scale=this.magicScale(id),p=this.state.progress;return [...SKILLS[id],...EXTRA_SKILLS[id].filter(sk=>p.learned.includes(sk.node))].map(sk=>{
   const signature=signatureTechnique(sk.id);
   if(signature){let description=signature.description;if(signature.damage)description=description.replace(/^\d+/,String(Math.round((signature.damage+spellBonus(p,id))*scale)));if(signature.heal)description=description.replace(/Restaura \d+/,`Restaura ${this.healPower(id,signature.heal)}`);if(signature.woundedHeal)description=description.replace(/cura \d+/,`cura ${this.healPower(id,signature.woundedHeal)}`);if(signature.selfHeal)description=description.replace(/recupera \d+/,`recupera ${this.healPower(id,signature.selfHeal)}`);return {...sk,description};}
   const base=({cut:38,stain:26,shard:32,blind:22,bleed:30,freeze:24,eclipse:34,drain:26,blaze:36,voltcut:34,arc:28,darkveil:24,flamewall:28,rupture:32,nightseal:38,nova:48,ashseal:30,tidecut:36,'umbra-seal':25,'echo-strike':32,'vine-strike':32} as Record<string,number>)[sk.id],bonus=sk.id==='cut'&&p.learned.includes('seiji-ink')||sk.id==='shard'&&p.learned.includes('ophelia-ice')||['eclipse','blaze','voltcut'].includes(sk.id)&&p.learned.includes(`${id}-power`)?8:0;
   if(['mend','cleanse','rekindle','shadowrest','margem','garden-heal'].includes(sk.id))return {...sk,description:`Restaura ${this.healPower(id,({mend:36,cleanse:25,rekindle:28,shadowrest:24,margem:32,'garden-heal':38} as Record<string,number>)[sk.id])} HP${['cleanse','rekindle','margem'].includes(sk.id)?' e remove estados.':sk.id==='shadowrest'?' de Marin.':'.'} Também na exploração.`};
   return {...sk,description:sk.description.replace(/^\d+/,String(Math.round((base+bonus+spellBonus(p,id))*scale)))};
  });}
 magicScale(id:HeroId){return (setCount(this.state.progress,id,'veil')>=6?1.25:1)*(setCount(this.state.progress,id,'lunar')>=6?1.2:1);}
 attackPower(id:HeroId){const h=this.state.heroes.find(h=>h.id===id)!;return Math.round((h.atk+(id==='ophelia'?5:6))*(setCount(this.state.progress,id,'wolf')>=6?1.25:1));}
 skillCost(id:HeroId,cost:number){return cost===0?0:Math.max(1,cost-(setCount(this.state.progress,id,'veil')>=3?2:0));}
 healPower(id:HeroId,base:number){const p=this.state.progress;return Math.round((base+spellBonus(p,id)-cosmeticRank(p,id,'magic')+cosmeticRank(p,id,'heal')*2+(base===36&&p.learned.includes('ophelia-master')?14:0))*this.magicScale(id));}
 gainXp(amount:number){const p=this.state.progress,before=level(p);p.xp+=amount;const gained=level(p)-before;if(gained>0){for(const id of PLAYABLE_HERO_IDS)p.points[id]=(p.points[id]||0)+gained;const old=this.state.heroes;this.state.heroes=deriveHeroes(p,old).map((h,i)=>({...h,hp:Math.min(h.maxHp,h.hp+h.maxHp-old[i].maxHp),mp:Math.min(h.maxMp,h.mp+h.maxMp-old[i].maxMp)}));}}
 learn(id:string){if(this.state.mode!=='world')return false;const n=TREE.find(n=>n.id===id),p=this.state.progress;if(!n||p.learned.includes(id)||p.points[n.hero]<n.cost||n.requires&&!p.learned.includes(n.requires))return false;p.points[n.hero]-=n.cost;p.learned.push(id);this.state.heroes=deriveHeroes(p,this.state.heroes);this.save();this.toast(`Aprendeu ${n.name}.`);return true;}
 equip(hero:HeroId,id:string){if(this.state.mode!=='world')return false;const p=this.state.progress,item=gearById(id);if(!item||!p.owned.includes(id)||(item.minLevel||1)>level(p)||item.hero&&item.hero!==hero)return false;
  for(const h of PLAYABLE_HERO_IDS)for(const slot of SLOTS)if(p.equipment[h][slot]===id)delete p.equipment[h][slot];p.equipment[hero][item.slot]=id;this.recalculateGear();return true;}
 unequip(hero:HeroId,slot:Slot){if(this.state.mode!=='world')return false;delete this.state.progress.equipment[hero][slot];this.recalculateGear();return true;}
 recalculateGear(){const p=this.state.progress;this.state.heroes=deriveHeroes(p,this.state.heroes);for(const h of PLAYABLE_HERO_IDS)for(const set of Object.keys(SETS) as (keyof typeof SETS)[]){const n=setCount(p,h,set);if(n>=3)p.metrics.set3=true;if(n===6)p.metrics.set6=true;}this.save();this.emit();}
 claimBestiary(id:string,goal:number){if(this.state.mode!=='world')return false;const monster=BESTIARY.find(m=>m.id===id),boss=BOSS_REWARDS[id];if(!monster||!(monster.set?[5,25,50].includes(goal):!!boss&&goal===1))return false;const p=this.state.progress,key=`${id}-${goal}`;if((p.kills[id]||0)<goal||p.bestiaryClaims.includes(key))return false;p.bestiaryClaims.push(key);if(monster.set){const index=[5,25,50].indexOf(goal)*2;for(const slot of SLOTS.slice(index,index+2)){const item=`${monster.set}-${slot}`;if(!p.owned.includes(item)){p.owned.push(item);p.unseenGear.push(item);}}}else{if(!p.owned.includes(boss.gear)){p.owned.push(boss.gear);p.unseenGear.push(boss.gear);}p.tokens+=boss.tokens;}this.save();this.notify(monster.set?`${SLOTS.slice([5,25,50].indexOf(goal)*2,[5,25,50].indexOf(goal)*2+2).map(slot=>GEAR[`${monster.set}-${slot}`].name).join(' + ')} recebidos.`:`${GEAR[boss.gear].name} e ${boss.tokens} Fichas de Eco recebidos.`,'gear',p.unseenGear.at(-1));return true;}
 claimQuest(id:string){if(this.state.mode!=='world')return false;const q=QUESTS.find(q=>q.id===id),p=this.state.progress;if(!q||q.value(this.state)<q.goal||p.questClaims.includes(id)||q.request&&!p.requests.includes(q.request))return false;p.questClaims.push(id);p.tokens++;this.state.credits+=q.reward;for(const id of PLAYABLE_HERO_IDS)p.points[id]=(p.points[id]||0)+q.points;if(q.xp)this.gainXp(q.xp);this.save();this.notify(`Missão concluída: +${q.reward} créditos, +${q.points} ponto por herói e +1 Ficha de Eco.`,'skills');return true;}
 claimAchievement(id:string){if(this.state.mode!=='world')return false;const a=ACHIEVEMENTS.find(a=>a.id===id),p=this.state.progress;if(!a||!a.test(this.state)||p.achievementClaims.includes(id))return false;p.achievementClaims.push(id);this.state.credits+=a.reward;const unlocked=this.unlockCarmillaIfReady();this.save();this.notify(`Conquista recebida: +${a.reward} créditos.${unlocked?' Carmilla 5★ entrou para o Grupo!':''}`,'achievements',id);return true;}
 buy(id:string){if(this.state.mode!=='world'||!this.map.entities.some(e=>e.kind==='shop'))return false;const item=SHOP.find(i=>i.id===id);if(!item||!this.state.progress.masterMode&&this.state.credits<item.price||level(this.state.progress)<item.minLevel)return false;if(!this.state.progress.masterMode)this.state.credits-=item.price;if(item.gear){let copy=item.gear,n=2;while(this.state.progress.owned.includes(copy))copy=`${item.gear}@${n++}`;this.state.progress.owned.push(copy);this.state.progress.unseenGear.push(copy);}else if(id==='potion')this.state.potions++;else if(id==='ether')this.state.ethers++;else if(id==='remedy')this.state.remedies++;this.state.progress.metrics.purchases++;this.save();this.notify(`${item.name} comprado.`,item.gear?'gear':'bag',item.gear?this.state.progress.unseenGear.at(-1):id);return true;}
 activateMasterMode(){if(this.state.mode!=='world'||this.state.progress.masterMode)return false;this.state.progress.masterMode=true;this.unlockCarmillaIfReady();this.save();this.toast('Modo Mestre ativo · Carmilla 5★ no Grupo; invocações e compras sem custo.');return true;}
 useFieldSkill(id:string,target:HeroId='seiji'){
  if(this.state.mode!=='world')return false;const p=this.state.progress,healer=this.state.heroes.find(h=>h.id==='ophelia')!,ink=this.state.heroes.find(h=>h.id==='seiji')!;
  if(id==='mend'||id==='cleanse'||id==='margem'){const caster=id==='margem'?this.state.heroes.find(h=>h.id==='beatriz'):healer;if(!caster)return false;if(id==='cleanse'&&!p.learned.includes('ophelia-cleanse'))return false;const ally=this.state.heroes.find(h=>h.id===target);if(!ally)return false;const cost=this.skillCost(caster.id,id==='mend'?9:id==='margem'?11:12);if(caster.hp<=0||caster.mp<cost||ally.hp===ally.maxHp)return false;caster.mp-=cost;ally.hp=Math.min(ally.maxHp,ally.hp+this.healPower(caster.id,id==='mend'?36:id==='margem'?32:25));p.metrics.heals++;this.state.fieldEffect={kind:'heal',started:Date.now()};this.save();this.toast(`${caster.name} restaura as forças do grupo.`);return true;}
  if(id==='shadowrest'||id==='rekindle'){const heroId=id==='shadowrest'?'marin':'gabriel',caster=this.state.heroes.find(h=>h.id===heroId),ally=id==='shadowrest'?caster:this.state.heroes.find(h=>h.id===target),cost=this.skillCost(heroId,id==='shadowrest'?8:10);if(!p.learned.includes(`${heroId}-field`)||!caster||caster.hp<=0||!ally||ally.hp===ally.maxHp||caster.mp<cost)return false;caster.mp-=cost;ally.hp=Math.min(ally.maxHp,ally.hp+this.healPower(heroId,id==='shadowrest'?24:28));p.metrics.heals++;this.state.fieldEffect={kind:'heal',started:Date.now()};this.save();this.toast(`${caster.name} restaura as forças de ${ally.name}.`);return true;}
  if(id==='ink-focus'){const hero=this.state.heroes.find(h=>h.id==='seiji');if(!hero||!p.learned.includes('seiji-field')||hero.hp<=10||hero.mp===hero.maxMp)return false;hero.hp-=10;hero.mp=Math.min(hero.maxMp,hero.mp+8);this.save();this.toast('Concentração: −10 HP, +8 MP.');return true;}
  const technique=Object.entries(FIELD_TECHNIQUES).flatMap(([hero,list])=>list.map(t=>({...t,hero:hero as HeroId}))).find(t=>t.id===id&&t.timed),caster=technique&&this.state.heroes.find(h=>h.id===technique.hero);if(!technique||!caster||caster.hp<=0||!!technique.node&&!p.learned.includes(technique.node)||caster.mp<this.skillCost(caster.id,technique.cost))return false;
  caster.mp-=this.skillCost(caster.id,technique.cost);p.fieldUntil[id]=Date.now()+15000;const entity=this.activeEntities().find(e=>e.id===(id==='ice-bridge'?'agua-jardim':'glifo'));if(entity&&dist(entity,this.state.position)<=2.4&&!p.field.includes(id))p.field.push(id);for(const point of this.activeEntities().filter(e=>e.fieldSkill===id&&dist(e,this.state.position)<=2.4))if(!p.field.includes(`found:${point.id}`))p.field.push(`found:${point.id}`);
  this.state.fieldEffect={kind:id==='shadow-step'?'shadow':combatElement(caster.id,id),started:Date.now()};this.soundEffect('cast');this.clearMovement();this.save();this.toast(`${technique.name} ativa por 15 segundos.`);return true;
 }

 playCutscene(id:string,onEnd?:()=>void,replay=false){if(!CUTSCENES[id])return false;if(replay&&(this.state.mode!=='world'||CUTSCENES[id].map!==this.state.map||!this.state.progress.seen.includes(id)))return false;this.clearMovement();this.state.mode='cutscene';this.state.cutscene={id,index:0,replay};this.afterDialogue=onEnd||null;this.emit();return true;}
 nextCutscene(){const c=this.state.cutscene;if(!c)return;const scene=CUTSCENES[c.id];if(c.index<scene.beats.length-1){c.index++;this.emit();}else this.finishCutscene();}
 finishCutscene(){const c=this.state.cutscene;if(!c)return;this.state.cutscene=null;this.state.mode='world';if(!this.state.progress.seen.includes(c.id))this.state.progress.seen.push(c.id);const cb=this.afterDialogue;this.afterDialogue=null;cb?.();this.save(true);this.emit();}
 dispose(){this.sound=false;const audio=this.audio;this.audio=null;if(audio&&audio.state!=='closed')void audio.close().catch(()=>{});}
}
