import type {Entity,HeroId,MapId} from './data';

export const QUEST_CHAPTER_V31='Ecos que Escolhem';
export const CRYSTALS_PER_PULL_V31=160;
export type QuestCategoryV31='long'|'medium'|'short'|'tutorial';
export type QuestEventKindV31='site'|'move'|'travel'|'leader'|'crystal'|'action'|'victory'|'ui'|'track';
export type QuestObjectiveV31={id:string;label:string;event:QuestEventKindV31;target?:string;goal:number};
export type QuestChoiceV31={id:string;label:string;text:string;correct?:boolean;consequence?:string};
export type QuestSiteV31={id:string;label:string;map:MapId;x:number;y:number;kind:'evidence'|'dialogue'|'puzzle'|'combat'|'choice'|'delivery';hero:HeroId;text:string[];choices?:QuestChoiceV31[];combat?:Pick<Entity,'family'|'asset'|'hp'|'damage'>};
export type QuestStepV31={id:string;title:string;description:string;objectives:QuestObjectiveV31[];sites:QuestSiteV31[];sequence?:boolean};
export type QuestDefV31={id:string;name:string;category:QuestCategoryV31;description:string;giver:string;minStage:number;rewardPulls:number;steps:QuestStepV31[];cinematic?:boolean};
const site=(id:string,label:string,map:MapId,x:number,y:number,hero:HeroId,text:string[],kind:QuestSiteV31['kind']='evidence',choices?:QuestChoiceV31[]):QuestSiteV31=>({id,label,map,x,y,hero,text,kind,choices});
const fight=(id:string,label:string,map:MapId,x:number,y:number,hero:HeroId,text:string[],family:NonNullable<Entity['family']>,asset:string,hp:number,damage:number):QuestSiteV31=>({...site(id,label,map,x,y,hero,text,'combat'),combat:{family,asset,hp,damage}});
const step=(id:string,title:string,description:string,...sites:QuestSiteV31[]):QuestStepV31=>({id,title,description,sites,objectives:sites.map(s=>({id:s.id,label:s.label,event:'site',target:s.id,goal:1}))});
const eventStep=(id:string,title:string,description:string,event:QuestEventKindV31,target?:string,goal=1):QuestStepV31=>({id,title,description,sites:[],objectives:[{id,label:title,event,target,goal}]});
const choice=(id:string,label:string,text:string,consequence:string):QuestChoiceV31=>({id,label,text,consequence});
const answer=(id:string,label:string,text:string,correct=false):QuestChoiceV31=>({id,label,text,correct});
const quest=(id:string,name:string,category:QuestCategoryV31,description:string,giver:string,minStage:number,steps:QuestStepV31[]):QuestDefV31=>({id,name,category,description,giver,minStage,steps,rewardPulls:category==='long'?5:category==='medium'?3:1,...(category==='long'?{cinematic:true}:{})});

/** Authored stages are prospective: accepting a story never cashes in old kills or opened chests. */
export const QUESTS_V31:QuestDefV31[]=[
 quest('long-tinta','O nome que o mar apagou','long','Uma barqueira desapareceu dos registros, mas o cais ainda guarda os gestos de quem ela salvou. Reconstrua a memória sem transformá-la em propriedade da Academia.','Seiji · Shin e Umbra',5,[
  step('pedido','A cadeira vazia','Encontre Seiji na Mesa de Âmbar e escute o relato que ninguém consegue terminar.',site('pedido','Seiji · a cadeira sem dona','porto',18,7,'seiji',['Há quatro cadeiras e três nomes no livro do cais. A quarta tem as marcas de alguém que voltou de muitas travessias.','Shin sente tinta sob a sal; Umbra percebe uma sombra que não pertence a nenhum de nós. Quero descobrir quem falta.'],'dialogue')),
  step('cais','Três vestígios, uma vida','Investigue o nó de resgate, a lista de passageiros e a soleira. Cada pista explica um gesto diferente.',site('corda','Nó de resgate','porto',11,16,'marin',['A corda está gasta do lado de dentro: alguém puxou pessoas para bordo, não cargas. Umbra preserva a sombra de duas mãos juntas.']),site('lista','Lista molhada','porto',21,16,'seiji',['Nove passageiros chegaram. A décima linha foi raspada depois, em tinta da Academia. Não foi o mar que apagou o nome.']),site('soleira','Marca na soleira','porto',16,8,'seiji',['A mesma pequena espiral aparece na cadeira e na porta. Shin recompõe três letras: I-r-i. Falta a última.'])),
  step('arquivo','O apagamento foi uma ordem','Compare a ata da maré com o registro de admissões no Arquivo.',site('ata','Ata da travessia','arquivo',4,12,'seiji',['A ata diz: “Iria atravessou com os últimos aprendizes durante a ruptura”. A linha seguinte chama a operação de transporte sem responsável.']),site('rasura','Registro de admissões','arquivo',17,11,'marin',['Umbra encontra a rasura por baixo da assinatura. Não apagaram um erro: esconderam que a Academia dependia de uma trabalhadora do cais.'])),
  step('nome','Uma identidade, não uma senha','Monte o nome pela última letra vista na ata. O erro não destrói as provas.',site('nome','Recompor o nome','arquivo',10,12,'seiji',['A cadeira guardou I-r-i. A ata conserva a letra final. Qual nome pertence à barqueira?'],'puzzle',[answer('iria','Iria','Shin une o traço final. O nome resiste: Iria.',true),answer('iris','Íris','A ata não termina em s. Volte à letra final, não à flor.'),answer('ira','Ira','A soleira conserva duas letras i. Falta preservar uma delas.')])),
  step('resistencia','O fiscal sem rosto','Uma sombra da ordem de apagamento fecha a passagem do testemunho. Vença sem perder as provas.',fight('fiscal','Fiscal da rasura','subsolo',16,16,'marin',['A sombra repete “transporte sem responsável”. Ela não consegue dizer Iria. Vamos abrir passagem para quem pode.'],'sombra','shadow',230,18)),
  step('testemunho','O que permanece quando um nome volta','Retorne ao cais e deixe que a cadeira seja uma testemunha, sem inventar uma voz para a morta.',site('testemunho','A cadeira de Iria','porto',18,7,'marin',['Umbra devolve apenas a sombra da cadeira, vazia. Lembrar não é obrigar alguém a continuar trabalhando depois da morte.','Seiji: Podemos tornar a prova pública. Também podemos deixá-la sob o cuidado das famílias, com cópia protegida contra outra rasura.'],'dialogue')),
  step('destino','Quem guarda o relato?','Decida o destino da memória. Ambas as decisões devolvem Iria à história do cais.',site('destino','Entregar o relato de Iria','arquivo',10,14,'seiji',['Shin guarda uma cópia que não pode ser apagada. Quem deverá conduzir as próximas leituras?'],'choice',[choice('publico','Publicar no registro do cais','O nome de Iria será lido em cada reunião da maré. A Academia deverá reconhecer sua dívida.','O registro público do cais reconhece Iria como barqueira e salvadora.'),choice('familias','Entregar às famílias, sob proteção','As famílias decidem quando contar. O arquivo preserva a prova, sem tomar posse da lembrança.','As famílias do cais guardam a memória de Iria; a cópia fica protegida no Arquivo.')])),
 ]),
 quest('long-geada','O jardim que guardou o inverno','long','Mika encontra uma raiz que congelou para guardar o último cuidado de uma jardineira. Cure o solo e escolha o que a primavera deve preservar.','Ophelia · Mika e Ava',5,[
  step('pedido','Um frio que protege','Escute Ophelia e Mika no Domo.',site('pedido','Mika · a raiz silenciosa','domo',9,9,'ophelia',['Mika não está tremendo. Está ouvindo uma raiz. Este gelo foi feito para proteger alguma coisa, mas já está sufocando o jardim.','Ava encontrou a mesma geada no Jardim Lunar. Precisamos ouvir as duas margens antes de curar.'],'dialogue')),
  step('amostras','Dois solos, duas faltas','Examine a folha do Domo e a água lunar, sem arrancar plantas vivas.',site('folha','Folha sob a geada','domo',7,10,'ava',['A folha caiu sozinha. Os veios estão vivos; a raiz recebe luz, mas não consegue devolver água ao solo.']),site('agua','Água à margem lunar','jardim-lunar',12,10,'ophelia',['Mika percebe sal nas bordas do gelo. A geada recebeu água do cais durante a crise. Precisamos separar o sal, não quebrar toda a raiz.'])),
  step('cura','Cuidar exige ordem','Escolha o cuidado que evita choque térmico. Mika realizará o trabalho sem consumir MP do grupo.',site('cura','Mika · tratar a raiz','jardim-lunar',18,8,'ophelia',['A água salgada está presa no gelo. Qual sequência preserva os veios vivos?'],'puzzle',[answer('lento','Drenar o sal, aquecer aos poucos, irrigar','Mika conduz a água para fora e alivia a geada sem romper os veios.',true),answer('fogo','Derreter tudo de uma vez','A folha do Domo mostrou veios vivos. O choque térmico os romperia.'),answer('agua','Irrigar antes de drenar','Mais água levaria o sal para as raízes vizinhas. Primeiro precisamos drená-lo.')])),
  step('vigia','O jardim não é uma fortaleza','O antigo vigia impede qualquer alteração no canteiro. Interrompa a ordem, preservando as sementes.',fight('vigia','Vigia do canteiro fechado','jardim-lunar',19,17,'ophelia',['A sentinela chama todo crescimento de invasão. A ordem de conservar virou uma ordem de impedir a vida.'],'runewarden','runewarden',300,22)),
  step('memoria','A última rega','Leia o caderno da jardineira e examine a primeira flor que voltou.',site('caderno','Caderno da última rega','domo',10,14,'ava',['“Se não houver quem volte, que o inverno conserve uma manhã.” Não era uma ordem para prender o jardim para sempre.']),site('flor','A primeira flor descongelada','jardim-lunar',20,10,'ophelia',['Mika guardou o gesto da última rega. Podemos conservar um canteiro como testemunho ou repartir essa memória em sementes.'])),
  step('escolha','O lugar da primavera','Escolha um cuidado permanente para a memória.',site('escolha','O futuro do jardim','jardim-lunar',18,8,'ophelia',['Há espaço para viver e para lembrar. Nenhuma opção precisa aprisionar todo o jardim.'],'choice',[choice('testemunho','Preservar um canteiro de testemunho','Mika conservará só este pequeno canteiro. O restante do jardim poderá crescer livre.','Um canteiro de geada guarda a última rega; as demais raízes crescem livres.'),choice('sementes','Semear a memória nas novas flores','Ava distribuirá sementes. A última rega sobreviverá em cuidados novos, não num inverno imóvel.','A memória da jardineira acompanha sementes distribuídas pelo Domo e Jardim Lunar.')])),
  step('retorno','Voltar é parte da cura','Conte a Ava o cuidado escolhido e combine a próxima visita.',site('retorno','Ava · compromisso de cuidado','domo',9,9,'ava',['A cura não termina quando a cor volta. Registraremos quem cuida, e ninguém precisará carregar o inverno sozinho.','Ophelia: Mika quer voltar na próxima floração. Eu também.'],'delivery')),
 ]),
 quest('long-brasa','A promessa sob as cinzas','long','Uma forja prometeu arder enquanto houvesse alguém a proteger. Gabriel e Dante procuram uma maneira de libertar a promessa sem abandonar quem precisa de abrigo.','Gabriel · Dante',5,[
  step('pedido','Uma promessa sem descanso','Converse com Gabriel no acampamento.',site('pedido','Gabriel · a vigília de Dante','ashwood',14,9,'gabriel',['Dante observa uma viga que ainda aquece sob as cinzas. A forja prometeu não apagar. Ninguém perguntou se ela podia descansar.','Antes de destruir essa promessa, precisamos saber quem ainda depende dela.'],'dialogue')),
  step('restos','O que foi salvo','Investigue a viga do abrigo e as marcas da oficina.',site('viga','Viga protegida por Dante','ashwood',16,7,'gabriel',['A viga está queimada por fora, mas seca por dentro. Serviu de teto quando a mata desabou.']),site('oficina','Marcas de aprendizes','ashwood',7,11,'gabriel',['Cada aprendiz marcou sua própria ferramenta. A oficina não era um arsenal. Ensinava pessoas a construir uma casa.'])),
  step('pira','Ouvir antes de apagar','Examine a inscrição da pira e encontre a semente protegida nas cinzas.',site('inscricao','Promessa gravada na pira','ashpyre',7,8,'gabriel',['“Não deixarei ninguém ao frio.” A inscrição não diz “queimarei para sempre”. Transformaram cuidado em servidão.']),site('semente','Semente entre cinzas frias','ashpyre',13,12,'gabriel',['Dante afasta a cinza com o bico. Há uma semente intacta onde o calor foi mais brando. O fogo também soube preservar.'])),
  step('protecao','Um caminho para o abrigo','Afaste o predador que cerca os restos do abrigo.',fight('predador','Lobo junto ao abrigo','ashwood',20,15,'gabriel',['Dante guia o lobo para longe das vigas. Vamos impedir que a reconstrução vire outra fuga.'],'ashwolf','ashwolf',270,21)),
  step('libertar','Cuidar sem se prender','Escolha como extinguir a ordem de vigília, sem apagar o braseiro útil.',site('libertar','Gabriel · romper o juramento','ashpyre',7,8,'gabriel',['A promessa está escrita na pedra, não na brasa. O que devemos libertar primeiro?'],'puzzle',[answer('ordem','Desfazer a ordem; conservar calor suficiente','Gabriel rompe a inscrição de servidão. O braseiro volta a responder ao cuidado das pessoas.',true),answer('semente','Queimar a semente como pagamento','A semente sobreviveu graças ao fogo brando. Não é dívida nem combustível.'),answer('tudo','Apagar tudo e deixar o abrigo frio','Isso romperia também o cuidado que a promessa pretendia oferecer.')])),
  step('futuro','Uma forja que pode escolher','Decida a primeira função da pira livre.',site('futuro','O primeiro fogo livre','ashpyre',11,12,'gabriel',['Dante pousa para descansar pela primeira vez desde que chegamos. Podemos usar a pira para um abrigo aberto ou uma oficina dirigida por seus aprendizes.'],'choice',[choice('abrigo','Abrir um abrigo para viajantes','O primeiro fogo livre aquecerá quem chegar da mata, sem exigir juramento de permanência.','A pira se torna abrigo aberto; a vigília é repartida entre voluntários.'),choice('oficina','Reabrir uma oficina dos aprendizes','Cada aprendiz terá voz sobre a forja. Ferramentas servirão para casas, não para outra prisão.','A oficina livre da pira pertence aos aprendizes, com pausas e decisões coletivas.')])),
  step('plantio','Amanhã exige mãos','Plante a semente no acampamento e entregue o plano a quem ficará.',site('plantio','Semente da pira livre','ashwood',14,9,'gabriel',['Gabriel cobre a semente com terra fria. Dante vigiará só enquanto alguém precisar; depois, poderá dormir.','Uma promessa pode continuar importante sem continuar sendo uma corrente.'],'delivery')),
 ]),
 quest('long-trovao','O sino que não aceitava o silêncio','long','O sino da Vigília conserva uma mensagem que uma antiga ordem proibiu de chegar ao cais. Max e Vajra precisam conduzir o sinal, não aumentar seu volume.','Max · Vajra',5,[
  step('pedido','O sino mudo','Encontre Max na torre caída.',site('pedido','Max · escutar Vajra','vigilia',12,4,'max',['Vajra escuta três pulsos no sino. Ele não está quebrado: a mensagem foi desviada para o observatório.','Se só aumentarmos a carga, queimaremos o que tentamos ouvir. Primeiro, o caminho.'],'dialogue')),
  step('sinais','Ler os intervalos','Registre o pulso da torre e o retorno do astrolábio.',site('torre','Pulso sob o sino','vigilia',16,8,'max',['O sino envia um pulso curto, um intervalo e dois pulsos longos. O intervalo é parte da mensagem.']),site('orbita','Retorno da segunda órbita','observatorio',10,16,'max',['O astrolábio devolve três pulsos contínuos. A ordem de silêncio removeu os intervalos e transformou todas as vozes numa só.'])),
  {...step('rota','Conduzir sem esmagar','Conecte primeiro a terra de retorno no Observatório, depois o sino na Vigília e finalmente a órbita livre. Uma conexão fora de ordem não perde progresso. Vajra conduz sem custo de MP.',site('terra','Vajra · terra de retorno','observatorio',16,12,'max',['Vajra fixa o primeiro prego na terra de retorno. A carga agora tem por onde sair. O próximo contato precisa ser o sino da Vigília.']),site('sino','Vajra · contato do sino','vigilia',15,7,'max',['O sino devolve curto–pausa–longo–longo. Agora podemos levar esse intervalo à órbita livre, sem acúmulo de carga.']),site('orbita-livre','Vajra · órbita livre','observatorio',16,15,'max',['Vajra fecha a última ligação. A corrente cruza a órbita livre e conserva cada intervalo. A mensagem encontrou um caminho.'])),sequence:true},
  step('guardiao','A ordem ainda responde','Vençam a sentinela que protege o filtro de silêncio.',fight('filtro','Sentinela do filtro de silêncio','observatorio',19,13,'max',['A sentinela identifica uma mensagem como uma falha. Ela precisa perder o controle do filtro para que a voz passe.'],'runewarden','runewarden',320,23)),
  step('mensagem','Uma voz que atravessou a noite','Escute a mensagem libertada no sino e confira a lista de destinatários no cais.',site('mensagem','Mensagem no sino','vigilia',12,4,'max',['“Chegamos ao cais. Os aprendizes estão vivos. Não esperem mais junto à porta.” O silêncio manteve famílias esperando por anos.']),site('destinatarios','Lista de destinatários','porto',22,9,'max',['Os nomes estão legíveis. A notícia era de vida, não de uma vitória da Academia. Vajra guarda a cadência, sem tomar a voz para si.'])),
  step('envio','A quem pertence a notícia?','Decida como a mensagem voltará a circular.',site('envio','Devolver a mensagem','porto',22,9,'max',['Podemos transmitir a prova do silêncio imposto a toda a cidade, ou entregar primeiro a notícia a cada família.'],'choice',[choice('cidade','Transmitir à cidade com contexto','O sino anunciará também por que esteve mudo. A notícia deixará de ser segredo institucional.','O sino transmite a mensagem e denuncia publicamente o filtro de silêncio.'),choice('familias','Entregar primeiro às famílias','As famílias ouvirão antes de qualquer cerimônia. Depois decidirão como compartilhar sua notícia.','As famílias recebem primeiro a mensagem; a divulgação fica sob sua decisão.')])),
  step('retorno','O sino pode repousar','Volte à torre e desligue a repetição forçada.',site('retorno','Vajra · último pulso da vigília','vigilia',16,8,'max',['Vajra retira o prego da repetição. O sino tocará quando houver uma mensagem, não para obrigar alguém a continuar esperando.'],'delivery')),
 ]),
 quest('long-nulo','A última página em branco','long','Um índice registra decisões antes de serem tomadas. Orfeu procura os limites desse mecanismo: não para escolher no lugar dos outros, mas para devolver a cada pessoa o próximo gesto.','Orfeu',5,[
  step('pedido','Uma leitura que chega cedo demais','Ouça Orfeu no Arquivo.',site('pedido','Orfeu · o índice fechado','arquivo',14,14,'orfeu',['Este livro diz que amanhã você obedecerá. A tinta foi escrita ontem. Quero saber se ele prevê nossas escolhas ou impede que existam outras.'],'dialogue')),
  step('provas','Previsão ou coerção?','Compare a anotação apagada e a trava do subterrâneo.',site('indice','Índice das decisões previstas','arquivo',5,12,'orfeu',['“O visitante voltará sem perguntar.” Uma margem conserva a pergunta que foi raspada. A previsão depende do apagamento.']),site('trava','Trava da página prescrita','subsolo',14,17,'orfeu',['A trava fecha quando alguém tenta seguir a saída não registrada. O livro não vê o futuro: administra as portas.'])),
  step('limite','A anti-magia não escolhe por ninguém','Separe fato passado de ordem futura para abrir a trava.',site('limite','Orfeu · distinguir registro e ordem','subsolo',14,17,'orfeu',['Qual frase pode ficar no arquivo sem comandar a próxima pessoa?'],'puzzle',[answer('fato','“Ontem alguém abriu esta porta.”','Orfeu mantém a memória do gesto e desfaz apenas a obrigação de repeti-lo.',true),answer('ordem','“Amanhã todos abrirão esta porta.”','Isso ainda prescreve uma decisão. Precisamos preservar o passado, sem fechar o futuro.'),answer('apagamento','“Ninguém jamais esteve aqui.”','Apagar testemunhos também retiraria das pessoas a capacidade de compreender suas escolhas.')])),
  step('executor','O destino tem um mecanismo','Desligue o executor que impede a passagem livre.',fight('executor','Executor da página prescrita','galeria',21,15,'orfeu',['Ele não sabe o que você vai escolher. Só tenta impedir tudo o que não consta no índice. Vamos romper esse mecanismo.'],'runewarden','runewarden',330,23)),
  step('branco','O espaço que não é uma falha','Examine a página em branco e o relato de quem desobedeceu.',site('branco','Página preservada em branco','galeria',16,14,'orfeu',['A última página nunca recebeu tinta. O branco não é uma omissão: alguém o protegeu para quem viesse depois.']),site('relato','Relato da primeira desobediência','arquivo',17,12,'orfeu',['“Deixei uma página porque não conheço você.” Não é uma profecia. É um gesto de respeito.'])),
  step('escolha','Uma liberdade que exige cuidado','Escolha o destino do índice sem transformar a decisão em uma nova ordem.',site('escolha','Orfeu · entregar a página livre','arquivo',14,14,'orfeu',['Posso desfazer a prescrição. O uso do espaço livre pertence a vocês. Não vou escrever a resposta antes.'],'choice',[choice('livre','Deixar a página aberta a cada pessoa','As prescrições são rasgadas. Cada visitante recebe espaço para decidir e registrar, inclusive para não escrever.','O Arquivo mantém uma página livre e rejeita prescrições sobre escolhas futuras.'),choice('pacto','Criar um pacto revogável de cuidado','As prescrições são rasgadas. O grupo registra compromissos de cuidado que cada participante pode recusar ou revisar.','O Arquivo adota um pacto de cuidado revogável, com direito explícito de saída.')])),
  step('devolver','Nenhuma última palavra','Volte à Galeria e abra a saída que o índice recusava.',site('devolver','A saída sem previsão','galeria',16,14,'orfeu',['Orfeu rompe a última trava, sem preencher a página. Hoje a porta está aberta. O que virá depois não precisa obedecer ao livro.'],'delivery')),
 ]),
 quest('medium-mare','A régua das marés','medium','A marca de cheia protege o cais, mas duas réguas discordam. Procure quem ganha quando um risco desaparece do mapa.','Beatriz',0,[
  step('pedido','Medir para quem?','Leia o pedido de Beatriz no cais.',site('pedido','Beatriz · régua do cais','porto',23,13,'beatriz',['A régua nova chama a última cheia de maré normal. Os barcos contam outra história. Compare as marcas antes de validar a rota.'],'dialogue')),
  step('medidas','Duas marcas e um abrigo','Compare a régua antiga e a soleira do abrigo.',site('velha','Marca antiga da cheia','porto',11,15,'beatriz',['A água deixou uma faixa acima da régua nova. A medição foi deslocada, não corrigida.']),site('abrigo','Soleira do abrigo do cais','porto',18,9,'beatriz',['A soleira recebeu água na mesma altura da marca antiga. É uma confirmação independente.'])),
  step('decisao','Quem precisa saber primeiro?','Entregue a medição e escolha a primeira ação.',site('decisao','Plano para a próxima cheia','porto',23,13,'beatriz',['A rota pode ser corrigida agora. Qual aviso deve acompanhar o novo risco?'],'choice',[choice('abrigo','Sinalizar o abrigo e a rota segura','O cais marca o abrigo antes de anunciar a rota aberta.','O cais prioriza sinalização de abrigo durante cheias.'),choice('ata','Exigir a correção pública da ata','A ata antiga ficará ao lado da nova medição, impedindo outro apagamento.','O cais publica as duas medições e preserva a prova da cheia.')])),
 ]),
 quest('medium-lanternas','As lanternas que olham para baixo','medium','Uma iluminação mal dirigida deixa a saída da Galeria invisível. Siga os reflexos, recupere a lente e abra uma rota de retorno.','Marin',5,[
  step('pedido','Luz que não guia','Encontre o recado de Marin na Galeria.',site('pedido','Marin · reflexo na pedra','galeria',10,13,'marin',['A luz aponta para os troféus, não para a saída. Umbra consegue seguir os reflexos; quem chegar ferido não vai conseguir.'],'dialogue')),
  step('lente','Recuperar a lente','Afaste a sombra que guarda a lente caída.',fight('lente','Sombra junto à lente','galeria',23,11,'marin',['A lente não é tesouro. É o caminho de volta.'],'sombra','shadow',245,20)),
  step('reflexo','Um triângulo de retorno','Escolha o ajuste que direciona luz ao corredor.',site('reflexo','Ajustar a lanterna de saída','galeria',11,14,'marin',['O corredor fica ao norte; o espelho inferior aponta para os troféus. Qual ajuste conduz à saída?'],'puzzle',[answer('norte','Inclinar a lente para o corredor norte','Uma linha clara liga o cristal ao corredor de retorno.',true),answer('trofeu','Reforçar o reflexo dos troféus','A saída continuaria no escuro. O objetivo é guiar quem volta.'),answer('apagar','Apagar a lanterna','Umbra pode ver assim; os demais viajantes, não.')])),
  step('retorno','Verificar com quem passa','Confirme a rota a partir do cristal.',site('retorno','Marin · caminho iluminado','galeria',10,13,'marin',['A saída é visível daqui. Umbra recua para que o caminho não dependa de nós estarmos presentes.'],'delivery')),
 ]),
 quest('medium-correspondencia','Cartas sem destinatário','medium','Três cartas foram separadas de seus envelopes. Reúna os indícios antes de decidir se uma mensagem íntima deve virar documento público.','Seiji',0,[
  step('pedido','A caixa devolvida','Leia o pedido no Arquivo.',site('pedido','Seiji · correspondência devolvida','arquivo',13,14,'seiji',['As cartas voltaram sem envelope. Podemos encontrar os destinatários pelo que elas contam, sem publicar seus segredos.'],'dialogue')),
  step('pistas','Datas, lugares, cuidado','Leia a referência à maré e o selo de herbologia.',site('mare','Carta da maré baixa','porto',20,15,'seiji',['A carta pede uma travessia na primeira maré de primavera. A lista do cais guarda a família destinatária.']),site('selo','Selo de herbologia','domo',14,14,'ava',['O selo acompanha uma instrução de cuidado, não uma cobrança. A segunda carta pertence ao jardim.'])),
  step('entrega','Devolver sem tomar posse','Escolha como entregar a correspondência reunida.',site('entrega','Caixa de cartas reunidas','arquivo',13,14,'seiji',['As três famílias estão identificadas. O arquivo precisa preservar que entregamos, não o conteúdo íntimo de cada carta.'],'choice',[choice('lacradas','Entregar lacradas; registrar apenas o recebimento','Cada destinatário decidirá se deseja abrir sua carta.','A correspondência é entregue lacrada, com registro de recebimento.'),choice('leitura','Oferecer uma leitura acompanhada e consentida','Quem desejar poderá ouvir a carta; nenhuma leitura será obrigatória.','O Arquivo oferece leitura consentida sem publicar o conteúdo íntimo.')])),
 ]),
 quest('medium-cinzas','O peso da primeira ferramenta','medium','Uma ferramenta traz a marca de quem nunca terminou o aprendizado. Descubra sua função antes de devolvê-la à oficina.','Gabriel',5,[
  step('pedido','Uma marca sem nome','Escute o pedido no acampamento.',site('pedido','Gabriel · ferramenta incompleta','ashwood',12,11,'gabriel',['O cabo foi marcado por uma pessoa canhota. A lâmina nunca foi afiada. Quero saber o que ela pretendia construir.'],'dialogue')),
  step('funcao','Aprender com os vestígios','Examine o molde da pira e a viga do acampamento.',site('molde','Molde sem lâmina','ashpyre',12,10,'gabriel',['O molde produz uma ferramenta para abrir encaixes de madeira, não um golpe.']),site('viga','Encaixe da primeira casa','ashwood',16,12,'gabriel',['A viga tem o tamanho exato do molde. O aprendiz estava construindo uma casa.'])),
  step('escolha','Ferramenta de trabalho ou de memória','Devolva a ferramenta e decida sua primeira guarda.',site('escolha','A ferramenta do aprendiz','ashwood',12,11,'gabriel',['Podemos terminá-la para o uso coletivo ou preservá-la junto ao molde, explicando o projeto interrompido.'],'choice',[choice('uso','Terminar para o uso coletivo','A oficina concluirá a ferramenta e conservará a marca original do aprendiz.','A ferramenta do aprendiz serve à reconstrução coletiva, com sua marca preservada.'),choice('memoria','Preservar com uma réplica para uso','O original permanecerá como testemunho; a réplica continuará seu trabalho.','A oficina preserva o original e fabrica uma réplica para a reconstrução.')])),
 ]),
 quest('medium-orbita','A órbita fora do mapa','medium','Um astrolábio menor reserva uma rota para quem não se encaixa nas listas da Academia. Recalibre o aparelho sem apagar esse caminho.','Orfeu',5,[
  step('pedido','A quarta marca','Ouça Orfeu no Observatório.',site('pedido','Orfeu · a órbita omitida','observatorio',10,14,'orfeu',['O aparelho tem três anéis e quatro marcas de retorno. Uma rota existe sem constar no mapa. Não vamos chamá-la de defeito.'],'dialogue')),
  step('medir','Uma rota de visitantes','Compare a marca do Jardim com a do Observatório.',site('jardim','Marca de retorno do jardim','jardim-lunar',17,15,'orfeu',['A marca aponta para o jardim, sem exigir entrada pela Academia.']),site('torre','Marca livre do astrolábio','observatorio',16,16,'orfeu',['O anel menor confirma a mesma saída. A rota foi omitida do desenho, não da pedra.'])),
  step('calibrar','Corrigir o desenho, não a pessoa','Escolha a calibração que preserva a passagem.',site('calibrar','Anel da quarta marca','observatorio',10,14,'orfeu',['O que devemos alinhar quando a pedra e o mapa discordam?'],'puzzle',[answer('mapa','Corrigir o mapa pela passagem existente','A quarta rota passa a constar no mapa de retorno.',true),answer('porta','Fechar a passagem para caber no mapa','Isso transformaria um desenho incompleto em uma prisão.'),answer('marca','Raspar a quarta marca','Apagar a prova não corrige o caminho de quem precisa voltar.')])),
  step('relato','Dar acesso ao conhecimento','Entregue o mapa corrigido no Arquivo.',site('relato','Orfeu · mapa com quatro retornos','arquivo',14,15,'orfeu',['O registro agora admite uma chegada por fora. Quem vier depois não precisará pedir desculpas ao mapa.'],'delivery')),
 ]),
 quest('short-cadeira','Uma cadeira para quem chega','short','Repare o lugar de descanso do cais sem prometer uma chegada que ninguém pode prever.','Beatriz',0,[step('ouvir','Um lugar disponível','Leia o pedido e confira a madeira.',site('pedido','Banco do cais','porto',19,8,'beatriz',['Este banco virou uma placa de proibição. A madeira ainda aguenta alguém cansado. Vamos devolvê-lo ao uso.'])),step('devolver','Descanso sem senha','Escolha o aviso que acompanhará o banco.',site('aviso','Aviso do banco recuperado','porto',19,8,'beatriz',['O banco está firme. Que aviso ajuda quem acaba de chegar?'],'choice',[choice('aberto','“Pode descansar aqui.”','O banco não exige nome nem destino.','O banco do cais recebe viajantes sem exigir identificação.'),choice('cuidado','“Avise se precisar de ajuda.”','A Mesa de Âmbar ficará responsável pelo primeiro cuidado.','A Mesa de Âmbar oferece ajuda a quem descansa no cais.')]))]),
 quest('short-etiquetas','O rótulo que faltava','short','Uma prateleira chama uma pessoa de amostra. Corrija o catálogo usando a própria nota dela.','Seiji',0,[step('nota','Ler a margem','Encontre a nota ao lado do catálogo.',site('nota','Nota junto à prateleira','arquivo',10,11,'seiji',['“Não fui uma amostra. Eu trouxe a planta.” A assinatura é da coletora Lia. O catálogo omitiu seu trabalho.'])),step('corrigir','Restituir autoria','Escolha o novo registro.',site('registro','Rótulo da coleta','arquivo',10,11,'seiji',['A nota identifica a autora e a coleta. Qual registro é fiel ao testemunho?'],'puzzle',[answer('lia','“Planta coletada por Lia.”','O catálogo conserva a autoria e a procedência.',true),answer('academia','“Amostra produzida pela Academia.”','A margem diz que Lia trouxe a planta. A Academia não é sua autora.')]))]),
 quest('short-muda','A muda que cresce de lado','short','Uma planta se inclina para o corredor. Descubra se ela pede suporte ou uma nova posição.','Ava',0,[step('observar','Antes de endireitar','Examine luz e caule.',site('luz','Muda junto à janela','domo',14,10,'ava',['O caule é firme. A muda está seguindo a única faixa de luz que resta entre os vasos.'])),step('cuidar','Mudar o lugar','Escolha um cuidado sem forçar o caule.',site('cuidado','Ava · cuidado da muda','domo',14,10,'ava',['Ela não está quebrada. Que cuidado respeita seu crescimento?'],'puzzle',[answer('luz','Mover o vaso para a faixa de luz','Ava abre espaço junto à janela. A muda mantém seu caule intacto.',true),answer('forcar','Amarrar o caule até ficar reto','O problema é a luz, não a forma que o caule escolheu.')]))]),
 quest('short-intervalo','O valor de um intervalo','short','Vajra percebe que o metrônomo da Vigília nunca deixa ninguém respirar. Ajuste o ritmo.','Max',5,[step('escutar','Um compasso sem pausa','Escute o aparelho da torre.',site('escutar','Metrônomo da Vigília','vigilia',10,8,'max',['O aparelho repete quatro batidas sem intervalo. Vajra devolve três e espera. Essa pausa faz falta.'])),step('ritmo','Um ritmo que cabe num corpo','Reconfigure o intervalo.',site('ritmo','Vajra · intervalo do metrônomo','vigilia',10,8,'max',['Qual ajuste deixa espaço para respirar sem apagar o sinal?'],'puzzle',[answer('pausa','Três batidas e uma pausa','O sinal continua, mas já não exige um fôlego impossível.',true),answer('mais','Cinco batidas sem pausa','Mais batidas aumentariam a pressão; Vajra mostrou onde respirar.')]))]),
 quest('short-trilha','Pegadas sem caçador','short','Dante segue pegadas pequenas que levam para fora do perigo. Não transforme todo rastro em uma caçada.','Gabriel',5,[step('rastro','O rastro que recua','Examine as pegadas na mata.',site('rastro','Pegadas junto à cinza','ashwood',18,13,'gabriel',['As marcas são leves e se afastam da pira. Dante parou de rosnar: quem passou aqui procurava saída.'])),step('proteger','Proteger a saída','Afaste o predador do corredor de fuga.',fight('predador','Lobo no corredor de fuga','ashwood',21,12,'gabriel',['Vamos proteger o caminho. Não precisamos perseguir quem conseguiu sair.'],'ashwolf','ashwolf',230,19))]),
 quest('short-lacre','O lacre que não protege','short','Uma caixa de documentos está trancada para quem é citado nela. Descubra o que o lacre realmente protege.','Orfeu',0,[step('examinar','Um nome fora da caixa','Leia a inscrição do lacre.',site('examinar','Lacre de acesso do Arquivo','arquivo',17,14,'orfeu',['O documento descreve uma pessoa, mas proíbe que ela o leia. Esse lacre protege o autor contra perguntas.'])),step('acesso','Devolver direito de leitura','Escolha um acesso respeitoso.',site('acesso','Orfeu · abrir o documento','arquivo',17,14,'orfeu',['O acesso deve voltar à pessoa citada sem espalhar seus dados.'],'choice',[choice('copia','Preparar uma cópia privada para ela','A cópia ficará disponível apenas à pessoa descrita.','Pessoas citadas nos documentos podem consultar suas próprias cópias.'),choice('acompanhada','Oferecer consulta privada acompanhada','Orfeu explicará o registro apenas se a pessoa desejar.','O Arquivo oferece consulta privada assistida por consentimento.')]))]),
 quest('short-sombra','A sombra de uma árvore ausente','short','Umbra encontra sombra sem árvore. Leia a marca de quem plantou antes de decidir onde recomeçar.','Marin',0,[step('marca','A sombra preservada','Investigue a marca no jardim.',site('marca','Sombra sob o vaso vazio','domo',16,15,'marin',['A árvore foi retirada durante a crise. Umbra guardou seu desenho no chão; a placa conserva quem a plantou.'])),step('plantio','Um novo lugar','Escolha onde registrar o futuro plantio.',site('plantio','Registro da árvore ausente','domo',16,15,'marin',['Há luz aqui e espaço na margem do pátio. Qual lugar receberá a próxima árvore?'],'choice',[choice('domo','Replantar no Domo','A árvore voltará ao lugar que ainda guarda sua sombra.','O Domo reserva um canteiro para a árvore cuja sombra Umbra preservou.'),choice('patio','Levar a muda ao pátio aberto','A memória acompanharia a árvore até um lugar com mais espaço.','O pátio recebe uma muda com a memória da árvore preservada por Umbra.')]))]),
 quest('short-ponte','A ponte depois da geada','short','Uma passagem precisa continuar compreensível quando o gelo se desfizer. Planeje o retorno.','Ophelia',0,[step('margem','Uma travessia temporária','Examine o recado à margem segura.',site('margem','Recado na margem do jardim','patio',5,15,'ophelia',['O gelo oferece uma passagem temporária. Mika quer deixar um aviso que continue útil quando a água voltar.'])),step('aviso','Um retorno legível','Escolha o aviso da margem.',site('aviso','Aviso da passagem temporária','patio',5,15,'ophelia',['O aviso deve contar a verdade sobre a duração da travessia.'],'puzzle',[answer('tempo','“Gelo temporário; confira o retorno antes de cruzar.”','O aviso indica também a rota segura ao redor do jardim.',true),answer('sempre','“A ponte ficará aberta para sempre.”','A geada é temporária. Um aviso assim faria alguém depender de uma promessa falsa.')]))]),
 quest('short-orvalho','Uma gota para cada raiz','short','O reservatório do Domo irriga apenas o canteiro central. Redistribua água sem prometer abundância infinita.','Ava',0,[step('canais','Seguir a água','Examine o canal lateral.',site('canais','Canal do Domo','domo',10,15,'ava',['O canal lateral está seco; o central transborda. Uma divisória móvel pode repartir a água, sem retirar nenhuma planta.'])),step('repartir','Cuidado distribuído','Ajuste a divisória.',site('repartir','Divisória de irrigação','domo',10,15,'ava',['Qual ajuste serve às duas raízes com a água que existe?'],'puzzle',[answer('dividir','Dividir o fluxo entre os canteiros','A água alcança as raízes laterais e o centro deixa de transbordar.',true),answer('central','Manter toda a água no centro','O centro já transborda. As raízes laterais continuariam sem cuidado.')]))]),
 quest('short-retorno','Uma seta para quem volta','short','As placas do Subterrâneo apontam só para o fundo. Dê também um caminho de volta.','Beatriz',2,[step('placa','A orientação incompleta','Examine a placa junto à entrada.',site('placa','Placa da descida','subsolo',6,4,'beatriz',['A placa nomeia o selo, mas omite a biblioteca. Quem vem ferido precisa saber onde descansar.'])),step('corrigir','Uma saída também é um destino','Registre a direção do retorno.',site('corrigir','Placa da biblioteca','subsolo',6,4,'beatriz',['A biblioteca fica pela escada ao noroeste. Qual indicação ajuda a voltar?'],'puzzle',[answer('biblioteca','“Biblioteca e cristal: retorno ao noroeste.”','A placa passa a indicar saída e cuidado, além do objetivo da expedição.',true),answer('selo','“Siga sempre para o selo.”','A pergunta é como voltar. A placa já indicava o fundo.')]))]),
 quest('tutorial-diario','Meu primeiro registro','tutorial','Conheça o diário e escolha o objetivo que deseja acompanhar.','Beatriz',0,[eventStep('abrir','Abrir o diário','Abra Diário no menu para ver etapas e prêmios em tiros.','ui','journal-open'),eventStep('rastrear','Rastrear uma missão','Use Rastrear em qualquer missão aceita.','track')]),
 quest('tutorial-mapa','Ler antes de partir','tutorial','Veja as saídas do cenário e realize uma viagem segura.','Orfeu',0,[eventStep('mapa','Consultar Mapa · Viagens','Abra Mapa · Viagens e localize uma saída.','ui','map-open'),eventStep('viajar','Atravessar uma saída','Viaje para outro cenário por uma porta alcançável.','travel')]),
 quest('tutorial-passos','O caminho sob os pés','tutorial','Pratique movimento até um ponto seguro e confirme sua chegada.','Seiji',0,[eventStep('andar','Percorrer seis passos','Caminhe seis unidades no mundo por teclado ou apontando o caminho.','move',undefined,6),step('marca','Conferir a marca','Leia a marca de treino no pátio.',site('marca','Marca de treino do pátio','patio',15,12,'seiji',['Chegar não exige pressa. Você pode apontar um lugar, usar as setas e interromper o caminho a qualquer momento.']))]),
 quest('tutorial-lider','Quem conduz a próxima rua','tutorial','Conheça os slots fixos do Grupo e selecione um líder sem mudar a ordem.','Marin',0,[eventStep('grupo','Consultar o Grupo','Abra Grupo e veja os slots atuais.','ui','party-open'),eventStep('lider','Selecionar um slot de líder','Use 1–5 na exploração ou Liderar exploração no Grupo. Selecionar o único líder também vale.','leader')]),
 quest('tutorial-cristal','Um lugar para retornar','tutorial','Ative um cristal para guardar o caminho de volta e restaurar o grupo gratuitamente.','Ophelia',0,[eventStep('cristal','Usar um cristal real','Interaja com qualquer cristal de descanso no mundo.','crystal')]),
 quest('tutorial-bolsa','Preparar sem desperdiçar','tutorial','Leia a função de um item sem precisar gastá-lo.','Ava',0,[eventStep('bolsa','Consultar a Bolsa','Abra Bolsa e compare Poção e Elixir de Éter. Nenhum uso é necessário.','ui','bag-open'),step('nota','Conferir a preparação','Leia o conselho junto ao cristal do pátio.',site('nota','Conselho de preparação','patio',21,12,'ava',['Poção recupera HP; Elixir recupera MP. Use quando houver perda real. Cristais restauram o grupo sem consumir itens.']))]),
 quest('tutorial-invocacao','O preço de uma esperança','tutorial','Veja preços, chances e garantias da invocação sem gastar cristais ou fichas.','Beatriz',0,[eventStep('regras','Consultar as regras de invocação','Abra Convocar e leia as regras de invocação. Nenhum sorteio é necessário.','ui','gacha-preview'),step('nota','Reconhecer o custo','Confirme o aviso do cais.',site('nota','Beatriz · escolhas de invocação','porto',22,12,'beatriz',['Um tiro de personagem custa 160 cristais. Estes prêmios usam esse mesmo saldo. Chances e garantias não tornam uma escolha obrigatória.','Guarde os recursos enquanto decide. Ler as regras já conclui o aprendizado; não é preciso sortear.']))]),
 quest('tutorial-catalogo','Conhecer sem possuir','tutorial','Descubra o catálogo de heróis e companheiros. Não é preciso recrutar para ler.','Orfeu',0,[eventStep('catalogo','Abrir o catálogo','Abra Convocar, entre em Lista de Espera e use Detalhes para conhecer um personagem e seu companheiro. Não precisa possuir o personagem.','ui','catalog-open'),step('nota','O registro não é uma posse','Leia a nota no Arquivo.',site('nota','Orfeu · catálogo aberto','arquivo',12,14,'orfeu',['Conhecer uma história não é possuir quem a viveu. O catálogo fica aberto mesmo antes do recrutamento.']))]),
 quest('tutorial-guarda','Um turno para proteger','tutorial','Pratique a guarda contra uma sombra de treino. O duelo não cobra itens, MP nem fichas.','Gabriel',0,[step('treino','Iniciar treino gratuito','Encontre Gabriel no pátio. Você receberá um exercício de guarda, com recuperação gratuita ao final.',fight('treino','Gabriel · treino de guarda','patio',16,14,'gabriel',['Este eco de treino cede depois que o grupo guarda. Sua guarda reduz o próximo golpe. Não precisamos usar magia nem gastar itens.'],'sombra','shadow',36,1)),eventStep('guarda','Executar Guardar em combate','No treino, use Guardar. Depois conclua o combate para devolver o eco.','action','guard'),eventStep('encerrar','Concluir o exercício','Vença o eco de treino. O grupo recupera suas condições anteriores.','victory','training-guard')]),
 quest('tutorial-ritmo','O jogo no seu ritmo','tutorial','Encontre som e movimento reduzido; as preferências pertencem a você. Não é preciso ativar áudio.','Max',0,[eventStep('ajustes','Consultar as configurações','Abra Sistema, consulte Som e leia como o jogo acompanha a preferência de movimento reduzido do seu dispositivo. Não precisa mudar nenhum valor.','ui','settings-open'),step('nota','Uma preferência é sua','Leia o conselho no pátio.',site('nota','Max · ritmo pessoal','patio',14,14,'max',['Som desligado continua desligado até você ativar. A preferência de movimento reduzido do dispositivo altera a apresentação, nunca chances ou prêmios. O ritmo é seu.']))]),
];

export const questByIdV31=(id:string)=>QUESTS_V31.find(q=>q.id===id);
export const questEntityIdV31=(questId:string,siteId:string)=>`v31:${questId}:${siteId}`;
export const QUEST_SITES_V31=QUESTS_V31.flatMap(q=>q.steps.flatMap((s,stepIndex)=>s.sites.map(site=>({questId:q.id,stepIndex,...site,entityId:questEntityIdV31(q.id,site.id)}))));
export const questSiteByEntityV31=(id:string)=>QUEST_SITES_V31.find(s=>s.entityId===id);
export const QUEST_UI_EVENTS_V31=['journal-open','map-open','party-open','bag-open','gacha-preview','catalog-open','settings-open'] as const;
export type QuestUIEventV31=typeof QUEST_UI_EVENTS_V31[number];
