import {REMAKE_ASSETS_SEIJI_OPHELIA,REMAKE_FRAMES_SEIJI_OPHELIA} from './remakeArtSeijiOphelia';
import {REMAKE_ASSETS_GABRIEL_MARIN_MAX,REMAKE_FRAMES_GABRIEL_MARIN_MAX} from './remakeArtGabrielMarinMax';
import {REMAKE_ASSETS_CARMILLA_BEATRIZ_ABEL,REMAKE_FRAMES_CARMILLA_BEATRIZ_ABEL} from './remakeArtCarmillaBeatrizAbel';

// Apply after legacy registrations; Ava and Orfeu retain their approved sources.
export const REMAKE_ASSETS={...REMAKE_ASSETS_SEIJI_OPHELIA,...REMAKE_ASSETS_GABRIEL_MARIN_MAX,...REMAKE_ASSETS_CARMILLA_BEATRIZ_ABEL};
export const REMAKE_FRAMES={...REMAKE_FRAMES_SEIJI_OPHELIA,...REMAKE_FRAMES_GABRIEL_MARIN_MAX,...REMAKE_FRAMES_CARMILLA_BEATRIZ_ABEL};
