export type SummonRarity=3|4|5;
export type SummonedHero={id:string;name:string;rarity:4|5;element:string;role:string;hero?:string;title:string;description:string;ultimate:string;bond:string;accent:string;art?:string};

export const SUMMONED_HEROES:SummonedHero[]=[
 {id:'seiji-awakened',name:'Seiji — Despertar da Lâmina',rarity:4,hero:'seiji',element:'Tinta Abissal',role:'DPS / Controle',title:'O Escriba que Cortou a Noite',description:'Traje de duelista gasto, fivelas douradas e runas de tinta viva sobre a mão que segura a lâmina.',ultimate:'“Que o nome apagado responda.” O Códice se abre e uma maré de tinta corta o campo.',bond:'Reconstrua uma página proibida no Arquivo Central.',accent:'#5375d8'},
 {id:'ophelia-awakened',name:'Ophelia — Coroa do Inverno Sereno',rarity:4,hero:'ophelia',element:'Gelo Astral',role:'Suporte / Controle',title:'A Guardiã do Orvalho Branco',description:'Vestes cerimoniais de inverno, prata antiga e uma cicatriz de mana que brilha como aurora sob a pele.',ultimate:'“Neve que não esquece, cubra-nos.” Um inverno silencioso protege aliados e prende inimigos.',bond:'Ajude Ophelia a estabilizar o Domo de Geada.',accent:'#8edff2'},
 {id:'marin-awakened',name:'Marin — Herdeira da Hora Sem Estrelas',rarity:4,hero:'marin',element:'Treva Lunar',role:'DPS Burst',title:'A Nobre da Última Hora',description:'Uma capa rasgada de nobre decaída, correntes de ouro fosco e runas lunares gravadas na espada.',ultimate:'“Quando a última estrela cair, eu ainda estarei aqui.” A lua apaga e a lâmina decide.',bond:'Encontre a vigília abandonada além da Mata Cindária.',accent:'#9371db'},
 {id:'gabriel-awakened',name:'Gabriel — Fera da Forja Celestial',rarity:4,hero:'gabriel',element:'Chama Celestial',role:'Tanque / Sustentado',title:'O Juramento que Ardendo Permanece',description:'Armadura de viagem marcada por batalha, metal luminoso e o Éter ardendo entre antigas cicatrizes.',ultimate:'“Forja, reconhece este coração.” Uma forma bestial de fogo intercepta todo o dano do grupo.',bond:'Suporte a prova de fogo da Oficina Alta.',accent:'#f59b57'},
 {id:'max-awakened',name:'Max — Trovão Costurado',rarity:4,hero:'max',element:'Plasma de Éter',role:'DPS / Quebra',title:'O Morto-Vivo que Ri da Tempestade',description:'Casaco preto e laranja recomposto à mão; costuras de mana riscam a pele pálida como relâmpagos.',ultimate:'“Vajra, faz barulho.” A tempestade costura o céu ao chão com um único trovão.',bond:'Siga o rastro de Vajra até o antigo campanário.',accent:'#f2c95c'},
 {id:'orfeu',name:'Orfeu Bauss — Primeiro Som',rarity:5,element:'Eco de Éter',role:'Suporte / Controle',title:'Professor da Biblioteca',description:'Cabelo branco curto, pele morena, braços nus e enfaixados. Seu traje azul-marinho assimétrico conduz anéis sonoros de Éter.',ultimate:'“Escutem o que a pedra reteve.” Um pulso de ressonância alcança todo o campo.',bond:'Aula de Vínculo: A Primeira Palavra.',accent:'#8ea7ff',art:'/assets/v22/orfeu-5star.webp'},
 {id:'beatriz',name:'Beatriz Demeter — Maré Umbral',rarity:5,element:'Água / Trevas',role:'Controle / Proteção',title:'Mestra do Pátio Central',description:'Cabelo negro, olhos violetas, chapéu de bruxa e casaco branco. Sua espada corta entre correntes d’água e orbes de trevas.',ultimate:'“Uma margem para os nossos; a profundidade para vocês.” Água e sombra cruzam o campo.',bond:'Aula de Vínculo: A Margem Oculta.',accent:'#8e9df4',art:'/assets/v22/beatriz-5star.webp'},
 {id:'ava',name:'Ava Rosa Groot — Jardim Indomável',rarity:5,element:'Natureza',role:'Controle / Cura',title:'Professora do Domo',description:'Cachos castanhos cobertos de flores. Fora de combate leva seu cajado e manto verde; na forma fighter luta com punhos enfaixados e vinhas floridas.',ultimate:'“Floresçam onde a pedra disse não.” Raízes protegem aliados e imobilizam inimigos.',bond:'Aula de Vínculo: Sementes que Acordam.',accent:'#9be2c5',art:'/assets/v22/ava-fighter-5star.webp'},
 {id:'abel',name:'Abel Nomikos — Fogo Primordial',rarity:5,element:'Fogo Primordial',role:'DPS Técnico',title:'Professor da Forja Antiga',description:'Cabelo vermelho, pele morena, óculos de aro dourado e manto rubro. Runas ardem nos braços enquanto empunha o cajado de cristal vermelho.',ultimate:'“Não é chama. É o começo.” Seu cajado abre um círculo de fogo primordial sobre o campo.',bond:'Aula de Vínculo: A Chama sem Encanto.',accent:'#f17855',art:'/assets/v22/abel-5star.webp'}
];

export const summonedById=(id:string)=>SUMMONED_HEROES.find(hero=>hero.id===id);
